version: "3"

services:
  server:
    image: jetbrains/teamcity-server:2017.2.4
    container_name: tc-server
    ports:
      - "8111:8111"
    volumes:
      - ./datadir:/data/teamcity_server/datadir
      - ./logs:/opt/teamcity/logs
    environment:
      - TZ=Asia/Taipei
  agent1:
    image: jianminhuang/teamcity-agent:1.0.0
    container_name: tc-agent1
    environment:
      - TZ=Asia/Taipei
      - SERVER_URL=http://server:8111
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  agent2:
    image: jianminhuang/teamcity-agent:1.0.0
    container_name: tc-agent2
    environment:
      - TZ=Asia/Taipei
      - SERVER_URL=http://server:8111
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
