window.__adroll||(function(){function l(){this.exp=5E4;this.eexp=720;this.pv=1E11*Math.random();this.__adc="__ar_v4";this._nad=0;this._lce=null;this._loaded=this._broken=!1;this._url=2E3;this._kwl=300;this._r={};this._logs=[]};l.prototype.cookieEnabled=function(a){if(this._global("adroll_ext_network")||this._global("adroll_optout")||this._broken)return!1;if(2<=this._nad||a)return this._lce;this.set("_te_","1");return"1"===this.get("_te_")?(this.del("_te_"),0<this._nad&&!this.get(this.__adc)?this._lce=!1:this._lce=!0):this._lce=!1};
l.prototype.get=function(a){var c=window.document.cookie;if(null===c)return this._broken=!0,null;var b;0>c.indexOf(a+"=")?c=null:(a=c.indexOf(a+"=")+a.length+1,b=c.indexOf(";",a),-1===b&&(b=c.length),c=c.substring(a,b),c=""===c?null:window.unescape(c));return c};
l.prototype.set=function(a,c,b){var d;b&&"number"===typeof b?(d=new Date,d.setTime(d.getTime()+36E5*b),b=d.toGMTString(),b="; expires="+b):b="";d="; domain="+window.location.hostname;c=window.escape(c);window.document.cookie=a+"="+c+b+"; path=/"+d};l.prototype.del=function(a){this.set(a,"",-8760)};
l.prototype.check_cookie=function(a,c){if(this._global("adroll_ext_network")||this._global("adroll_optout"))return"";for(var b=a.split("|"),d=b.length-1;0<=d;d--)if(b[d]){var f=b[d].split(":");c===f[0]&&(f[2]=""+(parseInt(f[2])+1),b[d]=f.join(":"))}return b.join("|")};l.prototype.handle=function(a){var c=this.get(this.__adc)||"";-1!==c.indexOf(a)?this.set(this.__adc,this.check_cookie(c,a),this.exp):(a=[c,[a,this.get_date(this.eexp),"1"].join(":")].join("|"),this.set(this.__adc,a,this.exp))};
l.prototype.expire_old=function(){if(!this._global("adroll_ext_network")&&!this._global("adroll_optout")){for(var a=this.get_date(!1),c=this.get(this.__adc),c=c?c.split("|"):[""],b=[],d=c.length-1;0<=d;d--)c[d]&&c[d].split(":")[1]>a&&b.push(c[d]);this.set(this.__adc,b.join("|"),this.exp)}};l.prototype.get_date=function(a){var c=new Date;a&&c.setTime(c.getTime()+36E5*a);a=""+c.getUTCFullYear();var b=c.getUTCMonth(),b=10<=b?b:"0"+b,c=c.getUTCDate();return[a,b,10<=c?c:"0"+c].join("")};l.prototype.generate_link=function(){return""};l.prototype.view=function(a){var c=new window.Image;c.src=this._srv("/view/"+a);c.setAttribute("width","1");c.setAttribute("height","1");c.setAttribute("border","0");this._head().appendChild(c)};l.prototype.set_cookie=function(){};
l.prototype.reset=function(){this._set_global("adroll_c_id",null);this._set_global("adroll_url_macro","");this._set_global("adroll_c_macro","");this._set_global("adroll_cpm_macro","");this._set_global("adroll_ext_network",null);this._set_global("adroll_subnetwork",null);this._set_global("adroll_ad_payload",null);this._set_global("adroll_win_notif",null)};l.prototype.set_pixel_cookie=function(a,c,b){this._global("adroll_optout")||(this.handle(a),this.handle(c),this.handle(b),this.pixel_loaded())};
l.prototype.add_pixel_load_callback=function(a){this._loaded?a():this._ensure_global("adroll_callbacks",[]).push(a)};l.prototype.pixel_loaded=function(){this._loaded=!0;for(var a=this._ensure_global("adroll_callbacks",[]),c=0;c<a.length;c++)a[c].called||(a[c](),a[c].called=!0)};l.prototype.addLoadEvent=function(a){if(this._has_global("__adroll_loaded")&&this._global("__adroll_loaded")||this._has_global("_adroll_ie")&&this._global("_adroll_ie")||/msie/i.test(window.navigator.userAgent))return a();if(/WebKit/i.test(window.navigator.userAgent)){var c=window.setInterval(function(){/loaded|complete/.test(window.document.readyState)&&window.clearInterval(c);a()},10);return null}var b=window.onload;window.onload=function(){a();b&&b()}};
l.prototype._head=function(){return(window.document.getElementsByTagName("head")||[null])[0]||(window.document.getElementsByTagName("body")||[null])[0]||window.document.getElementsByTagName("script")[0].parentNode};l.prototype.external_data_to_qs=function(a){var c=[],b=this.get_external_data();if(!b)return null;for(var d in b)b.hasOwnProperty(d)&&this._is_defined(b[d])&&null!==b[d]&&c.push(this.normalize_var(window.escape(""+d)+"="+window.escape(""+b[d]),!1));c=c.join("&");a&&(c=window.escape(c));return"adroll_external_data="+c};
l.prototype.replace_external_data=function(a){var c=this.get_external_data(),b=this.get_conversion_value(),d=null,f;if(c)for(f in c)c.hasOwnProperty(f)&&(d=new RegExp("\\["+f+"\\]","gi"),a=a.replace(d,c[f]),d=new RegExp("\\["+f+"_ESC\\]","gi"),a=a.replace(d,window.escape(c[f])));if(b)for(f in b)b.hasOwnProperty(f)&&(d=new RegExp("\\["+f+"\\]","gi"),a=a.replace(d,b[f]),d=new RegExp("\\["+f+"_ESC\\]","gi"),a=a.replace(d,window.escape(b[f])));return a};
l.prototype.get_external_data=function(){if(this._has_global("adroll_custom_data")){var a=this._global("adroll_custom_data"),c={},b;for(b in a)a.hasOwnProperty(b)&&"undefined"!==a[b]&&(c[b.toLowerCase()]=a[b]);return c}return null};
l.prototype.get_conversion_value=function(){var a=this._ensure_global("adroll_currency",null),c=this._ensure_global("adroll_conversion_value",null),b=this._ensure_global("adroll_conversion_value_in_dollars",null);return c?{conv_value:""+c,currency:a}:b?{conv_value:""+parseInt(100*b),currency:"USC"}:null};l.prototype._has_global=function(a){return this._is_defined(this._global(a))};l.prototype._global=function(a){return window[a]};l.prototype._set_global=function(a,c){window[a]=c};l.prototype._unset_global=function(a){delete window[a]};l.prototype._ensure_global=function(a,c){this._has_global(a)||this._set_global(a,c);return this._global(a)};l.prototype.btoi=function(a){return a.includes(null)?null:parseInt(a.concat().reverse().join(""),2)};l.prototype.hstsImgUrl=function(a){return"https://"+a+".ar1d.net/id/q"};l.prototype.hstsBitUrl=function(a){return this.hstsImgUrl("p"+a)};l.prototype.hstsCheckFlag=function(a,c){fetch(a).then(function(a){c&&c.call(this,0===a.url.indexOf("https:"))}.bind(this))["catch"](function(){c.call(this,!1)}.bind(this))};l.prototype.hstsMaxBits=function(){return 32};l.prototype.hstsVersion=function(){return"3"};
l.prototype.hstsCacheName=function(a){return"__ar1d"+(a||"")};l.prototype.hstsCacheVersion=function(){return"__ar1d_v"};l.prototype.hstsOptoutCacheName=function(){return"__ar1d_optout"};l.prototype.hstsRead=function(a){function c(c){this.hstsCheckFlag(this.hstsBitUrl(c),function(d){b[c]=d?"1":"0";d=this.btoi(b);null!==d&&a&&a.call(this,d)}.bind(this))}var b=Array(this.hstsMaxBits()),d=b.length,f;for(f=0;f<d;f++)b[f]=null;for(f=d-1;0<=f;f--)b[f]=null,c.call(this,f)};
l.prototype.precache_tpc=function(){function a(a){return"https://"+a+".ar1d.net/p.gif"}var c=this.hstsMaxBits(),b;this.imgRequest(a.call(this,"isset"));this.imgRequest(a.call(this,"hsts3"));for(b=0;b<c;b++)this.imgRequest(a.call(this,"p"+b))};l.prototype.getSafariVersion=function(){var a=/^Mozilla\/5\.0 \([^)]+\) AppleWebKit\/[^ ]+ \(KHTML, like Gecko\) Version\/([^ ]+)( Mobile\/[^ ]+)? Safari\/[^ ]+$/i.exec(navigator.userAgent);return a?a[1]:null};
l.prototype.check_tpc_optout=function(a){var c=this.hstsOptoutCacheName(),b=this.get(c);b&&a.call(this,parseInt(b,10));this.hstsCheckFlag(this.hstsImgUrl("optout"),function(b){b&&this.set(c,1);a&&a.call(this,b?1:0)}.bind(this))};
l.prototype.get_tpc_cookie=function(a){var c=this.hstsCacheName(this.hstsVersion()),b=this.get(c);if(b)return a.call(this,b);this.hstsCheckFlag(this.hstsImgUrl("hsts3"),function(b){if(!b)return a.call(this,null);this.hstsRead(function(b){(b=b?this.md5(String(b)):null)&&this.set(c,b,8760);a.call(this,b)}.bind(this))}.bind(this))};l.prototype.jsonStringify=function(a){this.jsonStringifyFunc||this.initJsonStringify();return this.jsonStringifyFunc(a)};l.prototype.jsonParse=function(a){var c=this._global("JSON");return"function"===typeof c.parse?c.parse(a):eval("("+a+")")};
l.prototype.initJsonStringify=function(){var a=this._global("JSON");this.jsonStringifyFunc=a||a.stringify&&"function"===typeof a.stringify?a.stringify:function(){function a(c){return f[c]||"\\u"+(c.charCodeAt(0)+65536).toString(16).substr(1)}var b=Object.prototype.toString,d=Array.isArray||function(a){return"[object Array]"===b.call(a)},f={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"},n=/[\\"\u0000-\u001F\u2028\u2029]/g;return function q(k){if(null===k)return"null";
if("number"===typeof k)return isFinite(k)?k.toString():"null";if("boolean"===typeof k)return k.toString();if("object"===typeof k){if("function"===typeof k.toJSON)return q(k.toJSON());if(d(k)){for(var e="[",h=0;h<k.length;h++)e+=(h?", ":"")+q(k[h]);return e+"]"}if("[object Object]"===b.call(k)){e=[];for(h in k)k.hasOwnProperty(h)&&e.push(q(h)+": "+q(k[h]));return"{"+e.join(", ")+"}"}}return'"'+k.toString().replace(n,a)+'"'}}()};l.prototype.macro_values=function(){var a=this._ensure_global("adroll_cpm_macro",null),c=this._ensure_global("adroll_url_macro",null),b=this._ensure_global("adroll_c_macro",null),d=this._ensure_global("adroll_subnetwork",null),f=this._ensure_global("adroll_ad_payload",null),n=this._ensure_global("adroll_win_notif",null),p=this._ensure_global("adroll_rtb_dict",null),q={r:/^\$\{.*\}$/i,g:/^%%.*%%$/i,b:/^\[.*\]$/i,x:/^\$\{.*\}$/i,t:/INSERTCLICKTRACKER/}[this._global("adroll_ext_network")],q=this._is_defined(q)?
q:/CANNOT_MATCH_THIS/,k={};a&&!q.test(a)&&(k.adroll_cpm_macro=a);c&&!q.test(c)&&(k.adroll_url_macro=c);b&&!q.test(b)&&(k.adroll_c_macro=b);d&&!q.test(d)&&(k.adroll_subnetwork=d);f&&!q.test(f)&&(k.adroll_ad_payload=f);n&&!/^[|$]/.test(n)&&(k.adroll_win_notif=n);if(p&&("string"!==typeof p||!/^[|$]/.test(p))){if("string"===typeof p)try{0===p.indexOf("b64:")&&(p=atob(p.substr(4))),p=this.jsonParse(p)}catch(e){this.log("failed to parse: "+e),p={}}"object"===typeof p&&(k.adroll_rtb_dict=p)}return k};
l.prototype.format_macros=function(a,c,b,d){return this.macro_url_params(this.macro_values(),a,c,b,d)};
l.prototype.macro_url_params=function(a,c,b,d,f){f=this._is_defined(f)?f:!1;var n=d?window.escape:function(a){return a},p=a.adroll_cpm_macro,q=a.adroll_url_macro,k=b?a.adroll_c_macro:null,e=[],h=c?this.parseUri(c):null,h=h?this.endswith(h.path,".tp"):!1;!h&&f&&e.push(["desturl",""]);k&&0===k.indexOf("http")?(f=n,"g"===this._global("adroll_ext_network")&&(f=d?function(a){return a}:window.unescape),e.push(["clickurl",f(k)])):h&&f&&e.push(["clickurl",""]);this._global("adroll_ext_network")&&e.push(["adroll_network",
this._global("adroll_ext_network")]);p&&e.push(["cpm",p]);a.adroll_subnetwork&&e.push(["adroll_subnetwork",a.adroll_subnetwork]);a.adroll_ad_payload&&e.push(["adroll_ad_payload",a.adroll_ad_payload]);q&&(a=this.parseUri(window.unescape(q)),e.push(["site_url",n("http://"+a.host)]),b&&(e.push(["adroll_width",n(this._global("adroll_width"))]),e.push(["adroll_height",n(this._global("adroll_height"))])));this.log("Macros found "+this.serialize(e));return c?this.buildurl(c,e):this.serialize(e)};
l.prototype.serialize=function(a){if(a.length){for(var c=[],b=a.length-1;0<=b;b--)c.push(a[b].join("="));return c.join("&")}return""};l.prototype.endswith=function(a,c){return-1!==a.indexOf(c,a.length-c.length)};l.prototype.buildurl=function(a,c){var b=this.serialize(c),d=a.indexOf("?");return b?d===a.length-1?a+b:-1!==d?"&"===a[a.length-1]?a+b:a+"&"+b:a+"?"+b:a};l.prototype.md5=function(){function a(a,c){var b=(a&65535)+(c&65535);return(a>>16)+(c>>16)+(b>>16)<<16|b&65535}function c(c,b,d,h,g,f){b=a(a(b,c),a(h,f));return a(b<<g|b>>>32-g,d)}function b(a,b,d,h,g,f,n){return c(b&d|~b&h,a,b,g,f,n)}function d(a,b,d,h,g,f,n){return c(b&h|d&~h,a,b,g,f,n)}function f(a,b,d,h,g,f,n){return c(d^(b|~h),a,b,g,f,n)}function n(n,k){var e=n[0],h=n[1],g=n[2],m=n[3],e=b(e,h,g,m,k[0],7,-680876936),m=b(m,e,h,g,k[1],12,-389564586),g=b(g,m,e,h,k[2],17,606105819),h=b(h,g,m,e,k[3],
22,-1044525330),e=b(e,h,g,m,k[4],7,-176418897),m=b(m,e,h,g,k[5],12,1200080426),g=b(g,m,e,h,k[6],17,-1473231341),h=b(h,g,m,e,k[7],22,-45705983),e=b(e,h,g,m,k[8],7,1770035416),m=b(m,e,h,g,k[9],12,-1958414417),g=b(g,m,e,h,k[10],17,-42063),h=b(h,g,m,e,k[11],22,-1990404162),e=b(e,h,g,m,k[12],7,1804603682),m=b(m,e,h,g,k[13],12,-40341101),g=b(g,m,e,h,k[14],17,-1502002290),h=b(h,g,m,e,k[15],22,1236535329),e=d(e,h,g,m,k[1],5,-165796510),m=d(m,e,h,g,k[6],9,-1069501632),g=d(g,m,e,h,k[11],14,643717713),h=d(h,
g,m,e,k[0],20,-373897302),e=d(e,h,g,m,k[5],5,-701558691),m=d(m,e,h,g,k[10],9,38016083),g=d(g,m,e,h,k[15],14,-660478335),h=d(h,g,m,e,k[4],20,-405537848),e=d(e,h,g,m,k[9],5,568446438),m=d(m,e,h,g,k[14],9,-1019803690),g=d(g,m,e,h,k[3],14,-187363961),h=d(h,g,m,e,k[8],20,1163531501),e=d(e,h,g,m,k[13],5,-1444681467),m=d(m,e,h,g,k[2],9,-51403784),g=d(g,m,e,h,k[7],14,1735328473),h=d(h,g,m,e,k[12],20,-1926607734),e=c(h^g^m,e,h,k[5],4,-378558),m=c(e^h^g,m,e,k[8],11,-2022574463),g=c(m^e^h,g,m,k[11],16,1839030562),
h=c(g^m^e,h,g,k[14],23,-35309556),e=c(h^g^m,e,h,k[1],4,-1530992060),m=c(e^h^g,m,e,k[4],11,1272893353),g=c(m^e^h,g,m,k[7],16,-155497632),h=c(g^m^e,h,g,k[10],23,-1094730640),e=c(h^g^m,e,h,k[13],4,681279174),m=c(e^h^g,m,e,k[0],11,-358537222),g=c(m^e^h,g,m,k[3],16,-722521979),h=c(g^m^e,h,g,k[6],23,76029189),e=c(h^g^m,e,h,k[9],4,-640364487),m=c(e^h^g,m,e,k[12],11,-421815835),g=c(m^e^h,g,m,k[15],16,530742520),h=c(g^m^e,h,g,k[2],23,-995338651),e=f(e,h,g,m,k[0],6,-198630844),m=f(m,e,h,g,k[7],10,1126891415),
g=f(g,m,e,h,k[14],15,-1416354905),h=f(h,g,m,e,k[5],21,-57434055),e=f(e,h,g,m,k[12],6,1700485571),m=f(m,e,h,g,k[3],10,-1894986606),g=f(g,m,e,h,k[10],15,-1051523),h=f(h,g,m,e,k[1],21,-2054922799),e=f(e,h,g,m,k[8],6,1873313359),m=f(m,e,h,g,k[15],10,-30611744),g=f(g,m,e,h,k[6],15,-1560198380),h=f(h,g,m,e,k[13],21,1309151649),e=f(e,h,g,m,k[4],6,-145523070),m=f(m,e,h,g,k[11],10,-1120210379),g=f(g,m,e,h,k[2],15,718787259),h=f(h,g,m,e,k[9],21,-343485551);n[0]=a(e,n[0]);n[1]=a(h,n[1]);n[2]=a(g,n[2]);n[3]=
a(m,n[3])}var p="0123456789abcdef".split("");return function(a){var b=a;/[\x80-\xFF]/.test(b)&&(b=unescape(encodeURI(b)));var c=b.length;a=[1732584193,-271733879,-1732584194,271733878];var d;for(d=64;d<=b.length;d+=64){for(var g=b.substring(d-64,d),f=[],r=void 0,r=0;64>r;r+=4)f[r>>2]=g.charCodeAt(r)+(g.charCodeAt(r+1)<<8)+(g.charCodeAt(r+2)<<16)+(g.charCodeAt(r+3)<<24);n(a,f)}b=b.substring(d-64);g=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(d=0;d<b.length;d++)g[d>>2]|=b.charCodeAt(d)<<(d%4<<3);g[d>>2]|=
128<<(d%4<<3);if(55<d)for(n(a,g),d=0;16>d;d++)g[d]=0;g[14]=8*c;n(a,g);for(b=0;b<a.length;b++){c=a;d=b;g=a[b];f="";for(r=0;4>r;r++)f+=p[g>>8*r+4&15]+p[g>>8*r&15];c[d]=f}return a.join("")}}();l.prototype._gurl=function(){var a=window.location;return this.normalize_url(a.pathname+a.search)};l.prototype.get_dummy_product_for_facebook=function(a){return{product_id:"adroll_dummy_product",product_group:a,product_action:null,product_category:null}};l.prototype.facebook_dummy_product_enabled=function(){return!0};
l.prototype.extract_pid=function(a,c,b){function d(a){return a?(a=new RegExp(a,"gi"),!!a.exec(k)):null}a||(a={});var f=null,n=null,p=null,q=null,k=this._gurl(),e=this.get_external_data();e&&(n=e.product_id,f=e.product_group,p=e.product_action,q=e.adroll_product_category_id);if(!n&&a.regexp_group&&!("string"===a.regexp_group&&a.regexp_group instanceof String)&&"html"===a.regexp_group.scheme){if(d(a.blacklist_regexp)||!0!==d(a.regexp))return"";n=this.get_product_id_from_dom(a.regexp_group)}else if(!n){if(d(a.blacklist_regexp))return"";
n=this.get_product_id_from_url(k,a.regexp,a.regexp_group)}f||!a.product_group_group||"string"===a.product_group_group&&a.product_group_group instanceof String||"html"!==a.product_group_group.scheme?f||a.product_group_regexp&&(f=this.get_product_id_from_url(k,a.product_group_regexp,a.product_group_group)):f=this.get_product_id_from_dom(a.product_group_group);if(n)a={product_id:n,product_group:f,product_action:p,product_category:q};else if(this.facebook_dummy_product_enabled()&&"facebook"===c)a=this.get_dummy_product_for_facebook(f);
else return null;b&&b(a);return a};
l.prototype.get_pid=function(a){this.extract_pid(a,"adroll",function(a){if(a){var b=a.product_id,d=a.product_group,f=a.product_action,n=a.product_category;a=[];var p;if(b instanceof Array)for(p=0;p<b.length;p++)a.push(["adroll_product_id",this.normalize_var((b[p]+"").toLowerCase(),!0)]);else a.push(["adroll_product_id",this.normalize_var((b+"").toLowerCase(),!0)]);if(n instanceof Array)for(p=0;p<n.length;p++)a.push(["adroll_product_category_id",this.normalize_var((n[p]+"").toLowerCase(),!0)]);else n&&
a.push(["adroll_product_category_id",this.normalize_var((n+"").toLowerCase(),!0)]);d&&a.push(["adroll_product_group",this.normalize_var((d+"").toLowerCase(),!0)]);f&&a.push(["adroll_product_action",this.normalize_var((f+"").toLowerCase(),!0)]);(b=this.external_data_to_qs(!0))&&a.push([b]);b=this._srv(this.buildurl("/p/"+this._global("adroll_adv_id")+"/",a));d=window.document.createElement("img");d.src=b;d.height=d.width=1;d.border=0;this._head().appendChild(d)}}.bind(this))};
l.prototype.get_product_id_from_dom=function(a){var c=null,b;a.path&&(window.jQuery?(b=window.jQuery(a.path),b.length&&(b=b.eq(0),c="text"===a.attribute?b.text():b.attr(a.attribute))):window.Prototype&&window.$$?(b=window.$$(a.path),b.length&&(b=b[0],c="text"===a.attribute?b.innerText&&!window.opera?b.innerText:b.innerHTML.stripScripts().unescapeHTML().replace(/[\n\r\s]+/g," "):b.readAttribute(a.attribute))):window.YUI?(b=window.YUI().use("node"),b.one&&(b=b.one(a.path),c=null,b&&(c="text"===a.attribute?
b.get("text"):b.getAttribute(a.attribute)))):window.$$&&(b=window.$$(a.path),b.length&&(b=b[0],c="text"===a.attribute?b.get("text"):b.getProperty(a.attribute))));if(c&&(c=c.replace(/^\s\s*/,"").replace(/\s\s*$/,""),a.regular_expression&&a.regular_expression_replace))if(b=new RegExp(a.regular_expression,"gi"),c=b.exec(c),null!==c){a=a.regular_expression_replace;for(b=0;b<c.length;b++)a=a.replace(new RegExp("\\\\"+b,"gi"),c[b]||"");c=a}else c="";return c};
l.prototype.get_product_id_from_url=function(a,c,b){var d=null;try{d=parseInt(b)}catch(f){}return null!==d&&!isNaN(d)&&c&&(a=(new RegExp(c,"gi")).exec(a),null!==a&&d in a)?a[d]:null};l.prototype.render_pixel_code=function(a,c){this._has_global("adroll_tpc")?this.render_pixel_code_exec(a,c):this.load_adroll_tpc(function(){this.render_pixel_code_exec(a,c)}.bind(this))};
l.prototype.render_pixel_code_exec=function(a,c){this.expire_old();var b=this._srv("/pixel"),d=window.document.createElement("script");d.setAttribute("async","true");d.type="text/javascript";var f=this.get_keywords();this.addLoadEvent(function(n){return function(){var p=[];try{200>=window.document.referrer.length&&p.push("adroll_s_ref="+window.escape(window.document.referrer))}catch(r){}try{p.push("keyw="+window.escape(f))}catch(r){}try{n._has_global("adroll_segments")&&p.push("name="+window.escape(n._global("adroll_segments").toLowerCase()))}catch(r){}try{var q=
n.get_conversion_value();q.conv_value&&p.push("conv_value="+q.conv_value);q.currency&&p.push("adroll_currency="+q.currency)}catch(r){}try{if(n._has_email()){var k=n._global("adroll_email"),k=k.replace(/^\s+|\s+$/g,""),e=k.toLowerCase();n.is_already_hashed(e)?p.push("hashed_email="+e):n.is_email_valid(k)?p.push("hashed_email="+n.md5(e)):(p.push("data_error=email"),p.push("data_error_message=invalid_format"))}}catch(r){}try{if(n._has_user_identifier()){var h=n._global("adroll_user_identifier"),h=h.replace(/^\s\s*/,
"").replace(/\s\s*$/,"");p.push("user_identifier="+n.md5(h))}}catch(r){}try{var g=n.external_data_to_qs(!0);g&&p.push(g)}catch(r){}try{var m=window.location.href.split("#")[0];500>=m.length&&p.push("arrfrr="+window.encodeURIComponent(m))}catch(r){}p=n.get_base_url(b,a,c,null,"",p);d.src=p;n._head().appendChild(d)}}(this));this.addLoadEvent(function(a){return function(){var b=a._global("adroll");if(b&&"object"===typeof b){b.identify=function(){return a.identify.apply(a,arguments)};b.track=function(){return a.track.apply(a,
arguments)};for(var c,d,e=0;e<b.length;e++)c=b[e][0],d=b[e][1],"identify"===c?a.identify.apply(a,d):"track"===c&&a.track.apply(a,d)}}}(this))};
l.prototype.render_ad_code=function(a,c,b,d){d=this._is_defined(d)?d:null;if(!this._is_defined(this._r[c])||d){var f=["width="+this._global("adroll_width"),"height="+this._global("adroll_height"),"x=0","y=0"];if(b)this.log("Rendering test ad "+b+" in space "+c),f.push("test_ad="+b),a=this.get_url(a,c,null,"ad",f);else if(d){this.log("Rendering adgroup "+d);b=this.macro_values();var n=this.macro_url_params(b,!1,!1,!1,!1);f.push(n);this.render_win_notification(b);this.render_extra_script(b);a=this.get_url(a,
c,d,null,f)}else this.log("Rendering ad space "+c),a=this.get_url(a,c,null,"ad",f);this.expire_old();window.document.write('<script src="'+a+'">\x3c/script>');this._nad+=1;this._r[c]=1}};
l.prototype.render_win_notification=function(a){if(a.adroll_cpm_macro&&a.adroll_win_notif){var c=(this._secure()?"https://":"http://")+a.adroll_win_notif+a.adroll_cpm_macro;a.adroll_ad_payload&&(a.adroll_rtb_dict&&a.adroll_rtb_dict.waap||/waap=1&/.test(a.adroll_win_notif)&&!this._is_defined(a.adroll_rtb_dict))&&(c+="&ad_payload="+a.adroll_ad_payload);this.imgRequest(c)}};
l.prototype.render_extra_script=function(a){a.adroll_rtb_dict&&a.adroll_rtb_dict.extra_script_src&&this.add_script_element(a.adroll_rtb_dict.extra_script_src,{})};l.prototype.add_script_element=function(a,c){var b=window.document.createElement("script"),d=this._secure()?"https://":"http://";b.type="text/javascript";b.src=d+a;for(var f in c)c.hasOwnProperty(f)&&"src"!==f&&b.setAttribute(f,c[f]);this._head().appendChild(b)};
l.prototype.get_base_url=function(a,c,b,d,f,n){var p=a.split("?");a=p[0]+"/"+c+"/"+b+(d?"/"+d:"")+(f?"/"+f:"");var q="?";p[1]&&(a+="?"+p[1],q="&");var p=q+"no-cookies=1&pv=",k="";this.cookieEnabled(!1)?(k=window.escape(this.get_eids()),a+=q+"pv="+this.pv+"&cookie="+k):a+=p+this.pv;n&&(a+="&"+n.join("&"));a=this.add_tpc_to_url(a);if(a.length>this._url){this.del(this.__adc);if(a.length-k.length>this._url)return a;this.log("Url was too big, shrinking it");return this.get_url(c,b,d,f,n)}this.log("Generated url: "+
a);return a};l.prototype.get_url=function(a,c,b,d,f){var n=b?this._srv("/c"):this._srv("/r");return this.get_base_url(n,a,c,b,d,f)};l.prototype.get_eids=function(){if(this._global("adroll_ext_network")||this._global("adroll_optout"))return"";try{for(var a=this.get(this.__adc),c=a?a.split("|"):"",a=[],b=c.length-1;0<=b;b--)if(c[b]){var d=c[b].split(":");a.push([d[0],d[2]].join(":"))}return a.join("|")}catch(f){return this.del(this.__adc),""}};l.prototype.record_user=function(a){var c="adroll_conversion_value adroll_conversion_value_in_dollars adroll_segments adroll_email adroll_user_identifier adroll_currency".split(" "),b,d;a=a||{};var f={adroll_email:!0,adroll_user_identifier:!0};for(b=0;b<c.length;b++){try{this._unset_global(c[b])}catch(n){}if(c[b]in a){c[b]in f?this._set_global(c[b],window.escape(a[c[b]])):this._set_global(c[b],a[c[b]]);try{delete a[c[b]]}catch(n){}}}try{this._unset_global("adroll_custom_data")}catch(n){}for(d in a)if(a.hasOwnProperty(d)){this._set_global("adroll_custom_data",
a);break}this.render_pixel_code(this._global("adroll_adv_id"),this._global("adroll_pix_id"))};l.prototype.record_adroll_email=function(a){if(this._has_email()){var c=this._global("adroll_email"),c=c.replace(/^\s+|\s+$/g,""),b,d=c.toLowerCase();this.is_already_hashed(d)?b=d:this.is_email_valid(c)&&(b=this.md5(d));c="https://d.adroll.com/id/"+this._global("adroll_adv_id")+"/?hashed_email="+b;a&&(c+="&idsource="+a);this.imgRequest(c)}};
l.prototype._send_plain_text_identifiers=function(a,c,b){(a||c)&&b&&(b="https://d.adroll.com/id/"+this._global("adroll_adv_id")+"/?idsource="+b,a&&(a=a.replace(/^\s+|\s+$/g,"").toLowerCase(),b+="&email="+window.encodeURIComponent(a)+"&hashed_email="+this.md5(a)),c&&(b+="&user_identifier="+window.encodeURIComponent(c)),this.imgRequest(b))};l.prototype._has_email=function(){return this._has_global("adroll_email")&&"username@example.com"!==this._global("adroll_email")};
l.prototype._has_user_identifier=function(){return this._has_global("adroll_user_identifier")&&"example_user_id"!==this._global("adroll_user_identifier")};l.prototype.is_already_hashed=function(a){return/^[a-f0-9]{32}$/.test(a)};l.prototype.is_email_valid=function(a){return/[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/.test(a)};
l.prototype.identify=function(a,c){(a.email||a.userId)&&this._send_plain_text_identifiers(a.email,a.userId,c||"adroll-identify");a.email&&this._set_global("adroll_email",a.email);var b=this.copyObj(a,["email","userId"]);b&&(b="https://d.adroll.com/uat/"+this._global("adroll_adv_id")+"/"+this._global("adroll_pix_id")+"/?user_attributes="+window.encodeURIComponent(this.jsonStringify(b)),c&&(b+="&idsource="+c),this.imgRequest(b));this._queueAndCallback("identify",[a,c])};
l.prototype.track=function(a,c){if(a){var b="https://d.adroll.com/uev/"+this._global("adroll_adv_id")+"/"+this._global("adroll_pix_id")+"/?event_name="+window.encodeURIComponent(a),d=this.copyObj(c);d&&(b+="&event_attributes="+window.encodeURIComponent(this.jsonStringify(d)));this.imgRequest(b);this._queueAndCallback("track",[a,c])}};
l.prototype._registerCallback=function(a,c,b){this.callbacks=this.callbacks||{};this.callbackNames=this.callbackNames||[];this.callbacks[a]=this.callbacks[a]||[];if(!("function"!==typeof c||-1<this.callbackNames.indexOf(b))&&(this.callbackNames.push(b),this.callbacks[a].push(c),this.callbackQueues&&this.callbackQueues[a]&&this.callbackQueues[a].length))for(b=0;b<this.callbackQueues[a].length;b++)c.apply(null,this.callbackQueues[a][b])};
l.prototype._queueAndCallback=function(a,c){this.callbackQueues=this.callbackQueues||{};this.callbackQueues[a]=this.callbackQueues[a]||[];this.callbackQueues[a].push(c);if(this.callbacks&&this.callbacks[a]&&this.callbacks[a].length)for(var b=0;b<this.callbacks[a].length;b++)this.callbacks[a][b].apply(null,c)};l.prototype.registerIdentifyCallback=function(a,c){this._registerCallback("identify",a,c)};l.prototype.registerTrackCallback=function(a,c){this._registerCallback("track",a,c)};l.prototype._is_defined=function(a){return"undefined"!==typeof a};l.prototype.normalize_var=function(a,c){if(!a)return"";a=a.toString().substr(0,this._kwl).replace(/,/gi,".");c&&(a=window.escape(a));return a};l.prototype.get_keywords=function(){try{var a=window.document.referrer||"";if(!a)return"";var c=this.parseUri(a);return-1!==c.host.indexOf("www.google.")?c.queryKey.q.substring(0,this._kwl):-1!==c.host.indexOf("bing.com")?c.queryKey.q.substring(0,this._kwl):""}catch(b){return""}};
l.prototype.parseUri=function(a){a=/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*):?([^:@]*))?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/.exec(a);for(var c={queryKey:{}},b=14,d="source protocol authority userInfo user password host port relative path directory file query anchor".split(" ");b--;)c[d[b]]=a[b]||"";c[d[12]].replace(/(?:^|&)([^&=]*)=?([^&]*)/g,function(a,b,d){b&&(c.queryKey[b]=d)});return c};
l.prototype._secure=function(){return!0};l.prototype._protocol=function(){return window.document.location.protocol};l.prototype._native=function(){try{return"http"!==this._protocol().slice(0,4)}catch(a){return!0}};l.prototype._srv=function(a){a=this._is_defined(a)?a:"";return this.add_tpc_to_url("https://d.adroll.com"+a)};l.prototype._cdn=function(a){a=this._is_defined(a)?a:"";return"https://s.adroll.com"+a};l.prototype.log=function(a){this._logs.push(a)};
l.prototype.read_log=function(a){return this._logs.join(a?"\n":"<br>\n")};l.prototype.normalize_url=function(a){return a.toLowerCase()};l.prototype.imgRequest=function(a){var c=new window.Image;c.src=this.add_tpc_to_url(a);c.setAttribute("width","1");c.setAttribute("height","1");c.setAttribute("border","0");this._head().appendChild(c)};l.prototype.copyObj=function(a,c){if(!a)return null;var b={},d=0,f;for(f in a)!a.hasOwnProperty(f)||c&&-1!==c.indexOf(f)||(d++,b[f]=a[f]);return d?b:null};
l.prototype.add_tpc_to_url=function(a){var c=this._global("adroll_tpc");if(!a||!c)return a;var b=this.parseUri(a);if(b.queryKey.adroll_tpc||"d.adroll.com"!==b.host&&"d.adroll.com"!==b.host+":"+b.port)return a;var d=a.indexOf("?"),f=b="";-1!==d?(b=a.slice(0,d+1),f="&"+a.slice(d+1)):(d=a.indexOf("#",-1===d?0:d),-1===d?b=a+"?":(b=a.slice(0,d)+"?",f=a.slice(d)));return b+"adroll_tpc="+encodeURIComponent("hsts"+this.hstsVersion()+"="+c)+f};
l.prototype.load_adroll_tpc=function(a){11<=parseFloat(this.getSafariVersion())?this.check_tpc_optout(function(c){c?this._set_global("adroll_optout",!0):this.get_tpc_cookie(function(b){this._set_global("adroll_tpc",b||null);a.call(this)}.bind(this))}.bind(this)):a.call(this)};window.__adroll=window.__adroll||new l;}());
(function(a){a.adroll_optout=!1;a.adroll_a_eid="undefined"===typeof a.adroll_ad_eid?null:a.adroll_ad_eid;a.adroll_c_eid="undefined"===typeof a.adroll_c_id?null:a.adroll_c_id;a.adroll_ext_network="undefined"===typeof a.adroll_ext_network?null:a.adroll_ext_network;a.adroll_subnetwork="undefined"===typeof a.adroll_subnetwork?null:a.adroll_subnetwork;a.adroll_ad_payload="undefined"===typeof a.adroll_ad_payload?null:a.adroll_ad_payload;a.adroll_win_notif="undefined"===typeof a.adroll_win_notif?null:a.adroll_win_notif;
a.adroll_c_eid&&!a.adroll_ext_network&&(a.adroll_ext_network="g");a.__adroll.render_ad_code(a.adroll_s_id,a.adroll_a_id,a.adroll_a_eid,a.adroll_c_eid)})(window);
