/*
 Copyright (c) WideOrbit Sweden AB 2008-2017
 Version 1.85.12
*/
function admetaEval(E){return eval(E)}void 0===window.Admeta||Admeta.isFn||(window.legacyTags=Admeta.aTags,window.legacyll=Admeta.ll,Admeta=void 0);
var Admeta=Admeta||function(){function E(a){return-1!==a.indexOf("/",a.length-1)?a:a+"/"}function F(){return Math.floor(1E8*Math.random())}function da(a){var b;try{if(a)for(b=0;b<a.length;b++)if(a[b]===ea)return!0}catch(c){}return!1}function L(){return da(Ka)?!0:window.AdmetaLogging}function O(a){var b;return void 0!==window.ADM_PL&&void 0!==window.ADM_PL.pbId&&a===P&&(b=parseInt(ADM_PL.pbId),0<b)?E(G+"p"+b+"."+I):a}function fa(){function a(a){return a&&-1!==a.indexOf("admaym")}a(window.AdmetaFrontBase)&&
(window.AdmetaFrontBase=void 0);a(window.AdmetaScriptBase)&&(window.AdmetaScriptBase=void 0);M=E(window.AdmetaScriptBase||G+"s."+I);var b=-1!==M.indexOf("localhost")?"":"script/";ga=E(window.AdmetaFrontBase||P);Q=M+"IfrJSAdLoader.htm?HTML=1&cb={cb}";Admeta.base=O(ga);Admeta.textAdsJS=M+b+"TextAds.js?{sv}"}function w(){if(window.disableIframeCheck)return m.NoIframe;try{if(top.location.href&&window.self!==window.top)return m.SameDomainIframe}catch(a){return m.CrossDomainIframe}return m.NoIframe}function ha(){try{return!ia&&
"1"===localStorage.getItem("AdmetaLogger")}catch(a){}return!1}function ja(a,b){try{if(ha()){var c=new CustomEvent("AdmetaLogger",{detail:{logCode:a,data:b}});w()===m.CrossDomainIframe?document.dispatchEvent(c):top.document.dispatchEvent(c);return!0}}catch(d){}return!1}function z(a){try{ja(a,Array.prototype.slice.call(arguments,1))||0===z.toString().indexOf("function logDebug")&&console.info(arguments)}catch(b){}}function ka(a){return"http://p.admeta.se/pixel.gif?v="+Admeta.fullVersion+"&"+a+"&cb="+
F()}function A(a){if(L())try{Admeta.loadImg(ka(a))}catch(b){}}function la(a){try{Admeta.loadImg("http://p.admeta.se/error.gif?e="+encodeURIComponent(a)+"&cb="+F())}catch(b){}}function R(a,b){z(n.Undef,"Exception: ",a,b);if(L()){var c="";try{c=Admeta.fullVersion,c+=": "+a.toString()}catch(d){}try{c+=": ",c+=JSON.stringify(a.stack)}catch(d){}try{b&&(c+=": ",c+=JSON.stringify(b))}catch(d){}try{c=c.substr(0,3500)}catch(d){}la(c)}}function ma(){Admeta.focus=1}function na(){Admeta.focus=0}function S(){return(void 0===
ADM_PL.pId?escape(ADM_PL.page).replace(/%/g,"_")+ADM_PL.width+ADM_PL.height:ADM_PL.pId)+":"+(void 0===ADM_PL.rank?1:ADM_PL.rank)+":"+(16777216*(1+Math.random())|0).toString(16).substring(1)}function oa(){var a=Admeta.Text;a.forceSize=ADM_PL.textSize;a.forceCenterImg=ADM_PL.centerImages;a.forceBaseFontSize=ADM_PL.fontSize;a.forceBaseFont=ADM_PL.font;ADM_PL.TextSize=void 0;ADM_PL.CenterImages=void 0;ADM_PL.fontSize=void 0;ADM_PL.font=void 0}function pa(a){return-1!==a.indexOf("&")||-1!==a.indexOf("?")?
escape(a):a}function T(a){var b=document.cookie,c=b.indexOf(a+"=");if(-1===c)return"";c+=a.length+1;a=b.indexOf(";",c);-1===a&&(a=b.length);return decodeURIComponent(b.substring(c,a))}function La(a){var b="",c=w();(function(){function b(a){try{return a=a.replace(/^\s+|\s+$/gm,""),""===a||"$"===a.slice(0,1)||"{"===a.slice(0,1)?void 0:a}catch(c){}}a&&void 0!==a.referrer&&(a.referrer=b(a.referrer));a&&void 0!==a.referrerBackup&&(a.referrerBackup=b(a.referrerBackup))})(a);if(a&&void 0!==a.referrer)b=
a.referrer;else if(a&&void 0!==a.referrerBackup&&c===m.CrossDomainIframe)b=a.referrerBackup;else if(c===m.CrossDomainIframe)b=document.referrer;else if(c===m.SameDomainIframe)try{b=top.location.href}catch(d){}return encodeURIComponent(b)}function qa(a){var b=0,c="",d,f=!1,g;try{if(void 0!==a.wlrcmd)b=1,c=a.wlrcmd;else if(void 0!==a.adptpecresp&&""!==a.adptpecresp)b=2,c=a.adptpecresp;else if(void 0!==a.adptkwresp&&""!==a.adptkwresp)b=2,c=a.adptkwresp;else if(void 0!==a.adt_bt)b=2,c=a.adt_bt;else if(void 0!==
a.W2T_UserCategories)b=3,c=a.W2T_UserCategories.join(",");else if(void 0!==a.rsinetsegs)b=3,c=a.rsinetsegs.join(",");else if(void 0!==a.nuggprof&&""!==a.nuggprof)b=2,c=a.nuggprof;else if(void 0!==a.dep_admeta_segments&&""!==a.dep_admeta_segments)b=3,c=a.dep_admeta_segments;else if(void 0!==a.ADTOTAL_PDP||void 0!==a.ADTOTAL_PDG){var e="",h;try{void 0!==a.ADTOTAL_PDP&&(e=a.ADTOTAL_PDP.substring(0,3)+";",h=parseInt(a.ADTOTAL_PDP.substring(4,6),10),19>=h?e+="AGE1":29>=h?e+="AGE2":39>=h?e+="AGE3":49>=
h?e+="AGE4":59>=h?e+="AGE5":60<=h&&(e+="AGE6"),e+=";"),void 0!==a.ADTOTAL_PDG&&(e+=a.ADTOTAL_PDG.replace(/,/g,"="))}catch(l){}c=e;""!==c&&(b=2)}else if(void 0!==a.onet_wl&&""!==a.onet_wl)b=1,c=a.onet_wl;else if(void 0!==a.ccauds){b=2;h="";try{for(e=0;e<a.ccauds.Profile.Audiences.Audience.length;e++)0<e&&(h+=";"),h+=a.ccauds.Profile.Audiences.Audience[e].abbr}catch(l){}c=h;f=!0}window.localStorage&&void 0!==window.localStorage.kxmktadapt_segs&&""!==window.localStorage.kxmktadapt_segs&&(g=window.localStorage.kxmktadapt_segs,
f?(2===b&&(c=c.replace(/;/g,",")),c=c+","+g):c=g,b=3);0===b&&(d=T("pec_resp"),""!==d&&(b=2,c=d.replace(/,/g,";")),d=T("rsi_segs"),""!==d&&(b=3,c=d.replace(/\|/g,",")),d=T("adptseg"),""!==d&&(b=2,c=d.replace(/([\w,]+)-([\w]+)/g,"$2=$1").replace(/,/g,":").replace(/#/g,";")));if(0===b){var k,c=(k=document.cookie.match(/frosmo_keywords=([^;$]+)/))?k[1].replace(/\./g,","):"";""!==c&&(b=3)}}catch(l){}return{vitp:b,vit:c}}function C(a,b,c){for(;-1!==a.indexOf(b);)a=a.replace(b,c);return a}function ra(a){a=
C(a,"{timestamp}",(new Date).getTime());a=C(a,"{timediff}",sa);return C(a,"{random}",F())}function Ma(a){if(a){if(a.deviceId)return a.deviceId;if(a.userId)return a.userId}}function U(a,b){var c;c=b&&b.segments?{vitp:3,vit:b.segments}:void 0;if(!c&&(c=qa(window),0===c.vitp&&w()===m.SameDomainIframe))try{c=qa(window.parent)}catch(d){}return Admeta.setParams(a,[["arp",0],["jsv",Admeta.version],["tsv",Admeta.textVersion],["fl",Admeta.Flash.support()?Admeta.Flash.version():0],["url",La(b)],["fp",ta.get()],
["mpp",V],["uid",encodeURIComponent(Ma(b)||"")],["jscb",b&&void 0!==b.jsonCallback?b.jsonCallback:""],["pbId",b?b.pbId||"":""],["clk",b&&void 0!==b.clk?pa(b.clk):""],["oid",b?encodeURIComponent(b.orderid||""):""],["mraid",b?encodeURIComponent(b.mraid||""):""],["apid",b?encodeURIComponent(b.appId||""):""],["apbndl",b?encodeURIComponent(b.appBundle||""):""],["lat",b?encodeURIComponent(b.latitude||""):""],["lon",b?encodeURIComponent(b.longitude||""):""],["hb",b&&b.headerBidding?1:0],["cb",F()],["vitp",
c.vitp],["vit",escape(c.vit)]])}function ua(a){void 0===Admeta.xRenderF&&(Admeta.xRenderF={});if(ADM_PL.renderF||ADM_PL.ADM_RENDERF){var b=ADM_PL.renderF?ADM_PL.renderF:ADM_PL.ADM_RENDERF;Admeta.xRenderF[a]=b;Admeta.xRenderF[ADM_PL.pId]=b}}function W(){var a="site page width height rank referrer referrerBackup subPublisher orderid ecpm atf tagId mraid mraid nativeAd nativeLayout appId appBundle clk adserverid deviceId userId segments latitude longitude headerBidding".split(" "),b,c=window.ADM_PL;
if(c){for(b=0;b<a.length;b++)a:{var d=c,f=a[b],g=void 0;for(g in d)if(d.hasOwnProperty(g)&&g.toLowerCase()===f.toLowerCase()){d[f]=d[g];break a}}c.ATpagefilter&&(c.page="Default web page");void 0!==c.pkg&&(c.pkg=encodeURIComponent("pkg|"+decodeURIComponent(c.pkg)));c.nativeLayout&&(c.nativeAd=1)}}function va(a){Admeta.MatC.setup(ADM_PL.pId,ADM_PL.rank,-1,a,void 0,ADM_PL.refresh,(ADM_PL.fade?1:0)|(ADM_PL.attRefreshed?2:0),ADM_PL.width,ADM_PL.height,void 0,ADM_PL.brandImgUrl,ADM_PL.brandLandingUrl,
ADM_PL.brandImgHeight,ADM_PL.brandImgPos,ADM_PL.unsoldTag,ADM_PL.unsoldMethod,ADM_PL.iframedUnsold,ADM_PL.protect,ADM_PL.embed,ADM_PL.soldMethod,void 0,ADM_PL.ifrAttrs,ADM_PL.attrFn)}function wa(a,b,c,d,f){var g=!1;if(void 0!==f)return f?1:0;if(void 0===b||void 0===c||void 0===a)return 0;!document.getElementById(a)&&d&&(document.write("<div id='"+a+"'></div>"),g=!0);d=document.getElementById(a);a=Admeta.MatC.checkElemForcedAreaVisible(a,b,c);try{g&&d.parentNode&&d.parentNode.removeChild(d)}catch(e){}return a?
1001:0}function xa(a,b){return Admeta.setParams(a,[["wsName",encodeURIComponent(decodeURIComponent(b.site))],["wName",encodeURIComponent(decodeURIComponent(b.page))],["width",b.width],["height",b.height],["subp",b.subPublisher?encodeURIComponent(decodeURIComponent(b.subPublisher)):""]])}function ya(a,b,c,d){return Admeta.setParams(a,[["rank",b.rank],["pp",b.pkg||""],["ecpm",b.ecpm||""],["ntv",b.nativeAd||""],["ntl",b.nativeLayout||""],["adsid",encodeURIComponent(decodeURIComponent(b.adserverid||""))],
["rpos",d],["gid",c]])}function Na(a){function b(a){return void 0!==a.pId?a.pId+"":a.site+":"+a.page+":"+a.width+":"+a.height}function c(){var b,c=-1;for(b=0;b<a.length;b++)(-1===c||a[b].admpl.rank<c)&&!a[b].touched&&(c=a[b].admpl.rank);return c}function d(g){if(-1!==g){var e={},h;for(f=0;f<a.length;f++)if(h=b(a[f].admpl),a[f].admpl.rank===g){if(void 0===e[h])e[h]=!0;else{h=a[f].admpl;for(var k=b(a[f].admpl),l=0,p=1,r=void 0;l<a.length;)r=a[l].admpl,b(r)===k&&r.rank===p?(p++,l=0):l++;h.rank=p}a[f].touched=
!0}d(c())}}var f;d(c());return a}function J(a){for(var b;Admeta.pushedAds&&0<Admeta.pushedAds.length;){var c=void 0;b=[];var d=0;if(void 0===Admeta.pushedAds||0===Admeta.pushedAds.length)b=[];else for(c=Admeta.pushedAds[0].admpl.pbId;d<Admeta.pushedAds.length;)Admeta.pushedAds[d].admpl.pbId==c?b.push(Admeta.pushedAds.splice(d,1)[0]):(d+=1,V=1);a:{var c=a,d=[],f=void 0,g=void 0,e=void 0,h=void 0,k=void 0,l=void 0;if(void 0===b||0===b.length)A("e=processFullPageNoAds");else{b=Na(b);for(f=0;f<b.length;f++)c&&
!document.getElementById(b[f].gid)||d.push(f);window.ADM_PL=window.ADM_PL||{};oa();b.length!==d.length&&A("e=tagsNotFound&pas="+b.length+"&up="+d.length);if(0<d.length){g=Admeta.setParams(Admeta.base+"JSAdservingMP.ashx?pc={pc}&pbId={pbId}&clk={clk}&exm={exm}&jsv={jsv}&tsv={tsv}&cts={cts}&arp={arp}&fl={fl}&vitp={vitp}&vit={vit}&jscb={jscb}&url={url}&fp={fp}&oid={oid}&exr={exr}&mraid={mraid}&apid={apid}&apbndl={apbndl}&mpp={mpp}&uid={uid}&lat={lat}&lon={lon}&hb={hb}&cb={cb}",[["pc",d.length]]);l=b[d[0]].admpl;
window.ADM_PL.orderid=l.orderid||window.ADM_PL.orderid;window.ADM_PL.referrer=l.referrer||window.ADM_PL.referrer;window.ADM_PL.mraid=l.mraid||window.ADM_PL.mraid;window.ADM_PL.appId=l.appId||window.ADM_PL.appId;window.ADM_PL.appBundle=l.appBundle||window.ADM_PL.appBundle;window.ADM_PL.pbId=l.pbId||window.ADM_PL.pbId;window.ADM_PL.jsonCallback=l.jsonCallback||window.ADM_PL.jsonCallback;g=U(g,ADM_PL);for(f=0;f<d.length;f++){e=b[d[f]];l=e.admpl;k=wa(e.gid,l.width,l.height,!1,l.atf);if(void 0!==l.pId)h=
Admeta.setParams("&pId{o}={pId}&rank{o}={rank}&gid{o}={gid}&pp{o}={pp}&clk{o}={clk}&rpos{o}={rpos}&ecpm{o}={ecpm}&ntv{o}={ntv}&ntl{o}={ntl}&adsid{o}={adsid}",[["o",f]]),h=Admeta.setParams(h,[["wId",l.wId],["pId",l.pId]]);else if(void 0!==l.pbId&&void 0!==l.site&&void 0!==l.page&&void 0!==l.width&&void 0!==l.height)h=Admeta.setParams("&wsName{o}={wsName}&wName{o}={wName}&rank{o}={rank}&bfDim{o}={width}x{height}&subp{o}={subp}&gid{o}={gid}&pp{o}={pp}&clk{o}={clk}&rpos{o}={rpos}&ecpm{o}={ecpm}&ntv{o}={ntv}&ntl{o}={ntl}&adsid{o}={adsid}",
[["o",f]]),h=xa(h,l);else{A("e=invalidTagMP&admpl="+encodeURIComponent(JSON.stringify(l)));break a}h=ya(h,l,e.gid,k);h=Admeta.setParams(h,[["clk",pa(l.clk||"")]]);g+=h}z(n.ExecMultipleRequest,b,g);Admeta.inFrontCall=!0;Admeta.Script.load(g,!0,void 0,1)}}}}}function Oa(a){var b,c={};for(b in a)a.hasOwnProperty(b)&&(c[b]=a[b]);return c}function H(a){W();va(a);ua(a);void 0===Admeta.pushedAds&&(Admeta.pushedAds=[]);Admeta.pushedAds.push({gid:a,admpl:Oa(window.ADM_PL)})}function X(){var a=void 0!==window.ADM_PL.tagId?
window.ADM_PL.tagId:S();document.write('<div id="'+a+'"></div>');H(a);ADM_PL.wId=void 0;ADM_PL.pId=void 0;ADM_PL.site=void 0}function za(){ADM_PL.tagId&&"sp"===ADM_PL.tp&&document.getElementById(ADM_PL.tagId)&&(z(n.Undef,"Corrected tag sp->spt",ADM_PL.tagId),ADM_PL.tp="spt")}function Aa(){ADM_PL.async&&(ADM_PL.defLoad=ADM_PL.async);Admeta.defLoad=void 0===ADM_PL.defLoad||Admeta.defLoad?Admeta.defLoad:ADM_PL.defLoad;"sp"===ADM_PL.tp&&Admeta.defLoad&&(ADM_PL.tp="spp");za();var a;a:{var b=ADM_PL.tp;
if("sp"===b||"fp"===b||"spp"===b)try{if(document.currentScript&&document.currentScript.async){a=!1;break a}}catch(d){}a=!0}if(a){Admeta.base=O(Admeta.base);z(n.ReceiveRequest,ADM_PL);switch(ADM_PL.tp){case "sp":a:{a=S();var b=Admeta.base,c;va(a);ua(a);oa();c=wa(a,ADM_PL.width,ADM_PL.height,!0,ADM_PL.atf);if(void 0!==ADM_PL.pId)b=Admeta.setParams(b+"JSAdservingSP.ashx?wId={wId}&pId={pId}&rank={rank}&gid={gid}&clk={clk}&di=1&exm={exm}&jsv={jsv}&tsv={tsv}&cts={cts}&fl={fl}&vitp={vitp}&vit={vit}&jscb={jscb}&pp={pp}&url={url}&fp={fp}&rpos={rpos}&oid={oid}&ecpm={ecpm}&exr={exr}&ntv={ntv}&mraid={mraid}&ntl={ntl}&apid={apid}&apbndl={apbndl}&mpp={mpp}&adsid={adsid}&uid={uid}&lat={lat}&lon={lon}&hb={hb}&cb={cb}",
[["wId",ADM_PL.wId],["pId",ADM_PL.pId]]);else if(void 0!==ADM_PL.pbId&&void 0!==ADM_PL.site&&void 0!==ADM_PL.page&&void 0!==ADM_PL.width&&void 0!==ADM_PL.height)b+="JSAdservingSP.ashx?pbId={pbId}&wsName={wsName}&wName={wName}&rank={rank}&bfDim={width}x{height}&subp={subp}&gid={gid}&clk={clk}&di=1&exm={exm}&jsv={jsv}&tsv={tsv}&cts={cts}&fl={fl}&vitp={vitp}&vit={vit}&jscb={jscb}&pp={pp}&url={url}&fp={fp}&rpos={rpos}&oid={oid}&ecpm={ecpm}&exr={exr}&ntv={ntv}&mraid={mraid}&ntl={ntl}&apid={apid}&apbndl={apbndl}&mpp={mpp}&adsid={adsid}&uid={uid}&lat={lat}&lon={lon}&hb={hb}&cb={cb}",
b=xa(b,ADM_PL);else{A("e=invalidTagSP&admpl="+encodeURIComponent(JSON.stringify(ADM_PL)));break a}b=ya(b,ADM_PL,a,c);b=U(b,ADM_PL);z(n.ExecSingleRequest,{gid:a},ADM_PL,b);ADM_PL.wId=void 0;ADM_PL.pId=void 0;ADM_PL.site=void 0;ADM_PL.defLoad=void 0;Admeta.inFrontCall=!0;Admeta.Script.load(b,!1,void 0,1)}break;case "fp":X();break;case "fpt":H(ADM_PL.tagId);ADM_PL.wId=void 0;ADM_PL.pId=void 0;ADM_PL.site=void 0;break;case "fpc":J(!0);break;case "spt":H(ADM_PL.tagId);J(!0);break;case "spp":X();J(!0);
break;default:la("Unrecognized ADM_PL.tp: "+ADM_PL.tp)}window.ADM_PL=void 0}else z(n.Undef,"Test write failed!",ADM_PL)}function Y(a,b){return Admeta.setParams(a,[["id",b.innerId],["width",b.w],["height",b.h]])}function Ba(a){a&&a.RF&&Admeta.Refresh.attMaterial(a);if(void 0!==a.soldMethod){var b=a.soldMethod,b=Y(b,a);a=Admeta.setParams(b,[["adid",a.adId]]);admetaEval(a)}}function Ca(a,b){for(var c=a.length;c--;)if(a[c]===b)return!0;return!1}function Da(a){try{if(a.contentDocument)return a.contentDocument;
if(a.contentWindow)return a.contentWindow.document;if(window.frames[a.name])return window.frames[a.name].document}catch(b){}}function Ea(a,b,c,d,f){b||(b=0);a.SIV=b;a.w=void 0!==d?d:a.w;a.h=void 0!==f?f:a.h;a.visitorState=c;Admeta.SIV.setup(a)}function Z(a,b){var c=document.getElementById(a),d=Admeta.getBrowser(),f=d[0],g=d[1],e,h,k;k=function(a){(e=Da(c))?(h="msie"===f&&8>=g||"opera"===f,e.open(),h&&1===a&&e.close(),e.write(Admeta.embedIfrCode(b)),h||e.close()):A("e=SameDomainIframeFail")};if(Admeta.isVisible(c)||
"complete"===document.readyState||"complete"===c.readyState)k(1);else switch(f){case "chrome":case "safari":c.onload=function(){c.onload=void 0;k()};break;case "msie":if(8>=g){c.attachEvent("onload",function p(){c.detachEvent("onload",p);k()});break}default:c.onload=k}}function Fa(a,b){var c,d=w(),f,g;try{if(a.highlight){c=document.getElementById(a.innerId);f="("+a.w+"x"+a.h+") pId: "+a.pid+(b?" unsold":" adId: "+a.adId)+" gid: '"+a.innerId+"'"+(d===m.SameDomainIframe?" Iframe same domain":d===m.CrossDomainIframe?
"Iframe cross domain":"");c.style.border="dashed 2px red";c.style.position="relative";var e=document.createElement("div");e.style.position="absolute";e.style.backgroundColor="#FFF";e.style.color="#000";e.style.left=0;e.style.top=0;e.style.font="14px Arial";e.style.textAlign="left";e.style.borderBottom="solid 1px red";e.style.padding="5px";e.style.zIndex=2147483647;e.innerHTML=f;c.appendChild(e)}g=d===m.SameDomainIframe?window.frameElement.id:a.innerId;ja(n.AdPosition,{pInfo:a,targetId:g,unsold:b,
ifrType:d})}catch(h){console.info(h)}}function aa(a){function b(){f+=1;10<f||setTimeout(function(){c.offsetWidth>2*a.adChoicesWidth?d.style.display="":b()},1E3)}var c,d,f=0;if(void 0!==a.adChoicesIdCollapsed&&(c=document.getElementById(a.innerId))&&(d=document.getElementById(a.adChoicesIdCollapsed))){try{if(c.parentNode.hasAttribute&&c.parentNode.hasAttribute("data-am")||void 0!==c.parentNode.attributes("data-am")){d.style.display="none";return}}catch(g){}c.offsetWidth<=2*a.adChoicesWidth&&(d.style.display=
"none");b()}}function ba(a,b){var c;var d=Admeta.MatC.getExisting(a.gid),f=a.sImg,g=a.sImgUrl,e=a.imgH;c=a.sPos;d&&void 0!==d.sImg&&(f=0===d.sImg?void 0:d.sImg,g=d.sImgUrl,e=d.imgH||0,c=d.sPos);void 0===f?c=void 0:(d="right:0px;bottom:0px",1===c&&(d="left:0px;bottom:0px"),2===c&&(d="left:0px;top:0px"),3===c&&(d="right:0px;top:0px"),c={h:e,pad:2<=c?"padding-top:"+e:"",html:"<a style='position:absolute;"+d+";z-index:100;border:0;padding:0;margin:0;width:auto;font-size:0' href='"+g+"' target='_blank' rel='nofollow'><img style='border:0;margin:0;padding:0' src='"+
f+"'></img></a>"});f=Admeta.AdChoices.getCode(a);e=g="";if(!(a.SIV||a.RF||a.embed||c)&&""===f)return b;(a.RF||a.SIV)&&a.gid===a.innerId&&Admeta.MatC.setInnerId(a);c&&(g=c.pad,e=c.html);c=a.innerId;null!==document.getElementById(a.innerId)&&(c+="_mbd");return b=a.embed?"<div data-am id='"+c+"' style='position:relative;width:"+a.w+"px;height:"+a.h+"px'>"+f+b+e+"</div>":"<fieldset data-am id='"+c+"' style='position:relative;display:inline;border:0;margin:0;padding:0;"+g+"'>"+f+b+e+"</fieldset>"}function K(a,
b,c,d,f,g,e){var h=Admeta.debug?"border: solid 2px"+(c?" red":" green"):"border-style:none;";a="<iframe data-am"+(void 0!==b||c?" name='"+(c?"ADM:"+escape(c):a)+"'":"")+" id='"+a+"' scrolling='no' frameborder='0' marginwidth=0 marginheight=0 hidefocus='true' style='margin:0px;width:"+d+"px;height:"+f+"px;"+h+"' src='about:blank'"+(void 0!==g?" mId='"+g+"'":"");var k;b="";if(e){for(k in e)e.hasOwnProperty(k)&&(b+=" "+k+'="'+e[k]+'"');e=b}else e="";return a+e+"></iframe>"}function Ga(a,b,c){var d=Admeta.MatC.getExisting(a);
void 0===d&&(d=Admeta.MatC.setup(1,1,-1,a,0,0,0,b,c,0,void 0,void 0,0,0,void 0,void 0,0,0,0,void 0),d.incomplete=1);return d}function N(a,b){var c=(""+b).split(","),d;for(d=0;d<c.length;d++)Ca(a,c[d])||a.push(c[d])}function Ha(a,b){if(void 0!==b){var c=(""+b).split(","),d;for(d=0;d<c.length;d++)Ca(a,c[d])||a.push(c[d])}}function Ia(a){var b,c,d,f,g,e,h="",k,l,p;try{b=a.pbId||"",c=a.pId||"",d=a.site||"",f=a.page||"",g=a.width||"",e=a.height||"",k=a.tp||"",l=w(),p=JSON.stringify(a),h="&pbId="+encodeURIComponent(b)+
"&pId="+encodeURIComponent(c)+"&site="+encodeURIComponent(d)+"&page="+encodeURIComponent(f)+"&w="+encodeURIComponent(g)+"&h="+encodeURIComponent(e)+"&tp="+encodeURIComponent(k)+"&ifr="+l+"&admpl="+encodeURIComponent(p)}catch(r){}return h}var I="atemda.com",G=window.AdmetaProtocol||"//",P=E(G+I),M,ga,Q,Ja=!1,ta,m={NoIframe:0,SameDomainIframe:1,CrossDomainIframe:2},n={Undef:0,ReceiveRequest:1,ReceiveRequestInFriendlyIframe:2,ExecSingleRequest:3,ExecMultipleRequest:4,WritingMaterial:5,InsertMaterial:6,
Unsold:7,AdPosition:8},ea,Ka=[],Pa=[235,251],sa=0,V=0,ia=!1;ta=function(){var a;return{get:function(){if(void 0!==a)return a;try{return a="0;"+screen.width.toString(16)+";"+screen.height.toString(16)+";"+screen.colorDepth.toString(16)}catch(b){}return""}}}();return{isFn:!0,aTags:window.legacyTags,ll:window.legacyll,version:"1.85",fullVersion:"1.85.12",textVersion:"2.26",focus:1,protect:!1,debug:!1,setTest:function(a){I=a;Admeta.base=P=E(G+I);V=!1;ia=!0},init:function(a,b,c){sa=(new Date).getTime()-
c;A("e=admetaInit");this.protect=void 0===b?this.protect:b;Ja||(this.SIV.init(a),window.addEventListener?(window.addEventListener("focus",ma,!1),window.addEventListener("blur",na,!1)):window.attachEvent&&(window.attachEvent("onfocus",ma),window.attachEvent("onblur",na)),Ja=!0)},loadImg:function(a){Admeta.imgLoad=Admeta.imgLoad||[];var b=new Image(0,0);b.src=a;Admeta.imgLoad.push(b)},embedInFieldSet:function(a,b,c,d,f){return"<fieldset id='"+a+"' style='display:inline;border:0;margin:0;overflow:hidden;padding:0;"+
d+(b?"width:"+b+"px;":"")+(c?"height:"+c+"px;":"")+"position:relative;'>"+f+"</fieldset>"},isVisible:function(a){do{if(!a||"none"===a.style.display)return!1;a=a.parentNode}while(a&&"BODY"!==a.tagName);return!0},iframedCode:function(a,b,c,d,f){-1!==b.search(/<script/i)||f?(f=document.createElement("iframe"),f.width=c,f.height=d,f.scrolling="no",f.frameBorder=0,f.hideFocus=0,f.style.borderStyle="none",f.style.margin=0,document.getElementById(a).appendChild(f),a=Da(f),a.open(),a.write(this.embedIfrCode(b)),
a.close()):document.getElementById(a).innerHTML=b},loadAdsJSON:function(a,b,c){for(var d,f=window.ADM_PL,g;0<b.length;)window.ADM_PL=b.pop(),W(),d=void 0!==window.ADM_PL.tagId?window.ADM_PL.tagId:S(),void 0!==window.ADM_PL.pbId&&(g=window.ADM_PL.pbId),H(d);window.ADM_PL={jsonCallback:a,headerBidding:c,pbId:g,defLoad:!0};fa();J(!1);window.ADM_PL=f},headerBidding:function(a,b){this.loadAdsJSON(a,b,!0)},storeJSONMaterials:function(a){var b;for(b=0;b<a.Ids.length;b++)this.storeMaterial(a.Ids[b])},processATags:function(a){if(a&&
0!==a.length){for(var b=window.ADM_PL,c=this.defLoad;0<a.length;)window.ADM_PL=a.pop(),ADM_PL===b&&(b=void 0),H(ADM_PL.tagId);window.ADM_PL={tp:"fpc",async:!0};Aa();this.defLoad=c;window.ADM_PL=b}},processAsync:function(){this.inFrontCall||(window._Admeta&&this.processATags(window._Admeta.aTags),this.processATags(this.aTags))},logCall:function(){L()&&A("e=AdmetaJsLoaded"+Ia(ADM_PL))},processImpressions:function(){W();try{window.ADM_PL.pbId&&(ea=window.ADM_PL.pbId)}catch(c){}var a=window.ADM_PL;try{if(this.logCall(),
fa(),this.Dispatcher.init(),this.Dispatcher.delayImpression())A("e=delayImpression"+Ia(ADM_PL));else{try{void 0!==top.Admeta.adsServed&&(this.adsServed=top.Admeta.adsServed,this.rtbAdvertisersServed=top.Admeta.rtbAdvertisersServed)}catch(c){}var b=this.loadList||this.ll;if(b){for(;0<b.length;)b.pop()();this.ll?this.ll=[]:this.loadList=[]}this.processAsync();window.ADM_PL&&Aa()}}catch(c){R(c,a)}},outputMaterial:function(a,b,c,d,f,g){b.attrFn&&"function"==typeof b.attrFn&&b.attrFn(b,{rtb:"-1"!==b.rtbAdvertiserIds});
var e=this.getBrowser(),h,e=(b.embed||!1)&&g&&"msie"===e[0]&&9>=e[1],e=(g=b.protect||d||1!==a&&g||e||b.ifrAttrs)&&(b.protect||void 0===c);L()&&(c="<img src='"+ka("e=markupPixel&mat="+encodeURIComponent(JSON.stringify(b)))+"'></img>\n"+c);g?(h="AMIfr_"+b.pid+"_"+b.o+"_"+b.adId+"_"+Admeta.MatC.generateId(),d=K(h,h,e?c:void 0,b.w,b.h,b.adId,b.ifrAttrs)):d=c;d=ba(b,d);z(1===a?n.WritingMaterial:n.InsertMaterial,b,c);if(1===a)document.write(d);else{a:if(a=document.getElementById(b.innerId),!a){if(void 0!==
b.gid&&(a=document.getElementById(b.gid)))break a;a=document.getElementById("Admeta"+b.pid+"_"+b.o)}if(!a)throw"Element '"+b.innerId+(b.gid!==b.innerId?"' or '"+b.gid:"")+"' not found.";a.innerHTML=d}g&&(e?(c=void 0===f?Q:f,document.getElementById(h).src=c.replace("{cb}",F())):Z(h,c));Fa(b,!1);Ba(b);aa(b);return h},insertMaterial:function(a,b,c){this.outputMaterial(0,a,b,c||!1,void 0,!1)},writeMaterial:function(a,b,c){this.outputMaterial(1,a,b,c||!1,void 0,!1)},customRendered:function(a){Ba(a)},setParams:function(a,
b){var c;for(c=0;c<b.length;c++){var d=b[c][1],f=new RegExp("{"+b[c][0]+"}","g");!0===d&&(d=1);!1===d&&(d=0);a=a.replace(f,d)}return a},storeMaterial:function(a){void 0===this.adsServed&&(this.adsServed=[]);N(this.adsServed,a);try{w()===m.SameDomainIframe&&(top.Admeta=top.Admeta||{},top.Admeta.adsServed=top.Admeta.adsServed||[],N(top.Admeta.adsServed,a))}catch(b){}},storeRtbAdvertiser:function(a){void 0===this.rtbAdvertisersServed&&(this.rtbAdvertisersServed=[]);Ha(this.rtbAdvertisersServed,a);try{w()===
m.SameDomainIframe&&Ha(top.Admeta.rtbAdvertisersServed,a)}catch(b){}},setupMaterial:function(a,b,c,d,f,g,e,h,k,l,p,r,y,t,B,v){this.storeMaterial(c);this.storeRtbAdvertiser(v);a=this.MatC.setup(a,b,c,d,f,g,e,h,k,t,l,p,r,y,void 0,void 0,void 0,B,void 0,void 0,v);this.SIV.setup(a);this.Refresh.setup(a);return a},versionFile:function(a,b){return this.setParams(a,[["sv",b]])},loadScript:function(a,b,c,d){var f=void 0===b?0:b,g;b=a;g="http:/"===b.slice(0,6)||"https:/"===b.slice(0,7)||"//"===b.slice(0,2);
a=ra(a);b=g&&0===c?"<script type='text/javascript' src='"+a+"'>\x3c/script>":g&&1===c?"<img src='"+a+"' width='0px' height='0px'></img>":a;d?(c=f?1:0,a=Admeta.MatC.generateId(),b=K(a,a,b,0,0,void 0),1===c?document.write(b):document.body&&(c=document.createElement("div"),c.innerHTML=b,document.body.appendChild(c)),b=Q,document.getElementById(a).src=b.replace("{cb}",F())):g&&0===c&&!f?this.Script.loadInTag(a,void 0,!0):g&&1===c?this.loadImg(a):f?document.write(b):document.body&&(c=Admeta.MatC.generateId(),
d=K(c,void 0,void 0,1,1,0),a=document.createElement("div"),a.innerHTML=d,document.body.appendChild(a),Z(c,b))},callUserScript:function(a,b,c){this.loadScript(a,b,1,c)},userMatch:function(a,b,c){switch(b){case "redirect":this.loadImg(a);break;case "js":this.Script.loadInTag(a);break;case "iframe":b=document.createElement("iframe"),b.src=a,b.setAttribute("width",0),b.setAttribute("height",0),b.setAttribute("style","display:none"),a=document.getElementById(c),a.parentNode.insertBefore(b,a)}},getBrowser:function(){try{var a,
b,c=[{c:"firefox"},{c:"chrome",nc:["chromium","edge"]},{c:"safari",nc:["chrome"]},{c:"opera"},{c:"msie"},{c:"edge"}],d,f,g={"microsoft internet explorer":"msie"};for(d=0;d<c.length;d++)if(f=new RegExp("("+c[d].c+")[/ ]?s*(\\.?\\d+(\\.\\d+)*)","i"),b=navigator.userAgent.match(f)){if(c[d].nc&&(f=new RegExp("("+c[d].nc.join("|")+")","i"),navigator.userAgent.match(f)))continue;break}b&&null!==(a=navigator.userAgent.match(/version\/([\.\d]+)/i))&&(b[2]=a[1]);b=b?[b[1].toLowerCase(),b[2]]:[navigator.appName.toLowerCase(),
navigator.appVersion,"-?"];g[b[0]]&&(b[0]=g[b[0]]);b[1]=parseFloat(b[1].match(/[\d]+[\.]*[\d]*/));return b}catch(e){return["",0]}},noAdAvailable:function(a,b,c,d,f,g){a=Ga(a,f,g);var e;A("e=unsoldPixel");if(1!==a.incomplete&&(Ea(a,c,d,f,g),a.unsoldTag?e=a.unsoldTag:c&&!document.getElementById(a.innerId)&&(e="<div style='display:inline;width:0px;height:0px;margin:0;padding:0' id='"+a.innerId+"'></div>"),e&&(e=Y(e,a),b?(document.write(ba(a,e)),aa(a)):this.iframedCode(a.innerId,e,a.w,a.h,a.iframedUnsold)),
this.Refresh.lastAdAvailable(a),Admeta.Dispatcher.signalDone(),a.unsoldMethod))try{admetaEval(Y(a.unsoldMethod,a))}catch(h){}},unsold:function(a,b,c,d,f,g,e,h,k){z(n.Unsold,arguments);var l=Ga(a,h,k),p;l.unsoldTag||l.unsoldMethod||(Ea(l,g,e,h,k),void 0===f?b=unescape(b):(d=Admeta.MatC.generateId(),b=K(d,d,void 0,h,k,void 0)),c?(document.write(ba(l,b)),aa(l)):f?document.getElementById(l.innerId).innerHTML=b:(d=Admeta.MatC.generateId(),p=K(d,d,void 0,h,k,void 0),document.getElementById(l.innerId).innerHTML=
p,Z(d,b)),f&&(document.getElementById(d).src=f),Fa(l,!0))},embedIfrCode:function(a){return"<!DOCTYPE html><html><body style='margin:0px;padding:0px;'>"+a+"</body></html>"},Refresh:function(){function a(a){var b="Admeta.Refresh.tmHandler('"+a.gid+"')",c=a.timerStarted?1E3*a.RF:a.pollTimeOut;a.pollTimeOut=1E3;setTimeout(b,c)}function b(a,b){a.onmouseover=function(){var a=Admeta.MatC.getExisting(b);a&&(a.active=1)};a.onmouseout=function(){var a=Admeta.MatC.getExisting(b);a&&(a.active=0)}}function c(a){if(a.adsQueue.length>=
a.maxAds){if(0<a.maxAds)switch(a.qPos=++a.qPos%a.maxAds,a=a.adsQueue[a.qPos],a.type){case "text":var b=Admeta.Text,c;b.init.apply(b,a.init);for(c=0;c<a.ads.length;c++)b.create.apply(b,a.ads[c]);b.insert.apply(b,a.insert);break;case "image":Admeta.Image.insert.apply(Admeta.Image,a.ad);break;case "flash":Admeta.Flash.insert.apply(Admeta.Flash,a.ad);break;case "html":Admeta.JS.insert.apply(Admeta.JS,a.ad);break;case "dhtml":Admeta.JS.insertC.apply(Admeta.JS,a.ad)}}else window.ADM_PL=void 0,b=Admeta.setParams(Admeta.base+
"JSAdservingMP.ashx?pc={pc}&pbId={pbId}&clk={clk}&exm={exm}&jsv={jsv}&tsv={tsv}&cts={cts}&arp={arp}&fl={fl}&vitp={vitp}&vit={vit}&jscb={jscb}&url={url}&fp={fp}&oid={oid}&exr={exr}&mraid={mraid}&apid={apid}&apbndl={apbndl}&mpp={mpp}&uid={uid}&lat={lat}&lon={lon}&hb={hb}&cb={cb}",[["pc",1],["arp",a.arp]]),b=U(b,void 0),b+=Admeta.setParams("&pId{o}={pId}&rank{o}={rank}&gid{o}={gid}&pp{o}={pp}&clk{o}={clk}&rpos{o}={rpos}&ecpm{o}={ecpm}&ntv{o}={ntv}&ntl{o}={ntl}&adsid{o}={adsid}",[["o",0],["pId",a.pid],
["rank",a.o],["clk",a.clk||""],["gid",a.gid]]),Admeta.Script.load(b,!0,a.innerId+"_scr",1)}return{maxAds:2,setup:function(b){if(b)return b.RF&&0<b.RF&&a(b),b},attMaterial:function(a){b(document.getElementById(a.innerId),a.gid);a.arp++},lastAdAvailable:function(a){a.RF&&0!==a.RF&&(a.maxAds=a.adsQueue.length,c(a))},tmHandler:function(b){b=Admeta.MatC.getExisting(b);if(Admeta.focus&&!b.active&&Admeta.MatC.checkElemVisible(b.innerId)){if(b.timerStarted){c(b);return}b.timerStarted=!0}a(b)}}}(),Flash:function(){function a(a,
c,d,f,g,e,h,k,l){Admeta.Flash.support()?(f=g+"="+e,h&&(f+="&trackingcode="+escape(h)),k&&(f+="&retargetingtags="+escape(k)),h='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="'+G+'download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" id="vfmov" width="'+c+'" height="'+d+'" align="middle" mId="'+l+'">\n',h=h+'<param name="allowScriptAccess" value="always">\n'+('<param name="movie" value="'+a+"?"+f+'">\n'),h+='<param name="quality" value="high">\n',h+=
'<param name="wmode" value="opaque">\n',h+='<embed src="'+a+"?"+f+'" width="'+c+'" height="'+d+'" quality=high name="vfmov" align="middle" allowScriptAccess="always" type="application/x-shockwave-flash" pluginspage="'+G+'www.macromedia.com/go/getflashplayer" wmode="opaque" outline="none"></embed>\n',h+="</object>"):(f.match("pixel\\.gif$")&&(c=d="1px"),h='<a href="'+unescape(e)+'" target="_blank" rel="nofollow"><img src="'+f+'" width="'+c+'" height="'+d+'" border="0"></a>');return h}return{insert:function(b,
c,d,f,g,e,h,k,l,p,r,y,t,B,v,m,u,x,ca,n,w){Admeta.MatC.addFlash(r,arguments);var z=Admeta.setupMaterial(b,c,d,r,p,y,t,g,e,B,v,m,u,n,w,-1),q=a(f,g,e,h,k,l,x,ca,d);Admeta.insertMaterial(z,q)},write:function(b,c,d,f,g,e,h,k,l,p,r,y,t,B,v,m,u,x,ca,n,w){Admeta.MatC.addFlash(r,arguments);var z=Admeta.setupMaterial(b,c,d,r,p,y,t,g,e,B,v,m,u,n,w,-1);Admeta.writeMaterial(z,a(f,g,e,h,k,l,x,ca,d))},version:function(){var a=navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]?navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin:
0,c,d,f=Admeta.getBrowser(),g=0;try{if(a)for(c=navigator.plugins["Shockwave Flash"].description.split(" "),d=0;d<c.length;++d){if(!isNaN(parseInt(c[d],10)))return c[d]}else if("msie"===f[0])for(d=5;50>d;){try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+d)}catch(e){return g}g=d;d++}}catch(e){}return 0},support:function(){try{var a=Admeta.getBrowser();return"chrome"===a[0]&&45<=a[1]?!1:5<Admeta.Flash.version()}catch(c){}return!1}}}(),Image:function(){function a(a,c,d,f,g,e,h){return'<a href="'+
f+'" target="_blank" rel="nofollow"><img id="AM'+g+"_"+e+'" src="'+a+'" width="'+c+'" height="'+d+'" border="0" mId="'+h+'"></a>'}return{insert:function(b,c,d,f,g,e,h,k,l,p,r,y,t,B,v,m,u,x){Admeta.MatC.addImage(l,arguments);var n=Admeta.setupMaterial(b,c,d,l,k,p,r,g,e,y,t,B,v,m,u,x);Admeta.insertMaterial(n,a(f,g,e,h,b,c,d))},write:function(b,c,d,f,g,e,h,k,l,p,r,y,t,B,v,m,u,x){Admeta.MatC.addImage(l,arguments);var n=Admeta.setupMaterial(b,c,d,l,k,p,r,g,e,y,t,B,v,m,u,x);Admeta.writeMaterial(n,a(f,g,
e,h,b,c,d))}}}(),JS:function(){function a(a,c){a=unescape(a);a=C(a,"{clickthrough0}",unescape(c));a=C(a,"{clickthrough1}",c);a=C(a,"{clickthrough2}",escape(c));a=C(a,"{clickthrough}",unescape(c));return a=ra(a)}return{insert:function(a,c,d,f,g,e,h,k,l,p,r,y,t,B,v,m){var u=f,x=arguments,n=Admeta.setupMaterial(a,c,d,k,h,l,p,g,e,r,y,t,B,v,m);Admeta.MatC.addHTML(n.gid,x);Admeta.outputMaterial(0,n,void 0,!0,u,!1)},write:function(a,c,d,f,g,e,h,k,l,p,r,y,t,m,v,n){var u=f,x=arguments,w=Admeta.setupMaterial(a,
c,d,k,h,l,p,g,e,r,y,t,m,v,n);Admeta.MatC.addHTML(w.gid,x);Admeta.outputMaterial(1,w,void 0,!0,u,!1)},insertC:function(b,c,d,f,g,e,h,k,l,p,r,y,t,m){var v=f,n=g,u=arguments,x=Admeta.setupMaterial(b,c,d,l,k,0,0,e,h,void 0,void 0,void 0,void 0,y,t,m);Admeta.MatC.addDHTML(x.gid,u);v=a(v,n);Admeta.outputMaterial(0,x,v,!0,void 0,!0)},writeC:function(b,c,d,f,g,e,h,k,l,p,r,y,t,m){var v=f,n=g,u=arguments,x=Admeta.setupMaterial(b,c,d,l,k,0,0,e,h,void 0,void 0,void 0,void 0,y,t,m);Admeta.MatC.addDHTML(x.gid,
u);v=a(v,n);Admeta.outputMaterial(1,x,v,!1,void 0,!0)}}}(),MatC:function(){return{pList:[],setup:function(a,b,c,d,f,g,e,h,k,l,p,r,y,t,m,n,w,u,x,z,A,E,F){var q=Admeta.MatC.getExisting(d),C=!1;if(ha()){x=!0;var D;a:{try{D="1"===localStorage.getItem("AdmetaShowAdLocations");break a}catch(G){}D=!1}D&&(C=!0)}q?(u=!0===u||1===u?u:q.protect||u,q.adId=c,q.SIV=f,void 0!==g&&void 0===q.RF&&(q.RF=g),void 0!==e&&void 0===q.RF&&(q.eff=e),q.w=h,q.h=k,q.timerStarted=!1,q.pollTimeOut=1,q.pid=a,q.o=b,q.visitorState=
l,q.sImg=void 0!==p?p:q.sImg,q.sImgUrl=void 0!==r?r:q.sImgUrl,q.sImgH=void 0!==y?y:q.sImgH,q.sPos=void 0!==t?t:q.sPos,q.protect=u,void 0!==x&&(q.embed=x),q.rtbAdvertiserIds=A):(D=u=void 0!==u?u:Admeta.protect,D=!0===D||1===D?D:Admeta.protect||D,q={pid:a,o:b,gid:d,adId:c,visibilityState:0,innerId:d,SIV:f,RF:g,active:0,eff:e,w:h,h:k,arp:0,sImg:p,sImgUrl:r,sImgH:y,sPos:t?t:0,unsoldTag:m,unsoldMethod:n,soldMethod:z,iframedUnsold:w,visitorState:l,protect:D,embed:x,timerStarted:!1,pollTimeOut:1,rtbAdvertiserIds:A,
ifrAttrs:E,attrFn:F,adsQueue:[]},q.maxAds=Admeta.Refresh.maxAds,q.qPos=-1,Admeta.MatC.pList[Admeta.MatC.pList.length]=q);q.highlight=C;return q},full:function(a){return a?a.adsQueue.length>=Admeta.Refresh.maxAds:!0},addTextInit:function(a,b){var c=this.getExisting(a);c.adsQueue[c.adsQueue.length]={type:"text",init:b,ads:[]}},addTextAd:function(a,b){var c=this.getExisting(a),c=c.adsQueue[c.adsQueue.length-1].ads;c[c.length]=b},addTextInsert:function(a,b){var c=this.getExisting(a);c.adsQueue[c.adsQueue.length-
1].insert=b},addImage:function(a,b){this.addAd("image",a,b)},addFlash:function(a,b){this.addAd("flash",a,b)},addHTML:function(a,b){this.addAd("html",a,b)},addDHTML:function(a,b){this.addAd("dhtml",a,b)},addAd:function(a,b,c){b=this.getExisting(b);this.full(b)||(b.adsQueue[b.adsQueue.length]={type:a,ad:c})},getExisting:function(a){var b,c;for(b=0;b<this.pList.length;b++)if(c=this.pList[b],c.gid===a)return c},generateId:function(){return(16777216*(1+Math.random())|0).toString(16).substring(1)},setInnerId:function(a){var b=
a.gid;a.innerId=(b&&2<b.length&&"AM"===b.substr(0,2)?b:"AM_"+this.generateId())+"_SIV"},getBoundingRect:function(a){var b=0,c=0,d=document.documentElement.scrollTop||document.body.scrollTop,f=document.documentElement.scrollLeft||document.body.scrollLeft,g=a.offsetWidth,e=a.offsetHeight;if("function"===typeof a.getBoundingClientRect)return a=a.getBoundingClientRect(),{top:a.top,right:a.right,bottom:a.bottom,left:a.left};if(a.offsetParent){do{var h;try{h=!a.offsetParent||a.currentStyle&&"relative"===
a.currentStyle||window.getComputedStyle&&"relative"===document.defaultView.getComputedStyle(a,null).getPropertyValue("position")?!0:!1}catch(k){h=!0}if(h)break;b+=a.offsetTop;c+=a.offsetLeft;a=a.offsetParent}while(a)}c-=f;b-=d;return{top:b,right:c+g,bottom:b+e,left:c}},checkAreaVisible:function(a){if(w()===m.CrossDomainIframe)return!1;try{var b=-1!==navigator.userAgent.indexOf("Opera"),c="CSS1Compat"===document.compatMode,d=window.disableIframeCheck?self:top.self,f=window.disableIframeCheck?document:
top.document,g=b?d.innerHeight:c?f.documentElement.clientHeight:f.body.clientHeight,e=b?d.innerWidth:c?f.documentElement.clientWidth:f.body.clientWidth,h=a.right-a.left,k=a.bottom-a.top;a.right>e&&(h-=a.right-e);0>a.left&&(h+=a.left);a.bottom>g&&(k-=a.bottom-g);0>a.top&&(k+=a.top);0>h&&(h=0);0>k&&(k=0);return.5<h*k/((a.right-a.left)*(a.bottom-a.top))}catch(l){}return!1},checkElemVisible:function(a,b,c){var d,f;switch(w()){case m.CrossDomainIframe:return!1;case m.SameDomainIframe:try{d=window.frameElement}catch(g){}break;
default:d=document.getElementById(a)}if(!d)return!1;try{return f=this.getBoundingRect(d),void 0!==b&&void 0!==c&&(f.right=f.left+b,f.bottom=f.top+c),this.checkAreaVisible(f)}catch(g){return!1}},checkElemForcedAreaVisible:function(a,b,c){return this.checkElemVisible(a,b,c)}}}(),SIV:function(){function a(){var a="",b=[],c=0,d,f=Admeta.MatC,g,m=!1;for(d=0;d<f.pList.length;d++)g=f.pList[d],g.visibilityTimer&&(m=!0),g.visibilityState===h.VisiblePastThreshold&&(g.visibilityState=h.VisibilityReported,"string"===
typeof g.visitorState?b.push(g.visitorState):b=b.concat(g.visitorState));m||(clearInterval(k),k=void 0);if(0!==b.length){for(d=0;d<b.length;d++)a+="&ad2vps"+c+"="+b[d],c++;Admeta.loadImg(e+("?mc="+c+a)+"&rnd="+F())}}function b(){function b(a){a.visibilityTimer=setTimeout(function(){Admeta.MatC.checkElemForcedAreaVisible(a.innerId,a.w,a.h)&&(a.visibilityState=h.VisiblePastThreshold);a.visibilityTimer=void 0},1E3)}var c=Admeta.MatC,d,e;if(!f){f=!0;for(d=0;d<c.pList.length;d++)(e=c.pList[d])&&e.SIV&&
e.visibilityState!==h.VisibilityReported&&(c.checkElemForcedAreaVisible(e.innerId,e.w,e.h)?e.visibilityState===h.Hidden&&(e.visibilityState=h.Visible,b(e),k||(k=setInterval(a,1500))):(e.visibilityState=h.Hidden,e.visibilityTimer&&(clearTimeout(e.visibilityTimer),e.visibilityTimer=void 0)));f=!1}}function c(){d||(d=!0,Admeta.SIV.parentOnLoad=window.onload||function(){},Admeta.SIV.parentOnScroll=window.onscroll||function(){},Admeta.SIV.parentOnResize=window.onresize||function(){},window.addEventListener?
(window.addEventListener("load",b,!1),window.addEventListener("scroll",b,!1),window.addEventListener("resize",b,!1)):window.attachEvent?(document.attachEvent("onreadystatechange",function p(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",p),g=!0,b())}),document.documentElement.doScroll&&void 0===window.frameElement&&function r(){if(!g){try{document.documentElement.doScroll("left")}catch(a){setTimeout(r,0);return}g=!0;b()}}(),window.attachEvent("onscroll",b),window.attachEvent("onresize",
b)):(window.onload=function(){Admeta.SIV.parentOnLoad();b()},window.onscroll=function(){Admeta.SIV.parentOnScroll();b()},window.onresize=function(){Admeta.SIV.parentOnResize();b()}))}var d=!1,f=!1,g=!1,e,h={Hidden:0,Visible:1,VisiblePastThreshold:2,VisibilityReported:3},k;return{init:function(a){e=a},setup:function(a){a&&a.SIV&&c()},checkVisibility:function(){"complete"===document.readyState&&d&&b()}}}(),Text:function(){function a(a,b){var g=Admeta.Text.AdGroup[Admeta.Text.AdGroup.length-1];g.Operation=
a;g.placementDetails=b;var e;e=5<=b.length?b[4]:void 0;var h=b[0],k=Admeta.xRenderF,l;k?(l=k[h],k[h]=void 0,e=e&&k[e]?k[e]:l):e=k;g.xRenderF=e;g.js?(c=Admeta.defLoad||0===a,Admeta.Script.load(g.js,Admeta.defLoad||0===a,void 0,0)):Admeta.Text.loadTextAdsJs(a)}var b=!1,c=!1;return{AdGroup:[],init:function(){this.AdGroup.push({initArgs:arguments,Ads:[],xRenderF:void 0})},create:function(){this.AdGroup[this.AdGroup.length-1].Ads.push(arguments)},insert:function(){Admeta.storeMaterial(arguments[2]);Admeta.storeRtbAdvertiser(arguments[9]);
a(0,arguments)},write:function(){Admeta.storeMaterial(arguments[2]);Admeta.storeRtbAdvertiser(arguments[9]);a(1,arguments)},pushPlacement:function(a){document.write('<div id="'+a+'"></div>')},customRender:function(a,b,c){var e=this.AdGroup[this.AdGroup.length-1];e.js=a;e.rop=1;void 0===Admeta.xRenderF&&(Admeta.xRenderF={});Admeta.xRenderF[c]=b},resetCustomRender:function(a){Admeta.xRenderF&&(Admeta.xRenderF[a]=void 0)},loadTextAdsJs:function(a){void 0===Admeta.Text.ProcessTextAds?b||(b=!0,z(n.Undef,
"Loading textads.js."),Admeta.Script.load(Admeta.versionFile(Admeta.textAdsJS,Admeta.textVersion),Admeta.defLoad||0===a||void 0===a&&c,void 0,0)):Admeta.Text.ProcessTextAds()}}}(),Script:function(){var a=[],b=0;return{loaded:function(){try{Admeta.inFrontCall=!1;if(void 0!==window.AdmetaIframed)try{top.Admeta.loadNext(Admeta.adsServed)}catch(d){}Admeta.processAsync();0<b&&b--;if(0===b&&0<a.length){var c=a.pop();Admeta.Script.load(c.url,!0,c.id,1)}else Admeta.Dispatcher.signalDone();Admeta.SIV.checkVisibility()}catch(d){R(d,
"Exception on Script.loaded")}},load:function(c,d,f,g){"complete"===document.readyState&&(d=!0);if(g&&d&&0<b)a.push({url:c,id:f});else try{g&&b++,c=Admeta.setParams(c,[["exm",void 0!==Admeta.adsServed?Admeta.adsServed.join(","):""],["exr",void 0!==Admeta.rtbAdvertisersServed?Admeta.rtbAdvertisersServed.join(","):""],["cts",(new Date).getTime()]]),d?(A("e=defload&p="+encodeURIComponent(c)),Admeta.Script.loadInTag(c,f)):(A("e=dwload&p="+encodeURIComponent(c)),document.write("<script charset='utf-8' type='text/javascript' src='"+
c+"'>\x3c/script>"))}catch(e){R(e,"Load fail: "+c),g&&b--}},loadInTag:function(a,b,f){var g,e=g=window,h=document;if(f){do try{g=e,e=e.parent}catch(k){e=g;break}while(e!==g);h=e.document}g=[h.getElementsByTagName("script")[0],h.getElementsByTagName("body")[0]];f=g[0];g=g[1];e=document.createElement("script");e.type="text/javascript";e.async=!0;b&&(e.id=b);e.src=a;"undefined"!==typeof f&&null!==f?f.parentNode.insertBefore(e,f):g.appendChild(e)}}}(),AdChoices:function(){function a(a){var b="right:0px;bottom:0px";
1===c&&(b="left:0px;bottom:0px");2===c&&(b="left:0px;top:0px");3===c&&(b="right:0px;top:0px");return"position:absolute;"+b+';z-index:101;border:0;padding:0;margin:0;font-size:0;background: transparent url("'+a+'") no-repeat right top;height:'+h+"px;overflow:hidden;left:auto;bottom:auto;cursor:pointer;"}var b=!1,c=0,d,f="",g=0,e=0,h=0,k="";return{init:function(a,p,m,n,t,w,v,z){b=a;c=p;d=m;f=n;e=t;g=w;h=v;k=z},showHide:function(a,b){document.getElementById(a).style.display="block";document.getElementById(b).style.display=
"none"},getCode:function(c){if(!b)return"";var h="_c_"+c.gid,m="_e_"+c.gid,n="'Admeta.AdChoices.showHide(\""+h+'", "'+m+"\")'",t="'Admeta.AdChoices.showHide(\""+m+'", "'+h+"\")'";c.adChoicesIdCollapsed=h;c.adChoicesWidth=e;return"<a id='"+h+"' style='"+(a(d)+"width:"+e+"px;")+"' onmouseover="+t+" href='"+k+"' target='_blank'></a><a id='"+m+"' style='display:none;"+(a(f)+"width:"+g+"px;")+"' onmouseout="+n+" href='"+k+"' target='_blank'></a>"}}}(),Dispatcher:function(){function a(){top.Admeta||(top.Admeta=
{});top.Admeta.ParentDispatch||(top.Admeta.ParentDispatch={ifrInQueue:[],busy:!1});var a=top.Admeta.ParentDispatch;top.Admeta.ParentDispatch.nextInQueue=function(){0===a.ifrInQueue.length||a.busy||(a.ifrInQueue.shift(1).Admeta.Dispatcher.processImpressions(a.adsServed,a.rtbAdvertisersServed),a.busy=!0)};top.Admeta.ParentDispatch.setupCallback=function(b){a.ifrInQueue.push(b);1===a.ifrInQueue.length&&a.nextInQueue()};top.Admeta.ParentDispatch.loadNext=function(b,c){a.adsServed||(a.adsServed=[]);b&&
N(a.adsServed,b);a.rtbAdvertisersServed||(a.rtbAdvertisersServed=[]);c&&N(a.rtbAdvertisersServed,c);a.busy=!1;a.nextInQueue()}}var b=!1,c=!1;return{init:function(){if(w()===m.SameDomainIframe){try{a()}catch(c){return}b||(b=!0)}},processImpressions:function(a,b){window.ADM_PL={defLoad:!0};Admeta.adsServed=a;Admeta.rtbAdvertisersServed=b;J(!0)},delayImpression:function(){var a;(a=!window.ADM_PL||!b||"fp"===window.ADM_PL.tp||"fpc"===window.ADM_PL.tp)||(a=da(Pa)?!0:window.AdmetaDisableIfrHTO);if(a)return!1;
var f;a:{try{f=top.Admeta.ParentDispatch.busy;break a}catch(g){}f=!1}if(!f){try{top.Admeta.ParentDispatch.busy=!0}catch(g){}return!1}za();z(n.ReceiveRequestInFriendlyIframe,ADM_PL);Admeta.base=O(Admeta.base);switch(ADM_PL.tp){case "spt":case "fpt":H(ADM_PL.tagId);break;default:X()}window.ADM_PL=void 0;c=!1;try{top.Admeta.ParentDispatch.setupCallback(window)}catch(g){Admeta.Dispatcher.processImpressions(Admeta.adsServed,Admeta.rtbAdvertisersServed)}setTimeout(Admeta.Dispatcher.signalDone,8E3);return!0},
signalDone:function(){try{w()===m.SameDomainIframe?c||top.Admeta.ParentDispatch.loadNext(Admeta.adsServed,Admeta.rtbAdvertisersServed):window.disableIframeCheck&&top.Admeta.ParentDispatch&&(top.Admeta.ParentDispatch.busy=!1)}catch(a){}c=!0}}}()}}();Admeta.processImpressions();
