(function (){ var e="",aa="\x00",h=" ",ba=" (",ca=" (Google)",da=' name="',ea=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678)',ga=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678) alpha(opacity=50)',ha=' type="',ia=" x ",ja='"',ka='"trebuchet ms",verdana,arial,sans-serif',la="#",ma="#000",na="#fff",oa="%",pa="%$1",qa="%2525",ra="%s",l="&",
ta="&#0;",ua="&#39;",va="&action=",wa="&amp;",xa="&func=",ya="&gt;",za="&lt;",Aa="&nbsp;",Ba="&quot;",Ca="&sectionId=",Da="&widgetId=",Ea="&widgetType=",Fa="'",Ga="(",Ha="(\\d*)(\\D*)",Ia=")",Ja="*",Ka=",",La="-140px",Ma="-225px",Na=".",Oa=".01",Pa=".5",Qa=".js",Sa=".previewMode .postCommentButtonHolder { padding-top: 22px; }\n",Ta=".x",Ua=".y",Va="/",Wa="//",Xa="//img2.blogblog.com/img/icon_inprogress.gif",Ya="/comment-iframe-bg.g",Za="/rearrange?blogID=",$a="0",ab="1",bb="100%",cb="1000",db="10px",
eb="1px solid #aaa",fb="1px solid transparent",gb="200px",hb="24px",ib="28px",jb="50% 0",kb="600px",lb="75px",mb=":",nb=": ",ob=";\nfont-family: ",pb=";}\n",qb="<",n="=",rb=">",sb="?",tb="?widgetId=",ub="@",vb="AIM",wb="AIM username:",xb="ANON",yb="ARIA attribute cannot be empty.",zb="An error occurred while contacting the server.",Ab="An object listener must have handleEvent method.",Bb="Anonymous",Cb="Assertion failed",Db="BODY",Eb="CSS1Compat",Fb="CURRENT",Gb="Comment should not be empty",Hb="Content length exceeds 1MB. Please abridge.",
Ib="Content-Type",Jb="DIV",Kb="Event target is not initialized. Did you call the superclass (goog.events.EventTarget) constructor?",Lb="Expected number but got %s: %s.",Mb="Expected string but got %s: %s.",Nb="FIELDSET",Ob="GET",Pb="GOOGLE",Qb="Google Account",Rb="HEAD",Sb="INPUT",Tb="LJ",Ub="Listener can not be null.",Vb="LiveJournal",Wb="LiveJournal username:",Xb="MSXML2.XMLHTTP",Yb="MSXML2.XMLHTTP.3.0",Zb="MSXML2.XMLHTTP.6.0",$b="Microsoft Internet Explorer",ac="Microsoft.XMLHTTP",bc="NAMEURL",
cc="NONE",dc="Name should not be empty",ec="Name/URL",fc="No such ARIA attribute expanded",gc="No such ARIA role tab",hc="Node cannot be null or undefined.",ic="OPENID",jc="OpenID",kc="POST",lc="Please choose a profile",mc="Preview",nc="SCRIPT",oc="STYLE",pc="Select profile...",qc="SubscribeByEmail",rc="TP",sc="The URL should not be empty",tc="The username should not be empty",uc="TypePad",vc="TypePad username:",wc="UnsubscribeByEmail",xc="WP",yc="WordPress",zc="WordPress username:",Ac="X",Bc="[object Array]",
Cc="[object Function]",Dc="[object Window]",Ec="]",Fc="_",Gc="_OnWidgetDeleted",Hc="__gjsload__",Ic="_asynchronousFileUploadIframe",Jc="_changeImageLink",Kc="_imageChoiceTable",Lc="_imgFileNameError",Mc="_imgFileNameInput",Nc="_imgSrcFromPCRadio",Oc="_imgSrcFromWebRadio",Pc="_imgUrlTextError",Qc="_imgUrlTextInput",Rc="_picImg",Sc="a",Tc="a:link, a:visited, a:active, a:hover { color: ",Uc="abort",Vc="absolute",Wc="action",Xc="action=",Yc="additions text",Zc="addnew",$c="ajaxAction",ad="allHolder",
bd="alpha(opacity=1)",cd="animate",dd="anonNameField",ed="anonUrlField",fd="application/x-www-form-urlencoded;charset=utf-8",gd="aria-",hd="aria-expanded",id="array",jd="arraybuffer",kd="begin",ld="bgint",md="bgresponse",nd="block",od="blogID",pd="blogger-clickTrap singleton-element",qd="blur",rd="body { color: ",sd="button",td="call",ud="captcha-error",vd="center",wd="change",xd="checkbox",yd="checked",zd="chooseWidget",Ad="class",Bd="click",Cd="commentBody-err",Dd="commentBodyField",Ed="commentDash",
Fd="commentForm",Gd="commentSubscriptionForm",Hd="compact",p="complete",Id="config",Jd="configure",Kd="content-type",Ld="data-",Md="default",Nd="delete",Od="destroy",Pd="disabled",Qd="display",Rd="displayModeFull",Sd="displayModeLayout",Td="displayModeNone",Ud="displayModeSnippet",Vd="div",Wd="downloadprogress",Xd="edit-link",Yd="editButton",Zd="editlink",$d="encodedIds",ae="encodedSelectedId",be="end",ce="error",de="error-details",ee="errorbox-bad errormsg",fe="errorbox-good",ge="errormessage_",
he="event",ie="expanded",je="expression(this.parentNode.clientHeight)",ke="false",le="file",me="finish",ne="focus",oe="for",pe="form",q="function",qe="g",re="genericOpenIdDialogErrorHolder",se="genericOpenIdIdentityHolder",te="goog-zippy-collapsed",ue="goog-zippy-content",ve="goog-zippy-expanded",we="goog-zippy-header",xe="goog.net.EventType.PROGRESS is of the same type as raw XHR progress.",ye="hidden",ze="href",Ae="http",Be="http://",Ce="http://openid.aol.com/{username}",De="http://{username}.livejournal.com",
Ee="http://{username}.wordpress.com",Fe="https://profile.typepad.com/{username}",Ge="id",He="id-error",Ie="identity-type-",Je="identityControlsHolder",Ke="identityHolder",Le="identityMenu",Me="iemode",Ne="image",Oe="imageUpload.do",Pe="img",Qe="infinite loop",Re="inline",Se="input",Te="keydown",Ue="keypress",Ve="keyup",We="layout-title",Xe="main-error",Ye="main-error-holder",Ze="main-status",$e="main-status-holder",af="mouseout",bf="mouseover",cf="mozResponseArrayBuffer",df="multipart/form-data",
ef="nameUrlDialogErrorHolder",ff="nameUrlIdentityHolder",gf="native code",hf="no type",jf="no widget for ",t="none",kf="null",lf="number",mf="o",nf="object",of="off",pf="on",qf="oninput",rf="onprogress",sf="openIdDialogErrorHolder",tf="openIdIdentityHolder",uf="openIdUriDisplayPrefix",vf="openIdUriDisplaySuffix",wf="openIdUriDisplayUsername",xf="openIdUriField",yf="openIdUserNameField",zf="openIdUsernameLabel",Af="option",Bf="overflow:hidden",Cf="page",Df="pageID",Ef="play",Ff="polyfill",Gf="postCommentPreview",
Hf="postCommentSubmit",If="previewHolder",Jf="previewMode",Kf="progress",Lf="px",Mf="radio",Nf="ready",Of="readystatechange",Pf="reset",Qf="response",Rf="responseType=js",Sf="resume",Tf="role",Uf="rotate(-45deg)",Vf="sectionId",Wf="sectionWidth",Xf="security_token",Yf="select",Zf="select-multiple",$f="select-one",ag="set-comment-editor-height ",bg="settingsButton",cg="showPreview",dg="singleton-element",eg="span",fg="splice",gg="status-message",hg="status-message-inner",ig="stop",jg="string",kg="style",
lg="submit",mg="subscribeButtonHolder",ng="success",og="tab",pg="text",qg="text/javascript",rg="timeout",sg="toggle",tg="true",ug="uploadprogress",vg="use",wg="username",xg="var ",yg="vertical",zg="viewBox",Ag="white",Bg="widget-content",Cg="widget-wrap1",Dg="widget-wrap2",Eg="widget-wrap3",Fg="widgetId=",Gg="widgetType",Hg="widgetType=",Ig="width=570,height=600,left=75,top=20,resizable=yes,scrollbars=yes",Jg="window",Kg="withCredentials",Lg="xlink:href",Mg="{username}",u,Ng=Ng||{},v=this,w=function(a){return void 0!==
a},x=function(a,b,c){a=a.split(Na);c=c||v;a[0]in c||!c.execScript||c.execScript(xg+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&w(b)?c[d]=b:c=c[d]?c[d]:c[d]={}},Og=function(){},Pg=function(a){a.Xf=function(){return a.Od?a.Od:a.Od=new a}},Qg=function(a){var b=typeof a;if(b==nf)if(a){if(a instanceof Array)return id;if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c==Dc)return nf;if(c==Bc||typeof a.length==lf&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&
!a.propertyIsEnumerable(fg))return id;if(c==Cc||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(td))return q}else return kf;else if(b==q&&"undefined"==typeof a.call)return nf;return b},y=function(a){return Qg(a)==id},Rg=function(a){var b=Qg(a);return b==id||b==nf&&typeof a.length==lf},z=function(a){return typeof a==jg},Sg=function(a){return typeof a==lf},Tg=function(a){return Qg(a)==q},Ug=function(a){var b=typeof a;return b==nf&&null!=a||b==q},Vg="closure_uid_"+
(1E9*Math.random()>>>0),Wg=0,Xg=function(a,b,c){return a.call.apply(a.bind,arguments)},Yg=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},A=function(a,b,c){A=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf(gf)?Xg:Yg;return A.apply(null,arguments)},Zg=Date.now||
function(){return+new Date},B=function(a,b){function c(){}c.prototype=b.prototype;a.h=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.mj=function(a,c,g){for(var k=Array(arguments.length-2),m=2;m<arguments.length;m++)k[m-2]=arguments[m];return b.prototype[c].apply(a,k)}};var $g=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,$g);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};B($g,Error);$g.prototype.name="CustomError";var ah;var bh=function(a,b){for(var c=a.split(ra),d=e,f=Array.prototype.slice.call(arguments,1);f.length&&1<c.length;)d+=c.shift()+f.shift();return d+c.join(ra)},ch=function(a){return a.replace(/(\r\n|\r|\n)+/g,h)},dh=function(a){return a.replace(/\xa0|[ \t]+/g,h)},eh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,e)},mh=function(a,b){if(b)a=a.replace(fh,wa).replace(gh,za).replace(hh,ya).replace(ih,Ba).replace(jh,ua).replace(kh,ta);else{if(!lh.test(a))return a;
-1!=a.indexOf(l)&&(a=a.replace(fh,wa));-1!=a.indexOf(qb)&&(a=a.replace(gh,za));-1!=a.indexOf(rb)&&(a=a.replace(hh,ya));-1!=a.indexOf(ja)&&(a=a.replace(ih,Ba));-1!=a.indexOf(Fa)&&(a=a.replace(jh,ua));-1!=a.indexOf(aa)&&(a=a.replace(kh,ta))}return a},fh=/&/g,gh=/</g,hh=/>/g,ih=/"/g,jh=/'/g,kh=/\x00/g,lh=/[\x00&<>"']/,nh=function(a,b){return a<b?-1:a>b?1:0};var oh=function(a,b){b.unshift(a);$g.call(this,bh.apply(null,b));b.shift()};B(oh,$g);oh.prototype.name="AssertionError";var ph=function(a,b,c,d){var f=Cb;if(c)var f=f+(nb+c),g=d;else a&&(f+=nb+a,g=b);throw new oh(e+f,g||[]);},C=function(a,b,c){a||ph(e,null,b,Array.prototype.slice.call(arguments,2));return a},D=function(a,b,c){Sg(a)||ph(Lb,[Qg(a),a],b,Array.prototype.slice.call(arguments,2));return a},qh=function(a,b,c){z(a)||ph(Mb,[Qg(a),a],b,Array.prototype.slice.call(arguments,2));return a};var rh=Array.prototype.indexOf?function(a,b,c){C(null!=a.length);return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(z(a))return z(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},sh=Array.prototype.lastIndexOf?function(a,b,c){C(null!=a.length);return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(z(a))return z(b)&&1==
b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1},th=Array.prototype.forEach?function(a,b,c){C(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=z(a)?a.split(e):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)},uh=Array.prototype.filter?function(a,b,c){C(null!=a.length);return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],g=0,k=z(a)?a.split(e):a,m=0;m<d;m++)if(m in k){var r=k[m];b.call(c,r,m,a)&&(f[g++]=
r)}return f},vh=Array.prototype.some?function(a,b,c){C(null!=a.length);return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=z(a)?a.split(e):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a))return!0;return!1},wh=function(a,b,c){a:{for(var d=a.length,f=z(a)?a.split(e):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a)){b=g;break a}b=-1}return 0>b?null:z(a)?a.charAt(b):a[b]},E=function(a,b){return 0<=rh(a,b)},xh=function(a){if(!y(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0},
zh=function(a,b){var c=rh(a,b),d;(d=0<=c)&&yh(a,c);return d},yh=function(a,b){C(null!=a.length);return 1==Array.prototype.splice.call(a,b,1).length},Ah=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)},Bh=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Ch=function(a,b,c){C(null!=a.length);return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var Dh=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Eh=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Fh=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},Gh=function(a,b){return null!==a&&b in a},Hh=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1},Ih=function(a){for(var b in a)return!1;return!0},Jh="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Kh=function(a,b){for(var c,d,f=1;f<arguments.length;f++){d=
arguments[f];for(c in d)a[c]=d[c];for(var g=0;g<Jh.length;g++)c=Jh[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var F;a:{var Lh=v.navigator;if(Lh){var Mh=Lh.userAgent;if(Mh){F=Mh;break a}}F=e};var Nh=function(a,b){this.width=a;this.height=b};u=Nh.prototype;u.clone=function(){return new Nh(this.width,this.height)};u.toString=function(){return Ga+this.width+ia+this.height+Ia};u.Cf=function(){return this.width*this.height};u.isEmpty=function(){return!this.Cf()};u.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var Oh=-1!=F.indexOf("Opera")||-1!=F.indexOf("OPR"),G=-1!=F.indexOf("Trident")||-1!=F.indexOf("MSIE"),Ph=-1!=F.indexOf("Edge"),Qh=-1!=F.indexOf("Gecko")&&!(-1!=F.toLowerCase().indexOf("webkit")&&-1==F.indexOf("Edge"))&&!(-1!=F.indexOf("Trident")||-1!=F.indexOf("MSIE"))&&-1==F.indexOf("Edge"),Rh=-1!=F.toLowerCase().indexOf("webkit")&&-1==F.indexOf("Edge"),Sh=function(){var a=v.document;return a?a.documentMode:void 0},Th;
a:{var Uh=e,Vh=function(){var a=F;if(Qh)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Ph)return/Edge\/([\d\.]+)/.exec(a);if(G)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Rh)return/WebKit\/(\S+)/.exec(a);if(Oh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Vh&&(Uh=Vh?Vh[1]:e);if(G){var Wh=Sh();if(null!=Wh&&Wh>parseFloat(Uh)){Th=String(Wh);break a}}Th=Uh}
var Xh=Th,Yh={},H=function(a){var b;if(!(b=Yh[a])){b=0;for(var c=eh(String(Xh)).split(Na),d=eh(String(a)).split(Na),f=Math.max(c.length,d.length),g=0;0==b&&g<f;g++){var k=c[g]||e,m=d[g]||e,r=RegExp(Ha,qe),sa=RegExp(Ha,qe);do{var X=r.exec(k)||[e,e,e],Ra=sa.exec(m)||[e,e,e];if(0==X[0].length&&0==Ra[0].length)break;b=nh(0==X[1].length?0:parseInt(X[1],10),0==Ra[1].length?0:parseInt(Ra[1],10))||nh(0==X[2].length,0==Ra[2].length)||nh(X[2],Ra[2])}while(0==b)}b=Yh[a]=0<=b}return b},Zh=v.document,$h=Zh&&G?
Sh()||(Zh.compatMode==Eb?parseInt(Xh,10):5):void 0;var ai=!G||9<=Number($h);!Qh&&!G||G&&9<=Number($h)||Qh&&H("1.9.1");G&&H("9");var di=function(a){return a?new bi(ci(a)):ah||(ah=new bi)},I=function(a){return z(a)?document.getElementById(a):a},fi=function(a,b){Dh(b,function(b,d){d==kg?a.style.cssText=b:d==Ad?a.className=b:d==oe?a.htmlFor=b:ei.hasOwnProperty(d)?a.setAttribute(ei[d],b):0==d.lastIndexOf(gd,0)||0==d.lastIndexOf(Ld,0)?a.setAttribute(d,b):a[d]=b})},ei={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:Tf,rowspan:"rowSpan",
type:"type",usemap:"useMap",valign:"vAlign",width:"width"},hi=function(a,b,c){return gi(document,arguments)},gi=function(a,b){var c=b[0],d=b[1];if(!ai&&d&&(d.name||d.type)){c=[qb,c];d.name&&c.push(da,mh(d.name),ja);if(d.type){c.push(ha,mh(d.type),ja);var f={};Kh(f,d);delete f.type;d=f}c.push(rb);c=c.join(e)}c=a.createElement(c);d&&(z(d)?c.className=d:y(d)?c.className=d.join(h):fi(c,d));2<b.length&&ii(a,c,b,2);return c},ii=function(a,b,c,d){function f(c){c&&b.appendChild(z(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var g=c[d];!Rg(g)||Ug(g)&&0<g.nodeType?f(g):th(ji(g)?Bh(g):g,f)}},ki=function(a){for(var b;b=a.firstChild;)a.removeChild(b)},ci=function(a){C(a,hc);return 9==a.nodeType?a:a.ownerDocument||a.document},ji=function(a){if(a&&typeof a.length==lf){if(Ug(a))return typeof a.item==q||typeof a.item==jg;if(Tg(a))return typeof a.item==q}return!1},bi=function(a){this.ta=a||v.document||document};u=bi.prototype;u.rb=function(a){return z(a)?this.ta.getElementById(a):a};
u.zd=function(a,b,c){c=c||this.ta;a=a&&a!=Ja?a.toUpperCase():e;if(c.querySelectorAll&&c.querySelector&&(a||b))b=c.querySelectorAll(a+(b?Na+b:e));else if(b&&c.getElementsByClassName)if(c=c.getElementsByClassName(b),a){for(var d={},f=0,g=0,k;k=c[g];g++)a==k.nodeName&&(d[f++]=k);d.length=f;b=d}else b=c;else if(c=c.getElementsByTagName(a||Ja),b){d={};for(g=f=0;k=c[g];g++)a=k.className,typeof a.split==q&&E(a.split(/\s+/),b)&&(d[f++]=k);d.length=f;b=d}else b=c;return b};
u.dc=function(a,b,c){return gi(this.ta,arguments)};u.createElement=function(a){return this.ta.createElement(a)};u.createTextNode=function(a){return this.ta.createTextNode(String(a))};u.appendChild=function(a,b){a.appendChild(b)};u.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var J=function(){this.sa=this.sa;this.Hb=this.Hb};J.prototype.sa=!1;J.prototype.la=function(){this.sa||(this.sa=!0,this.l())};J.prototype.l=function(){if(this.Hb)for(;this.Hb.length;)this.Hb.shift()()};var li=function(a){a&&typeof a.la==q&&a.la()};var K=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.pa=!1;this.qe=!0};K.prototype.stopPropagation=function(){this.pa=!0};K.prototype.preventDefault=function(){this.defaultPrevented=!0;this.qe=!1};var mi=function(a){mi[h](a);return a};mi[h]=Og;var ni=!G||9<=Number($h),oi=G&&!H("9");!Rh||H("528");Qh&&H("1.9b")||G&&H("8")||Oh&&H("9.5")||Rh&&H("528");Qh&&!H("8")||G&&H("9");var L=function(a,b){K.call(this,a?a.type:e);this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.La=this.state=null;a&&this.Md(a,b)};B(L,K);
L.prototype.Md=function(a,b){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;var f=a.relatedTarget;if(f){if(Qh){var g;a:{try{mi(f.nodeName);g=!0;break a}catch(k){}g=!1}g||(f=null)}}else c==bf?f=a.fromElement:c==af&&(f=a.toElement);this.relatedTarget=f;null===d?(this.offsetX=Rh||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=Rh||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=
void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c==Ue?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.La=a;a.defaultPrevented&&this.preventDefault()};
L.prototype.stopPropagation=function(){L.h.stopPropagation.call(this);this.La.stopPropagation?this.La.stopPropagation():this.La.cancelBubble=!0};L.prototype.preventDefault=function(){L.h.preventDefault.call(this);var a=this.La;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,oi)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var pi="closure_listenable_"+(1E6*Math.random()|0),qi=function(a){return!(!a||!a[pi])},ri=0;var si=function(a,b,c,d,f,g){this.listener=a;this.proxy=b;this.src=c;this.type=d;this.ib=!!f;this.vb=g;this.key=++ri;this.Ba=this.hb=!1};si.prototype.Fb=function(){this.Ba=!0;this.vb=this.src=this.proxy=this.listener=null};var ti=function(a){this.src=a;this.o={};this.ab=0};u=ti.prototype;u.add=function(a,b,c,d,f){var g=a.toString();a=this.o[g];a||(a=this.o[g]=[],this.ab++);var k=ui(a,b,d,f);-1<k?(b=a[k],c||(b.hb=!1)):(b=new si(b,null,this.src,g,!!d,f),b.hb=c,a.push(b));return b};u.remove=function(a,b,c,d){a=a.toString();if(!(a in this.o))return!1;var f=this.o[a];b=ui(f,b,c,d);return-1<b?(f[b].Fb(),yh(f,b),0==f.length&&(delete this.o[a],this.ab--),!0):!1};
u.me=function(a){var b=a.type;if(!(b in this.o))return!1;var c=zh(this.o[b],a);c&&(a.Fb(),0==this.o[b].length&&(delete this.o[b],this.ab--));return c};u.Jb=function(a){a=a&&a.toString();var b=0,c;for(c in this.o)if(!a||c==a){for(var d=this.o[c],f=0;f<d.length;f++)++b,d[f].Fb();delete this.o[c];this.ab--}return b};u.Ma=function(a,b,c,d){a=this.o[a.toString()];var f=-1;a&&(f=ui(a,b,c,d));return-1<f?a[f]:null};
var ui=function(a,b,c,d){for(var f=0;f<a.length;++f){var g=a[f];if(!g.Ba&&g.listener==b&&g.ib==!!c&&g.vb==d)return f}return-1};var vi="closure_lm_"+(1E6*Math.random()|0),wi={},xi=0,M=function(a,b,c,d,f){if(y(b)){for(var g=0;g<b.length;g++)M(a,b[g],c,d,f);return null}c=yi(c);return qi(a)?a.Aa(b,c,d,f):zi(a,b,c,!1,d,f)},zi=function(a,b,c,d,f,g){if(!b)throw Error("Invalid event type");var k=!!f,m=Ai(a);m||(a[vi]=m=new ti(a));c=m.add(b,c,d,f,g);if(c.proxy)return c;d=Bi();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,k);else if(a.attachEvent)a.attachEvent(Ci(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");
xi++;return c},Bi=function(){var a=Di,b=ni?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},Ei=function(a,b,c,d,f){if(y(b)){for(var g=0;g<b.length;g++)Ei(a,b[g],c,d,f);return null}c=yi(c);return qi(a)?a.uc(b,c,d,f):zi(a,b,c,!0,d,f)},Fi=function(a,b,c,d,f){if(y(b)){for(var g=0;g<b.length;g++)Fi(a,b[g],c,d,f);return null}c=yi(c);if(qi(a))return a.Ob(b,c,d,f);if(!a)return!1;if(a=Ai(a))if(b=a.Ma(b,c,!!d,f))return Gi(b);return!1},Gi=function(a){if(Sg(a)||
!a||a.Ba)return!1;var b=a.src;if(qi(b))return b.Ie(a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.ib):b.detachEvent&&b.detachEvent(Ci(c),d);xi--;(c=Ai(b))?(c.me(a),0==c.ab&&(c.src=null,b[vi]=null)):a.Fb();return!0},Hi=function(a,b){if(!a)return 0;if(qi(a))return a.le(b);var c=Ai(a);if(!c)return 0;var d=0,f=b&&b.toString(),g;for(g in c.o)if(!f||g==f)for(var k=c.o[g].concat(),m=0;m<k.length;++m)Gi(k[m])&&++d;return d},Ci=function(a){return a in wi?wi[a]:wi[a]=pf+a},Ji=function(a,
b,c,d){var f=!0;if(a=Ai(a))if(b=a.o[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.ib==c&&!g.Ba&&(g=Ii(g,d),f=f&&!1!==g)}return f},Ii=function(a,b){var c=a.listener,d=a.vb||a.src;a.hb&&Gi(a);return c.call(d,b)},Di=function(a,b){if(a.Ba)return!0;if(!ni){var c;if(!(c=b))a:{c=[Jg,he];for(var d=v,f;f=c.shift();)if(null!=d[f])d=d[f];else{c=null;break a}c=d}f=c;c=new L(f,this);d=!0;if(!(0>f.keyCode||void 0!=f.returnValue)){a:{var g=!1;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(r){g=
!0}if(g||void 0==f.returnValue)f.returnValue=!0}f=[];for(g=c.currentTarget;g;g=g.parentNode)f.push(g);for(var g=a.type,k=f.length-1;!c.pa&&0<=k;k--){c.currentTarget=f[k];var m=Ji(f[k],g,!0,c),d=d&&m}for(k=0;!c.pa&&k<f.length;k++)c.currentTarget=f[k],m=Ji(f[k],g,!1,c),d=d&&m}return d}return Ii(a,new L(b,this))},Ai=function(a){a=a[vi];return a instanceof ti?a:null},Ki="__closure_events_fn_"+(1E9*Math.random()>>>0),yi=function(a){C(a,Ub);if(Tg(a))return a;C(a.handleEvent,Ab);a[Ki]||(a[Ki]=function(b){return a.handleEvent(b)});
return a[Ki]};var N=function(){J.call(this);this.V=new ti(this);this.vf=this;this.Bc=null};B(N,J);N.prototype[pi]=!0;u=N.prototype;u.addEventListener=function(a,b,c,d){M(this,a,b,c,d)};u.removeEventListener=function(a,b,c,d){Fi(this,a,b,c,d)};
u.dispatchEvent=function(a){this.fd();var b,c=this.Bc;if(c){b=[];for(var d=1;c;c=c.Bc)b.push(c),C(1E3>++d,Qe)}c=this.vf;d=a.type||a;if(z(a))a=new K(a,c);else if(a instanceof K)a.target=a.target||c;else{var f=a;a=new K(d,c);Kh(a,f)}var f=!0,g;if(b)for(var k=b.length-1;!a.pa&&0<=k;k--)g=a.currentTarget=b[k],f=g.pb(d,!0,a)&&f;a.pa||(g=a.currentTarget=c,f=g.pb(d,!0,a)&&f,a.pa||(f=g.pb(d,!1,a)&&f));if(b)for(k=0;!a.pa&&k<b.length;k++)g=a.currentTarget=b[k],f=g.pb(d,!1,a)&&f;return f};
u.l=function(){N.h.l.call(this);this.le();this.Bc=null};u.Aa=function(a,b,c,d){this.fd();return this.V.add(String(a),b,!1,c,d)};u.uc=function(a,b,c,d){return this.V.add(String(a),b,!0,c,d)};u.Ob=function(a,b,c,d){return this.V.remove(String(a),b,c,d)};u.Ie=function(a){return this.V.me(a)};u.le=function(a){return this.V?this.V.Jb(a):0};
u.pb=function(a,b,c){a=this.V.o[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,f=0;f<a.length;++f){var g=a[f];if(g&&!g.Ba&&g.ib==b){var k=g.listener,m=g.vb||g.src;g.hb&&this.Ie(g);d=!1!==k.call(m,c)&&d}}return d&&0!=c.qe};u.Ma=function(a,b,c,d){return this.V.Ma(String(a),b,c,d)};u.fd=function(){C(this.V,Kb)};var Li=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,ub).replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,Ec).replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,e)))try{return eval(Ga+a+Ia)}catch(b){}throw Error("Invalid JSON string: "+a);};var Mi=function(a){return a};var Ni="StopIteration"in v?v.StopIteration:{message:"StopIteration",stack:e},Oi=function(){};Oi.prototype.next=function(){throw Ni;};Oi.prototype.Yb=function(){return this};var Pi=function(a,b){this.j={};this.c=[];this.bb=this.b=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};u=Pi.prototype;u.s=function(){return this.b};u.u=function(){this.lb();for(var a=[],b=0;b<this.c.length;b++)a.push(this.j[this.c[b]]);return a};u.K=function(){this.lb();return this.c.concat()};u.ka=function(a){return Qi(this.j,a)};u.isEmpty=function(){return 0==this.b};
u.clear=function(){this.j={};this.bb=this.b=this.c.length=0};u.remove=function(a){return Qi(this.j,a)?(delete this.j[a],this.b--,this.bb++,this.c.length>2*this.b&&this.lb(),!0):!1};u.lb=function(){if(this.b!=this.c.length){for(var a=0,b=0;a<this.c.length;){var c=this.c[a];Qi(this.j,c)&&(this.c[b++]=c);a++}this.c.length=b}if(this.b!=this.c.length){for(var d={},b=a=0;a<this.c.length;)c=this.c[a],Qi(d,c)||(this.c[b++]=c,d[c]=1),a++;this.c.length=b}};
u.get=function(a,b){return Qi(this.j,a)?this.j[a]:b};u.set=function(a,b){Qi(this.j,a)||(this.b++,this.c.push(a),this.bb++);this.j[a]=b};u.addAll=function(a){var b;a instanceof Pi?(b=a.K(),a=a.u()):(b=Fh(a),a=Eh(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};u.forEach=function(a,b){for(var c=this.K(),d=0;d<c.length;d++){var f=c[d],g=this.get(f);a.call(b,g,f,this)}};u.clone=function(){return new Pi(this)};
u.Yb=function(a){this.lb();var b=0,c=this.bb,d=this,f=new Oi;f.next=function(){if(c!=d.bb)throw Error("The map has changed since the iterator was created");if(b>=d.c.length)throw Ni;var f=d.c[b++];return a?f:d.j[f]};return f};var Qi=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Ri=function(a){if(a.u&&typeof a.u==q)return a.u();if(z(a))return a.split(e);if(Rg(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Eh(a)},Si=function(a,b,c){if(a.forEach&&typeof a.forEach==q)a.forEach(b,c);else if(Rg(a)||z(a))th(a,b,c);else{var d;if(a.K&&typeof a.K==q)d=a.K();else if(a.u&&typeof a.u==q)d=void 0;else if(Rg(a)||z(a)){d=[];for(var f=a.length,g=0;g<f;g++)d.push(g)}else d=Fh(a);for(var f=Ri(a),g=f.length,k=0;k<g;k++)b.call(c,f[k],d&&d[k],a)}};var Ti=function(a){this.j=new Pi;a&&this.addAll(a)},Ui=function(a){var b=typeof a;return b==nf&&a||b==q?mf+(a[Vg]||(a[Vg]=++Wg)):b.substr(0,1)+a};u=Ti.prototype;u.s=function(){return this.j.s()};u.add=function(a){this.j.set(Ui(a),a)};u.addAll=function(a){a=Ri(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};u.Jb=function(a){a=Ri(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};u.remove=function(a){return this.j.remove(Ui(a))};u.clear=function(){this.j.clear()};u.isEmpty=function(){return this.j.isEmpty()};
u.contains=function(a){return this.j.ka(Ui(a))};u.u=function(){return this.j.u()};u.clone=function(){return new Ti(this)};u.Yb=function(){return this.j.Yb(!1)};var Vi=function(a,b,c){if(Tg(a))c&&(a=A(a,c));else if(a&&typeof a.handleEvent==q)a=A(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:v.setTimeout(a,b||0)};var Wi=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,Xi=function(a,b){if(a)for(var c=a.split(l),d=0;d<c.length;d++){var f=c[d].indexOf(n),g=null,k=null;0<=f?(g=c[d].substring(0,f),k=c[d].substring(f+1)):g=c[d];b(g,k?decodeURIComponent(k.replace(/\+/g,h)):e)}};var Yi=function(){};Yi.prototype.ld=null;Yi.prototype.Ed=function(){return this.ld||(this.ld=this.tg())};var Zi,$i=function(){};B($i,Yi);$i.prototype.pd=function(){var a=this.Fd();return a?new ActiveXObject(a):new XMLHttpRequest};$i.prototype.tg=function(){var a={};this.Fd()&&(a[0]=!0,a[1]=!0);return a};
$i.prototype.Fd=function(){if(!this.Kd&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var a=[Zb,Yb,Xb,ac],b=0;b<a.length;b++){var c=a[b];try{return new ActiveXObject(c),this.Kd=c}catch(d){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return this.Kd};Zi=new $i;var O=function(a){N.call(this);this.headers=new Pi;this.Tb=a||null;this.aa=!1;this.Sb=this.a=null;this.tc=e;this.za=0;this.na=this.qc=this.yb=this.ic=!1;this.qa=0;this.Nb=null;this.Ca=e;this.Mc=this.eh=this.Fa=!1};B(O,N);var aj=/^https?$/i,bj=[kc,"PUT"],cj=[],dj=function(a,b,c,d,f,g,k){var m=new O;cj.push(m);b&&m.Aa(p,b);m.uc(Nf,m.Gf);g&&m.Hc(g);k&&m.Ic(k);m.send(a,c,d,f);return m};u=O.prototype;u.Gf=function(){this.la();zh(cj,this)};u.Hc=function(a){this.qa=Math.max(0,a)};
u.mh=function(a){this.Ca=a};u.Ic=function(a){this.Fa=a};
u.send=function(a,b,c,d){if(this.a)throw Error("[goog.net.XhrIo] Object is active with another request="+this.tc+"; newUri="+a);b=b?b.toUpperCase():Ob;this.tc=a;this.za=0;this.ic=!1;this.aa=!0;this.a=this.Kf();this.Sb=this.Tb?this.Tb.Ed():Zi.Ed();this.a.onreadystatechange=A(this.ge,this);this.eh&&rf in this.a&&(this.a.onprogress=A(function(a){this.ee(a,!0)},this),this.a.upload&&(this.a.upload.onprogress=A(this.ee,this)));try{this.qc=!0,this.a.open(b,String(a),!0),this.qc=!1}catch(g){this.xd(5,g);
return}a=c||e;var f=this.headers.clone();d&&Si(d,function(a,b){f.set(b,a)});d=wh(f.K(),ej);c=v.FormData&&a instanceof v.FormData;!E(bj,b)||d||c||f.set(Ib,fd);f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.Ca&&(this.a.responseType=this.Ca);Gh(this.a,Kg)&&(this.a.withCredentials=this.Fa);try{this.md(),0<this.qa&&((this.Mc=fj(this.a))?(this.a.timeout=this.qa,this.a.ontimeout=A(this.Ge,this)):this.Nb=Vi(this.Ge,this.qa,this)),this.yb=!0,this.a.send(a),this.yb=!1}catch(g){this.xd(5,g)}};
var fj=function(a){return G&&H(9)&&Sg(a.timeout)&&w(a.ontimeout)},ej=function(a){return Kd==a.toLowerCase()};u=O.prototype;u.Kf=function(){return this.Tb?this.Tb.pd():Zi.pd()};u.Ge=function(){"undefined"!=typeof Ng&&this.a&&(this.za=8,this.dispatchEvent(rg),this.abort(8))};u.xd=function(a){this.aa=!1;this.a&&(this.na=!0,this.a.abort(),this.na=!1);this.za=a;this.ud();this.kb()};u.ud=function(){this.ic||(this.ic=!0,this.dispatchEvent(p),this.dispatchEvent(ce))};
u.abort=function(a){this.a&&this.aa&&(this.aa=!1,this.na=!0,this.a.abort(),this.na=!1,this.za=a||7,this.dispatchEvent(p),this.dispatchEvent(Uc),this.kb())};u.l=function(){this.a&&(this.aa&&(this.aa=!1,this.na=!0,this.a.abort(),this.na=!1),this.kb(!0));O.h.l.call(this)};u.ge=function(){this.sa||(this.qc||this.yb||this.na?this.fe():this.Yg())};u.Yg=function(){this.fe()};
u.fe=function(){if(this.aa&&"undefined"!=typeof Ng&&(!this.Sb[1]||4!=this.tb()||2!=this.getStatus()))if(this.yb&&4==this.tb())Vi(this.ge,0,this);else if(this.dispatchEvent(Of),this.vg()){this.aa=!1;try{this.Sa()?(this.dispatchEvent(p),this.dispatchEvent(ng)):(this.za=6,this.ud())}finally{this.kb()}}};u.ee=function(a,b){C(a.type===Kf,xe);this.dispatchEvent(gj(a,Kf));this.dispatchEvent(gj(a,b?Wd:ug))};var gj=function(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}};
u=O.prototype;u.kb=function(a){if(this.a){this.md();var b=this.a,c=this.Sb[0]?Og:null;this.Sb=this.a=null;a||this.dispatchEvent(Nf);try{b.onreadystatechange=c}catch(d){}}};u.md=function(){this.a&&this.Mc&&(this.a.ontimeout=null);Sg(this.Nb)&&(v.clearTimeout(this.Nb),this.Nb=null)};u.Ab=function(){return!!this.a};u.vg=function(){return 4==this.tb()};
u.Sa=function(){var a=this.getStatus(),b;a:switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:b=!0;break a;default:b=!1}return b||0===a&&!this.wg()};u.wg=function(){var a=String(this.tc).match(Wi)[1]||null;!a&&v.self&&v.self.location&&(a=v.self.location.protocol,a=a.substr(0,a.length-1));return aj.test(a?a.toLowerCase():e)};u.tb=function(){return this.a?this.a.readyState:0};u.getStatus=function(){try{return 2<this.tb()?this.a.status:-1}catch(a){return-1}};
u.cg=function(){try{return this.a?this.a.responseText:e}catch(a){return e}};u.Gd=function(a){if(this.a){var b=this.a.responseText;a&&0==b.indexOf(a)&&(b=b.substring(a.length));return Li(b)}};u.ag=function(){try{if(!this.a)return null;if(Qf in this.a)return this.a.response;switch(this.Ca){case e:case pg:return this.a.responseText;case jd:if(cf in this.a)return this.a.mozResponseArrayBuffer}return null}catch(a){return null}};var hj=function(){};hj.prototype.R=function(){return cc};hj.prototype.L=function(){return null};var ij=function(a){this.label=a};B(ij,hj);ij.prototype.A=function(){return this.label};var P=function(a,b){this.label=b;this.value=a.R();this.X=a};B(P,hj);P.prototype.A=function(){return this.label};P.prototype.R=function(){return this.value};P.prototype.encode=function(){return this.X.encode()+n};P.prototype.L=function(){return new jj(this)};var Q=function(){};B(Q,hj);Q.prototype.encode=function(){return encodeURIComponent(this.R())};Q.prototype.L=function(){return null};var kj=function(a){P.call(this,a,a.A())};B(kj,P);var lj=function(){};B(lj,Q);lj.prototype.A=function(){return Bb};lj.prototype.R=function(){return xb};lj.prototype.decode=function(){return new kj(this)};var mj=function(a,b){this.mb=this.Nc=this.Da=e;this.Ib=null;this.qb=this.ie=e;this.G=this.xg=!1;var c;a instanceof mj?(this.G=w(b)?b:a.G,this.Ae(a.Da),this.Ee(a.Nc),this.ue(a.mb),this.ye(a.Ib),this.setPath(a.getPath()),this.ze(a.fa.clone()),this.we(a.qb)):a&&(c=String(a).match(Wi))?(this.G=!!b,this.Ae(c[1]||e,!0),this.Ee(c[2]||e,!0),this.ue(c[3]||e,!0),this.ye(c[4]),this.setPath(c[5]||e,!0),this.ze(c[6]||e,!0),this.we(c[7]||e,!0)):(this.G=!!b,this.fa=new nj(null,null,this.G))};u=mj.prototype;
u.toString=function(){var a=[],b=this.Da;b&&a.push(oj(b,pj,!0),mb);var c=this.mb;if(c||b==le)a.push(Wa),(b=this.Nc)&&a.push(oj(b,pj,!0),ub),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,pa)),c=this.Ib,null!=c&&a.push(mb,String(c));if(c=this.getPath())this.mg()&&c.charAt(0)!=Va&&a.push(Va),a.push(oj(c,c.charAt(0)==Va?qj:rj,!0));(c=this.Vf())&&a.push(sb,c);(c=this.qb)&&a.push(la,oj(c,sj));return a.join(e)};u.clone=function(){return new mj(this)};
u.Ae=function(a,b){this.da();if(this.Da=b?tj(a,!0):a)this.Da=this.Da.replace(/:$/,e);return this};u.Ee=function(a,b){this.da();this.Nc=b?tj(a):a;return this};u.ue=function(a,b){this.da();this.mb=b?tj(a,!0):a;return this};u.mg=function(){return!!this.mb};u.ye=function(a){this.da();if(a){a=Number(a);if(isNaN(a)||0>a)throw Error("Bad port number "+a);this.Ib=a}else this.Ib=null;return this};u.getPath=function(){return this.ie};u.setPath=function(a,b){this.da();this.ie=b?tj(a,!0):a;return this};
u.ze=function(a,b){this.da();a instanceof nj?(this.fa=a,this.fa.Gc(this.G)):(b||(a=oj(a,uj)),this.fa=new nj(a,null,this.G));return this};u.Vf=function(){return this.fa.toString()};u.Mb=function(a,b){this.da();this.fa.set(a,b);return this};u.we=function(a,b){this.da();this.qb=b?tj(a):a;return this};u.da=function(){if(this.xg)throw Error("Tried to modify a read-only Uri");};u.Gc=function(a){this.G=a;this.fa&&this.fa.Gc(a);return this};
var tj=function(a,b){return a?b?decodeURI(a.replace(/%25/g,qa)):decodeURIComponent(a):e},oj=function(a,b,c){return z(a)?(a=encodeURI(a).replace(b,vj),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,pa)),a):null},vj=function(a){a=a.charCodeAt(0);return oa+(a>>4&15).toString(16)+(a&15).toString(16)},pj=/[#\/\?@]/g,rj=/[\#\?:]/g,qj=/[\#\?]/g,uj=/[\#\?@]/g,sj=/#/g,nj=function(a,b,c){this.b=this.g=null;this.ca=a||null;this.G=!!c};u=nj.prototype;
u.U=function(){if(!this.g&&(this.g=new Pi,this.b=0,this.ca)){var a=this;Xi(this.ca,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g,h)),c)})}};u.s=function(){this.U();return this.b};u.add=function(a,b){this.U();this.ya();a=this.va(a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.b=D(this.b)+1;return this};u.remove=function(a){this.U();a=this.va(a);return this.g.ka(a)?(this.ya(),this.b=D(this.b)-this.g.get(a).length,this.g.remove(a)):!1};
u.clear=function(){this.ya();this.g=null;this.b=0};u.isEmpty=function(){this.U();return 0==this.b};u.ka=function(a){this.U();a=this.va(a);return this.g.ka(a)};u.K=function(){this.U();for(var a=this.g.u(),b=this.g.K(),c=[],d=0;d<b.length;d++)for(var f=a[d],g=0;g<f.length;g++)c.push(b[d]);return c};u.u=function(a){this.U();var b=[];if(z(a))this.ka(a)&&(b=Ah(b,this.g.get(this.va(a))));else{a=this.g.u();for(var c=0;c<a.length;c++)b=Ah(b,a[c])}return b};
u.set=function(a,b){this.U();this.ya();a=this.va(a);this.ka(a)&&(this.b=D(this.b)-this.g.get(a).length);this.g.set(a,[b]);this.b=D(this.b)+1;return this};u.get=function(a,b){var c=a?this.u(a):[];return 0<c.length?String(c[0]):b};u.setValues=function(a,b){this.remove(a);0<b.length&&(this.ya(),this.g.set(this.va(a),Bh(b)),this.b=D(this.b)+b.length)};
u.toString=function(){if(this.ca)return this.ca;if(!this.g)return e;for(var a=[],b=this.g.K(),c=0;c<b.length;c++)for(var d=b[c],f=encodeURIComponent(String(d)),d=this.u(d),g=0;g<d.length;g++){var k=f;d[g]!==e&&(k+=n+encodeURIComponent(String(d[g])));a.push(k)}return this.ca=a.join(l)};u.ya=function(){this.ca=null};u.clone=function(){var a=new nj;a.ca=this.ca;this.g&&(a.g=this.g.clone(),a.b=this.b);return a};u.va=function(a){a=String(a);this.G&&(a=a.toLowerCase());return a};
u.Gc=function(a){a&&!this.G&&(this.U(),this.ya(),this.g.forEach(function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.setValues(d,a))},this));this.G=a};var wj=e;var xj=function(a){if(a.classList)return a.classList;a=a.className;return z(a)&&a.match(/\S+/g)||[]},yj=function(a,b){return a.classList?a.classList.contains(b):E(xj(a),b)},zj=function(a,b){a.classList?a.classList.add(b):yj(a,b)||(a.className+=0<a.className.length?h+b:b)},Aj=function(a,b){a.classList?a.classList.remove(b):yj(a,b)&&(a.className=uh(xj(a),function(a){return a!=b}).join(h))};var Bj=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=Rh&&!b&&!c;if((!w(b)||d)&&a.getBoundingClientRect){var f;a:{try{f=a.getBoundingClientRect()}catch(g){f={left:0,top:0,right:0,bottom:0};break a}G&&a.ownerDocument.body&&(a=a.ownerDocument,f.left-=a.documentElement.clientLeft+a.body.clientLeft,f.top-=a.documentElement.clientTop+a.body.clientTop)}return new Nh(f.right-f.left,f.bottom-f.top)}return new Nh(b,c)},Cj=function(a,b){var c=di(b),d=null,d=c.ta;if(G&&d.createStyleSheet)c=d=d.createStyleSheet(),
G&&w(c.cssText)?c.cssText=a:c.innerHTML=a;else{var f=c.zd(Rb)[0];f||(d=c.zd(Db)[0],f=c.dc(Rb),d.parentNode.insertBefore(f,d));var g=d=c.dc(oc);G&&w(g.cssText)?g.cssText=a:g.innerHTML=a;c.appendChild(f,d)}return d};/*

 CC0 1.0 Universal License
 Public Domain Dedication

 The person(s) who associated a work with this deed has dedicated the work to
 the public domain by waiving all of his or her rights to the work worldwide
 under copyright law, including all related and neighboring rights, to the
 extent allowed by law.

 You can copy, modify, distribute and perform the work, even for commercial
 purposes, all without asking permission.

 In no way are the patent or trademark rights of any person affected by CC0,
 nor are the rights that other persons may have in the work or in how the work
 is used, such as publicity or privacy rights.

 Unless expressly stated otherwise, the person(s) who associated a work with
 this deed makes no warranties about the work, and disclaims liability for all
 uses of the work, to the fullest extent permitted by applicable law.

 When using or citing the work, you should not imply endorsement by the author
 or the affirmer.

 This is a human-readable summary of the Legal Code (read the full text).
*/
var Dj=function(a){function b(a,b){if(b){var c=document.createDocumentFragment(),k=!a.getAttribute(zg)&&b.getAttribute(zg);k&&a.setAttribute(zg,k);for(k=b.cloneNode(!0);k.childNodes.length;)c.appendChild(k.firstChild);a.appendChild(c)}}function c(a){a.onreadystatechange=function(){if(4===a.readyState){var c=a.uf;c||(c=a.uf=document.implementation.createHTMLDocument(e),c.body.innerHTML=a.responseText,a.$c={});a.ad.splice(0).map(function(g){var k=a.$c[g.id];k||(k=a.$c[g.id]=c.getElementById(g.id));
b(g.qh,k)})}};a.onreadystatechange()}(function(a){function f(){for(var a=0;a<X.length;){var d=X[a],m=d.parentNode;if(m&&/svg/i.test(m.nodeName)){var r=d.getAttribute(Lg);if(g&&(!k.th||k.th(r,m,d)))if(m.removeChild(d),r=r.split(la),d=r.shift(),r=r.join(la),d.length){var fa=sa[d];fa||(fa=sa[d]=new XMLHttpRequest,fa.open(Ob,d),fa.send(),fa.ad=[]);fa.ad.push({qh:m,id:r});c(fa)}else b(m,document.getElementById(r))}else++a}window.requestAnimationFrame&&window.requestAnimationFrame(f)||setTimeout(f,67)}
var g,k=Object(a);a=/\bTrident\/[567]\b|\bMSIE (?:9|10)\.0\b/;var m=/\bAppleWebKit\/(\d+)\b/,r=/\bEdge\/12\.(\d+)\b/;g=Ff in k?k.oj:a.test(navigator.userAgent)||10547>(navigator.userAgent.match(r)||[])[1]||537>(navigator.userAgent.match(m)||[])[1];var sa={},X=document.getElementsByTagName(vg);g&&f()})(a)};var Ej=function(a){return/^[A-Za-z0-9]+$/.test(a)||/^#[0-9A-Fa-f]{3}$/.test(a)||/^#[0-9A-Fa-f]{6}$/.test(a)||/^rgb *\( *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *\)$/.test(a)||/^rgba *\( *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *\)$/.test(a)},Fj=function(a){a=a.split(Ka);for(var b=0;b<a.length;b++){var c=a[b],c=eh(c);if(!(/^[- A-Za-z0-9]*$/.test(c)||/^"[- A-Za-z0-9]*"$/.test(c)||/^'[- A-Za-z0-9]*'$/.test(c)))return!1}return!0},Gj=function(){if(window.parent&&window.parent.postMessage){var a=
document.getElementById(If),b=0;if(a){b:{b=ci(a);if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,null))){b=b.display||b.getPropertyValue(Qd)||e;break b}b=e}if((b||(a.currentStyle?a.currentStyle.display:null)||a.style&&a.style.display)!=t)a=Bj(a);else{var b=a.style,c=b.display,d=b.visibility,f=b.position;b.visibility=ye;b.position=Vc;b.display=Re;a=Bj(a);b.display=c;b.position=f;b.visibility=d}b=a.height}b=Math.max(b,document.body.scrollHeight);window.parent.postMessage(ag+
(b||230)+Lf,Ja)}},Hj=function(){var a=document.getElementById(Dd),b=document.getElementById(Hf),c=document.getElementById(Gf),d=function(){b&&(b.disabled=a.value==e);c&&(c.disabled=a.value==e)};a&&qf in a&&(d(null),M(a,Se,d))},Ij=function(a){var b=e;G&&(b+=Sa);a=(new mj(a)).qb;if(0!=a.length){a=decodeURIComponent(a);var c=Li(a);if(c&&c.color){a=dh(ch(c.color));var d=dh(ch(c.unvisitedLinkColor)),c=dh(ch(c.fontFamily));Ej(a)&&Ej(d)&&Fj(c)&&(b=b+(rd+a+ob+c+pb)+(Tc+d+pb))}}Cj(b);setTimeout(Gj,100);var f=
I(ad);if((b=I(Dd))&&f){var g=!1;M(b,ne,function(){g||(g=!0,Aj(f,Hd),Gj())})}Dj()};var R=function(a){a=I(a);var b=a.nodeName.toLowerCase();a.style.display=b==eg||b==Pe||b==Sc||b==Se||b==Yf?Re:nd},S=function(a){I(a).style.display=t};var T=function(a,b,c){var d;c&&S($e);switch(a){case 0:a=d=ud;break;case 1:a=d=He;break;case 2:case 3:case 4:a=Xe;d=Ye;break;case 5:a=d=ef;break;case 6:a=d=sf;break;case 7:a=d=re;break;default:throw Error("internal error in show message");}c?(I(a).innerHTML=b,R(d),I(Dd).className=Cd):(ki(I(a)),S(d));Gj()},Jj=function(a){T(3,null,!1);I(Ze).innerHTML=a;R($e);Gj()};var Kj=function(){};Kj.prototype.ph=function(){S(Le);I(Dd).disabled=!0;I(Hf).disabled=!0};Kj.prototype.ng=function(){R(Le);I(Dd).disabled=!1;I(Hf).disabled=!1};var jj=function(a){this.m=a};B(jj,Kj);u=jj.prototype;u.oa=function(){return!1};u.ga=function(){if(!this.oa())throw Error("Trying to show a non-editable identity");this.ph();R(Ke)};u.Cb=function(){return!0};u.Jc=function(){if(!this.oa())throw Error("Trying to show edit button for a non-editable identity");R(Yd)};u.Va=function(){};u.Ya=function(){};u.Z=function(){S(Ke);S(Yd);S(bg);S(Ed);S(mg);this.ng()};var Lj=function(a){a=a.className;return z(a)&&a.match(/\S+/g)||[]},Mj=function(a,b){for(var c=Lj(a),d=Ch(arguments,1),f=c.length+d.length,g=c,k=0;k<d.length;k++)E(g,d[k])||g.push(d[k]);a.className=c.join(h);return c.length==f},Oj=function(a,b){var c=Lj(a),d=Ch(arguments,1),f=Nj(c,d);a.className=f.join(h);return f.length==c.length-d.length},Nj=function(a,b){return uh(a,function(a){return!E(b,a)})};var Rj=function(a){for(var b=[],c=Pj,d=a.elements,f,g=0;f=d[g];g++)if(f.form==a&&!f.disabled&&f.tagName!=Nb){var k=f.name;switch(f.type.toLowerCase()){case le:case lg:case Pf:case sd:break;case Zf:f=Qj(f);if(null!=f)for(var m,r=0;m=f[r];r++)c(b,k,m);break;default:m=Qj(f),null!=m&&c(b,k,m)}}d=a.getElementsByTagName(Sb);for(g=0;f=d[g];g++)f.form==a&&f.type.toLowerCase()==Ne&&(k=f.name,c(b,k,f.value),c(b,k+Ta,$a),c(b,k+Ua,$a));return b.join(l)},Pj=function(a,b,c){a.push(encodeURIComponent(b)+n+encodeURIComponent(c))},
Qj=function(a){var b=a.type;if(!w(b))return null;switch(b.toLowerCase()){case xd:case Mf:return a.checked?a.value:null;case $f:return b=a.selectedIndex,0<=b?a.options[b].value:null;case Zf:for(var b=[],c,d=0;c=a.options[d];d++)c.selected&&b.push(c.value);return b.length?b:null;default:return w(a.value)?a.value:null}};var Sj=!1,Tj=!1,Uj=!1,Vj=function(a,b){Tj=a;Uj=b;if(window.parent==window.top&&(a||b)){var c=I(mg);b?Mj(c,yd):Oj(c,yd);R(mg);I($c).value=b?wc:qc}else S(mg)};var Xj=function(a,b){P.call(this,new Wj,a);this.Uf=b};B(Xj,P);Xj.prototype.encode=function(){return this.X.encode()+n+this.label+n+this.Uf};Xj.prototype.A=function(){return this.label+ca};Xj.prototype.L=function(){return new Yj(this)};var Wj=function(){};B(Wj,Q);Wj.prototype.A=function(){return e};Wj.prototype.R=function(){return Fb};Wj.prototype.decode=function(a){return new Xj(a[1],a[2])};Wj.prototype.L=function(){throw Error("internal error");};var Yj=function(a){this.m=a};B(Yj,jj);
Yj.prototype.Jc=function(){(Tj||Uj)&&R(mg)};var Zj=function(a){P.call(this,a,a.A())};B(Zj,P);var ak=function(){};B(ak,Q);ak.prototype.A=function(){return Qb};ak.prototype.R=function(){return Pb};ak.prototype.decode=function(){return this.Dd()};ak.prototype.Dd=function(){return new Zj(this)};var bk=function(a,b,c){P.call(this,a,null);this.name=b;this.url=c};B(bk,P);bk.prototype.A=function(){return this.name+ba+this.url+Ia};bk.prototype.encode=function(){return this.X.encode()+n+encodeURIComponent(this.name)+n+encodeURIComponent(this.url)};bk.prototype.L=function(){return new ck(this)};var dk=function(){};B(dk,Q);dk.prototype.A=function(){return ec};dk.prototype.R=function(){return bc};dk.prototype.L=function(){return new ck(new bk(this,e,e))};
dk.prototype.decode=function(a){return new bk(this,a[1],a[2])};var ck=function(a){this.m=a};B(ck,jj);u=ck.prototype;u.oa=function(){return!0};u.ga=function(){ck.h.ga.call(this);R(ff)};u.Z=function(){ck.h.Z.call(this);S(ff);T(5,null,!1);this.xe(e);this.De(e)};u.Va=function(){this.xe(this.m.name);this.De(this.m.url)};u.Ya=function(){ck.h.Ya.call(this);this.m.name=this.Cd();this.m.url=this.fg();this.Jc()};u.Cb=function(){return this.Cd()==e?(T(5,dc,!0),!1):!0};u.Cd=function(){return I(dd).value};
u.xe=function(a){I(dd).value=a};u.fg=function(){return I(ed).value};u.De=function(a){I(ed).value=a};var ek=function(){this.ma=[];this.Ua=[];this.Ia=[];this.Pa=[];this.i=this.D=null;this.H=[]};u=ek.prototype;u.zb=function(a,b,c,d){for(var f=0;f<this.H.length;f++)if(a==this.H[f])return d(a);d=a.encode();for(f=0;f<this.H.length;f++)if(this.H[f].encode()==d)return c(this.H[f]);return b(a)};u.sg=function(a){return this.zb(a,A(function(a){return this.H[this.H.length]=a},this),Mi,Mi)};u.Bb=function(a){function b(){return!1}return this.zb(a,function(){return!0},b,b)};
u.Ra=function(a){function b(){throw Error("item should have been unique");}this.zb(a,Og,b,b);return this.sg(a)};u.$b=function(a){return this.zb(a,A(function(a){this.H[this.H.length]=a;return this.ma[this.ma.length]=a},this),Mi,Mi)};u.Zd=function(){for(var a=document.getElementById(Je),b=xj(a),c=0;c<b.length;c++)b[c].slice(0,14)==Ie&&Aj(a,b[c]);(b=this.Pa[I(Le).selectedIndex])&&zj(a,Ie+b.value)};u.dd=function(a){this.D=this.$b(a);this.Xa();this.Ha();this.gb(!1);return this.D};
u.ja=function(a){this.Ra(a);this.Ua[this.Ua.length]=a};u.yf=function(){var a=this.Ra(new ak);this.ja(a.Dd())};u.xf=function(){var a=new dk;this.Ra(a);this.Ia[this.Ia.length]=a};u.wf=function(){var a=this.Ra(new lj),a=this.Ra(new kj(a));this.Ia[this.Ia.length]=a};u.Ha=function(){var a=this.Pa[I(Le).selectedIndex];a.constructor==ij?this.Xa():(T(1,null,!1),this.i=a.L(),null!=this.i&&this.i.Va(),this.Zd())};
u.gb=function(a){if(null!=this.i){var b=this.i.m;if(a&&this.i.oa()&&this.Bb(b)||!this.i.Cb())this.i.ga();else return this.i.Ya(),this.i.Z(),this.i.oa()&&this.i.Jc(),this.i=null,b}return null};u.hh=function(){this.Lf(I($d).value);this.D=this.rd(I(ae).value);null==this.D&&0<this.ma.length&&(this.D=this.ma[0]);null==this.D&&1==this.Ua.length&&(this.D=this.Ua[0]);this.Xa();null!=this.D&&(this.Ha(),this.gb(!1))};
u.ed=function(a,b){this.Pa[this.Pa.length]=b;var c=document.createElement(Af);c.text=b.A();c.value=b.R();try{a.add(c,null)}catch(d){a.add(c)}this.D==b&&(c.selected=!0);return c};u.ac=function(a,b){for(var c=0;c<b.length;c++)this.ed(a,b[c])};u.Xa=function(){for(var a=I(Le);0!=a.options.length;)a.remove(0);this.Pa=[];this.ed(a,new ij(pc)).disabled=Pd;this.ac(a,this.ma);this.ac(a,this.Ua);this.ac(a,this.Ia)};u.Rf=function(){for(var a=[],b=0;b<this.ma.length;b++)a[a.length]=this.ma[b].encode();return a.join(l)};
u.Lf=function(a){if(a!=e){a=a.split(l);for(var b=0;b<a.length;b++)this.rd(a[b])}};u.rd=function(a){if(a==e)return null;a=a.split(n);for(var b=0;b<a.length;b++)a[b]=decodeURIComponent(a[b]);b=this.Tf(a[0]);return null!=b?(a=b.decode(a),this.$b(a)):null};u.Tf=function(a){for(var b=0;b<this.H.length;b++)if(this.H[b].encode()==a)return this.H[b];return null};u.Le=function(){var a=I(Dd).value;if(a==e)return T(2,Gb,!0),!1;if(1E6<a.length)return T(2,Hb,!0),!1;T(2,null,!1);return!0};
u.zc=function(){null!=this.i&&this.i.Z();this.Ha();var a=this.gb(!0);null!=a&&(this.D=a)};u.Og=function(){var a=this.gb(!1);null!=a&&this.dd(a)};u.Ng=function(){null!=this.i&&(this.i.Z(),this.i=null);this.Xa();this.zc()};u.he=function(){if(null==this.D||this.D.R()==cc)return T(1,lc,!0),!1;if(null!=this.i)return!1;I($d).value=this.Rf();I(ae).value=this.D.encode();return!0};u.Qg=function(){this.D&&(this.Ha(),this.i.ga())};u.Wg=function(){this.Le()&&this.he()&&this.vd(!1)};
u.Xg=function(){this.Le()&&this.he()&&this.vd(!0)};u.vd=function(a){I(cg).value=a?tg:ke;this.Ha();a=I(Fd);a.onsubmit();a.submit()};var fk=function(a,b,c,d){this.Mf=a;this.Ke=b;this.name=c;this.sh=d};B(fk,Q);u=fk.prototype;u.A=function(){return this.name};u.encode=function(){return encodeURIComponent(this.Mf)};u.Hf=function(a){return this.Ke.replace(/{username}/,encodeURIComponent(a))};u.eg=function(){return this.Ke.split(Mg)};u.L=function(){return new gk(new hk(this,e,e))};u.decode=function(a){return new hk(this,a[1],a[2])};var hk=function(a,b,c){P.call(this,a,b);this.username=c;this.uri=b;this.value=ic};B(hk,P);
hk.prototype.A=function(){return this.username+ba+this.X.A()+Ia};hk.prototype.encode=function(){return this.X.encode()+n+encodeURIComponent(this.uri)+n+encodeURIComponent(this.username)};hk.prototype.L=function(){return new gk(this)};var gk=function(a){this.m=a};B(gk,jj);u=gk.prototype;u.oa=function(){return!0};u.ga=function(){gk.h.ga.call(this);R(tf);I(zf).innerHTML=this.m.X.sh;for(var a=I(yf),b=A(function(){this.ke()},this),c=[wd,Ue,Te,Ve,qd,ne],d=0;d<c.length;d++)M(a,c[d],b)};
u.Z=function(){gk.h.Z.call(this);Hi(I(yf));S(tf);T(6,null,!1);I(xf).value=e};u.Va=function(){this.oh(this.m.username);I(xf).value=this.m.X.Hf(this.m.username)};u.Ya=function(){this.m.username=this.jc();this.Va()};u.Cb=function(){return this.jc()==e?(T(6,tc,!0),!1):!0};u.ke=function(){var a=this.m.X.eg(),b=this.jc(),b=b==e?wg:encodeURIComponent(b);I(uf).innerHTML=a[0];I(wf).innerHTML=b;I(vf).innerHTML=a[1]};u.jc=function(){return I(yf).value};u.oh=function(a){I(yf).value=a;this.ke()};var ik=function(){};
B(ik,Q);ik.prototype.A=function(){return jc};ik.prototype.R=function(){return ic};ik.prototype.decode=function(a){return new jk(this,a[1])};ik.prototype.L=function(){return new kk(new jk(this,e))};var jk=function(a,b){P.call(this,a,b);this.uri=b;this.value=ic};B(jk,P);jk.prototype.A=function(){return this.uri};jk.prototype.encode=function(){return this.X.encode()+n+encodeURIComponent(this.uri)};jk.prototype.L=function(){return new kk(this)};var kk=function(a){this.m=a};B(kk,jj);u=kk.prototype;
u.oa=function(){return!0};u.ga=function(){kk.h.ga.call(this);R(se)};u.Z=function(){kk.h.Z.call(this);S(se);T(7,null,!1);this.Ce(e)};u.Va=function(){this.Ce(this.m.uri)};u.Ya=function(){this.m.uri=this.Hd()};u.Cb=function(){return this.Hd()==e?(T(7,sc,!0),!1):!0};u.Hd=function(){return I(xf).value};u.Ce=function(a){I(xf).value=a};var lk=function(){Oj(I(ad),Jf);return!0};var mk=function(a,b,c){J.call(this);this.vc=a;this.ug=b||0;this.wa=c;this.Df=A(this.Of,this)};B(mk,J);u=mk.prototype;u.Na=0;u.l=function(){mk.h.l.call(this);this.stop();delete this.vc;delete this.wa};u.start=function(a){this.stop();this.Na=Vi(this.Df,w(a)?a:this.ug)};u.stop=function(){this.Ab()&&v.clearTimeout(this.Na);this.Na=0};u.Ab=function(){return 0!=this.Na};u.Of=function(){this.Na=0;this.vc&&this.vc.call(this.wa)};var nk={},ok=null,pk=function(a){a=a[Vg]||(a[Vg]=++Wg);delete nk[a];Ih(nk)&&ok&&ok.stop()},rk=function(){ok||(ok=new mk(function(){qk(Zg())},20));var a=ok;a.Ab()||a.start()},qk=function(a){Dh(nk,function(b){b.Lg(a)});Ih(nk)||rk()};var sk=function(){N.call(this);this.Ea=0;this.endTime=this.startTime=null};B(sk,N);u=sk.prototype;u.nh=function(){this.Ea=1};u.Be=function(){this.Ea=0};u.Qd=function(){return 1==this.Ea};u.Pd=function(){return-1==this.Ea};u.Rd=function(){return 0==this.Ea};u.Mg=function(){this.S(kd)};u.de=function(){this.S(be)};u.Sg=function(){this.S(me)};u.Vg=function(){this.S(Ef)};u.Zg=function(){this.S(Sf)};u.$g=function(){this.S(ig)};u.S=function(a){this.dispatchEvent(a)};var tk=function(a,b,c,d){sk.call(this);if(!y(a)||!y(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.$a=a;this.Sf=b;this.duration=c;this.cd=d;this.coords=[];this.progress=0;this.sc=null};B(tk,sk);u=tk.prototype;
u.play=function(a){if(a||this.Rd())this.progress=0,this.coords=this.$a;else if(this.Qd())return!1;pk(this);this.startTime=a=Zg();this.Pd()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.sc=this.startTime;this.progress||this.Mg();this.Vg();this.Pd()&&this.Zg();this.nh();var b=this[Vg]||(this[Vg]=++Wg);b in nk||(nk[b]=this);rk();this.qd(a);return!0};u.stop=function(a){pk(this);this.Be();a&&(this.progress=1);this.Je(this.progress);this.$g();this.de()};
u.l=function(){this.Rd()||this.stop(!1);this.Pg();tk.h.l.call(this)};u.Lg=function(a){this.qd(a)};u.qd=function(a){D(this.startTime);D(this.endTime);D(this.sc);this.progress=(a-this.startTime)/(this.endTime-this.startTime);1<=this.progress&&(this.progress=1);this.sc=a;this.Je(this.progress);1==this.progress?(this.Be(),pk(this),this.Sg(),this.de()):this.Qd()&&this.Ig()};
u.Je=function(a){Tg(this.cd)&&(a=this.cd(a));this.coords=Array(this.$a.length);for(var b=0;b<this.$a.length;b++)this.coords[b]=(this.Sf[b]-this.$a[b])*a+this.$a[b]};u.Ig=function(){this.S(cd)};u.Pg=function(){this.S(Od)};u.S=function(a){this.dispatchEvent(new uk(a,this))};var uk=function(a,b){K.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.state=b.Ea};B(uk,K);var vk,wk={vh:"activedescendant",Ah:"atomic",Bh:"autocomplete",Ch:"busy",Eh:yd,Jh:"controls",Mh:"describedby",Ph:Pd,Rh:"dropeffect",Sh:ie,Th:"flowto",Uh:"grabbed",Yh:"haspopup",HIDDEN:ye,ai:"invalid",bi:"label",ci:"labelledby",di:"level",ii:"live",ti:"multiline",ui:"multiselectable",zi:"orientation",Ai:"owns",Bi:"posinset",Di:"pressed",Hi:"readonly",Ji:"relevant",Ki:"required",Qi:"selected",Si:"setsize",Ui:"sort",ij:"valuemax",jj:"valuemin",kj:"valuenow",lj:"valuetext"};var xk={wh:"alert",xh:"alertdialog",yh:"application",zh:"article",BANNER:"banner",BUTTON:sd,Dh:xd,Fh:"columnheader",Gh:"combobox",Hh:"complementary",Ih:"contentinfo",Lh:"definition",Nh:"dialog",Oh:"directory",Qh:"document",FORM:pe,Vh:"grid",Wh:"gridcell",Xh:"group",Zh:"heading",$h:Pe,ei:"link",fi:"list",gi:"listbox",hi:"listitem",ji:"log",ki:"main",li:"marquee",mi:"math",ni:"menu",oi:"menubar",pi:"menuitem",ri:"menuitemcheckbox",si:"menuitemradio",wi:"navigation",xi:"note",yi:Af,Ci:"presentation",
Ei:"progressbar",Fi:Mf,Gi:"radiogroup",Ii:"region",Li:"row",Mi:"rowgroup",Ni:"rowheader",Oi:"scrollbar",Pi:"search",Ri:"separator",Ti:"slider",Vi:"spinbutton",Wi:"status",Yi:og,Zi:"tablist",$i:"tabpanel",aj:"textbox",bj:"textinfo",cj:"timer",dj:"toolbar",ej:"tooltip",fj:"tree",gj:"treegrid",hj:"treeitem"};var yk=function(a){J.call(this);this.wa=a;this.c={}};B(yk,J);var zk=[];u=yk.prototype;u.Aa=function(a,b,c,d){return this.zg(a,b,c,d)};u.zg=function(a,b,c,d,f){y(b)||(b&&(zk[0]=b.toString()),b=zk);for(var g=0;g<b.length;g++){var k=M(a,b[g],c||this.handleEvent,d||!1,f||this.wa||this);if(!k)break;this.c[k.key]=k}return this};u.uc=function(a,b,c,d){return this.Yd(a,b,c,d)};
u.Yd=function(a,b,c,d,f){if(y(b))for(var g=0;g<b.length;g++)this.Yd(a,b[g],c,d,f);else{a=Ei(a,b,c||this.handleEvent,d,f||this.wa||this);if(!a)return this;this.c[a.key]=a}return this};u.Ob=function(a,b,c,d,f){if(y(b))for(var g=0;g<b.length;g++)this.Ob(a,b[g],c,d,f);else c=c||this.handleEvent,f=f||this.wa||this,c=yi(c),d=!!d,b=qi(a)?a.Ma(b,c,d,f):a?(a=Ai(a))?a.Ma(b,c,d,f):null:null,b&&(Gi(b),delete this.c[b.key]);return this};
u.Jb=function(){Dh(this.c,function(a,b){this.c.hasOwnProperty(b)&&Gi(a)},this);this.c={}};u.l=function(){yk.h.l.call(this);this.Jb()};u.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var Ak=function(a,b,c,d,f){function g(a){a&&(a.tabIndex=0,C(Hh(xk,og),gc),a.setAttribute(Tf,og),zj(a,we),k.Qf(a),k.Pf(a))}N.call(this);this.hc=f||di();this.ba=this.hc.rb(a)||null;this.Ka=this.hc.rb(d||null);this.T=(this.Eb=Tg(b)?b:null)||!b?null:this.hc.rb(b);this.W=1==c;w(c)||this.Eb||(this.Ka?this.W=this.Ka.style.display!=t:this.ba&&(this.W=yj(this.ba,ve)));this.Xd=new yk(this);this.be=new yk(this);var k=this;g(this.ba);g(this.Ka);this.Lb(this.W)};B(Ak,N);u=Ak.prototype;
u.l=function(){Ak.h.l.call(this);li(this.Xd);li(this.be)};u.collapse=function(){this.Lb(!1)};u.toggle=function(){this.Lb(!this.W)};u.Lb=function(a){this.T?this.T.style.display=a?e:t:a&&this.Eb&&(this.T=this.Eb());this.T&&zj(this.T,ue);this.Ka?(this.ba.style.display=a?t:e,this.Ka.style.display=a?e:t):this.Kc(a);this.ve(a);this.dispatchEvent(new Bk(sg,this,this.W))};u.ve=function(a){this.W=a};
u.Kc=function(a){if(this.ba){var b=this.ba;a?zj(b,ve):Aj(b,ve);b=this.ba;a?Aj(b,te):zj(b,te);b=this.ba;y(a)&&(a=a.join(h));C(ie,yb);C(Hh(wk,ie),fc);a===e||void 0==a?(vk||(vk={atomic:!1,autocomplete:t,dropeffect:t,haspopup:!1,live:of,multiline:!1,multiselectable:!1,orientation:yg,readonly:!1,relevant:Yc,required:!1,sort:t,busy:!1,disabled:!1,hidden:!1,invalid:ke}),a=vk,ie in a?b.setAttribute(hd,a.expanded):b.removeAttribute(hd)):b.setAttribute(hd,a)}};u.Pf=function(a){a&&this.Xd.Aa(a,Te,this.Ug)};
u.Qf=function(a){a&&this.be.Aa(a,Bd,this.Tg)};u.Ug=function(a){if(13==a.keyCode||32==a.keyCode)this.toggle(),this.td(),a.preventDefault(),a.stopPropagation()};u.Tg=function(){this.toggle();this.td()};u.td=function(){this.dispatchEvent(new K(Wc,this))};var Bk=function(a,b){K.call(this,a,b)};B(Bk,K);var Ck=function(a,b,c,d){d=d||di();var f=d.dc(Jb,{style:Bf});b=d.rb(b);b.parentNode.replaceChild(f,b);f.appendChild(b);this.nb=f;this.O=null;Ak.call(this,a,b,c,void 0,d);a=this.W;this.nb.style.display=a?e:t;this.Kc(a)};B(Ck,Ak);u=Ck.prototype;u.Bf=500;u.Af=function(a){return 1-Math.pow(1-a,3)};
u.Lb=function(a){if(this.W!=a||this.O){this.nb.style.display==t&&(this.nb.style.display=e);var b=this.T.offsetHeight,c=0;this.O?(a=this.W,Hi(this.O),this.O.stop(!1),c=b-Math.abs(parseInt(this.T.style.marginTop,10))):c=a?0:b;this.Kc(a);this.O=new tk([0,c],[0,a?b:0],this.Bf,this.Af);M(this.O,[kd,cd,be],this.Jg,!1,this);M(this.O,be,A(this.Kg,this,a));this.O.play(!1)}};u.Jg=function(a){var b=this.T;b.style.marginTop=a.y-b.offsetHeight+Lf};
u.Kg=function(a){a&&(this.T.style.marginTop=$a);Hi(this.O);this.ve(a);this.O=null;a||(this.nb.style.display=t);this.dispatchEvent(new Bk(sg,this,a))};var Dk=null;var U=new ek;x("BLOG_CMT_OpenIdIdentityFactory",fk,void 0);x("BLOG_CMT_LoggedInGaiaIdentity",Xj,void 0);x("BLOG_CMT_NotLoggedInGaiaIdentityFactory",ak,void 0);x("BLOG_CMT_GenericOpenIdIdentityFactory",ik,void 0);x("BLOG_CMT_NameUrlIdentityFactory",dk,void 0);x("BLOG_CMT_AnonymousIdentityFactory",lj,void 0);x("BLOG_CMT_onPost",function(){lk();return U.Wg()},void 0);x("BLOG_CMT_onPreview",function(){return U.Xg()},void 0);x("BLOG_CMT_onCommentBodyChange",function(){},void 0);
x("BLOG_CMT_onCancel",function(){return U.Ng()},void 0);x("BLOG_CMT_onSelectorChange",function(){return U.zc()},void 0);x("BLOG_CMT_onContinue",function(){return U.Og()},void 0);x("BLOG_CMT_onEdit",function(){return U.Qg()},void 0);x("BLOG_CMT_addIdentity",function(a){return U.$b(a)},void 0);x("BLOG_CMT_addAndSelectIdentity",function(a){return U.dd(a)},void 0);x("BLOG_CMT_addIdentityFactory",function(a){return U.ja(a)},void 0);x("BLOG_CMT_addNameUrlIdentityFactory",function(){return U.xf()},void 0);
x("BLOG_CMT_addAnonIdentity",function(){return U.wf()},void 0);x("BLOG_CMT_addNotLoggedInGaiaIdentity",function(){return U.yf()},void 0);x("BLOG_CMT_init",function(a,b){Ij(document.location.href);U.hh();U.zc();U.Zd();Vj(a,b);I(cg).value==tg&&(I(cg).value=ke,Mj(I(ad),Jf));Hj();return!0},void 0);x("BLOG_CMT_addOpenIdIdentityFactories",function(){U.ja(new fk(Tb,De,Vb,Wb));U.ja(new fk(xc,Ee,yc,zc));U.ja(new fk(rc,Fe,uc,vc));U.ja(new fk(vb,Ce,vb,wb));U.ja(new ik)},void 0);
x("BLOG_CMT_createPhotoZippy",function(a,b){I(a)&&I(b)&&(Dk=new Ck(a,b))},void 0);x("BLOG_CMT_closePhotoZippy",function(){null!=Dk&&Dk.collapse()},void 0);x("BLOG_CMT_finalizeBG",function(){window.jd&&window.jd.invoke(function(a){document.getElementById(md).value=a})},void 0);
x("BLOG_CMT_getBG",function(){var a=new mj(Ya),b=document.getElementById(md).value;b&&a.Mb(md,b);b=null;window.navigator.appName==$b&&(document.documentMode?b=document.documentMode:(b=5,document.compatMode&&document.compatMode==Eb&&(b=7)));b&&a.Mb(Me,b);document.getElementById(Df)&&a.Mb(Cf,ab);wj&&a.Mb(ld,wj);dj(a,function(){if(this.Sa()){var a=eval(this.ag());a instanceof Object&&a.length&&(1<a.length&&(eval(a[1]),wj=a[2]),window.jd=new botguard.bg(a[0]))}})},void 0);
x("BLOG_CMT_setBG",function(a){wj=a},void 0);x("BLOG_CMT_subscription.toggle",function(){if(!Sj){Sj=!0;var a=I(Gd);dj(a.action,function(){Sj=!1;if(this.Sa()){var a=this.Gd();null!=a.errorMessage?T(3,a.errorMessage,!0):Jj(a.statusMessage);Vj(a.can_subscribe,a.is_subscribed)}else T(3,zb,!0)},kc,Rj(a))}},void 0);x("BLOG_CMT_showStatusMessage",Jj,void 0);x("BLOG_CMT_showPostErrorMessage",function(a){T(4,a,!0)},void 0);x("BLOG_CMT_hidePreview",function(){lk();U.Xa();Gj()},void 0);x("BLOG_xhr",O,void 0);
O.send=dj;O.prototype.isSuccess=O.prototype.Sa;O.prototype.getResponseJson=O.prototype.Gd;x("$",I,void 0);function Ek(a){return function(b){var c=-1;try{c=b.status}catch(d){}return 500<=c?(b.responseText.length?document.body.innerHTML=b.responseText:window.alert(LayoutsMessages.SERVER_ERROR),!1):a?a(b):!0}};var Gk=function(a,b,c){var d=a.ownerDocument;a=Fk(d,a,Vd,Cg);a=Fk(d,a,Vd,Dg);a=Fk(d,a,Vd,Eg);a=Fk(d,a,Vd,Bg);var f=Fk(d,a,Vd,We);b=b._GetHelper();var g=b._GetData();f.appendChild(d.createTextNode(g[We]));a=Fk(d,a,Sc,Zd);var k=b._GenerateWidgetMetadata();a.setAttribute(ze,k.quickEditUrl);a.target=zd;a.onclick=function(){return c._PopupConfig(d.getElementById(k.instanceId))};a.appendChild(d.createTextNode(g[Xd]))},Fk=function(a,b,c,d){a=a.createElement(c);a.className=d;b.appendChild(a);return a};var Hk=function(){this.dh={};this.ae={};this.Cc={};this.Lc=null;this.je=[]};Pg(Hk);Hk.prototype.Bd=function(a,b){return a+Fc+b+Qa};var Ik=function(a){eval(a)};Hk.prototype.Md=function(a,b){x(Hc,Ik,void 0);this.Lc=a.replace(/\.js$/,e);b&&(this.Bd=b);th(this.je,function(a){this.Bg(a)},this);xh(this.je)};Hk.prototype.fh=function(a,b,c){var d=this.ae,f=this.dh;d[a]||(d[a]={});if(c)d[a][b]=c;else if(f[a]){for(b=0;b<f[a].length;++b)(0,f[a][b][1])(d[a][f[a][b][0]]);delete f[a];delete this.Cc[a]}};
Hk.prototype.Bg=function(a){Vi(function(){if(!this.ae[a]){qh(this.Lc);var b=this.Bd(this.Lc,a),c=Hh(this.Cc,b);this.Cc[a]=b;c||(b=hi(nc,{type:qg,src:b}),document.body.appendChild(b))}},0,this)};var Jk=function(){this.J=[];this.P=[]};u=Jk.prototype;u.Cg=function(){0==this.J.length&&(this.J=this.P,this.J.reverse(),this.P=[])};u.enqueue=function(a){this.P.push(a)};u.dequeue=function(){this.Cg();return this.J.pop()};u.s=function(){return this.J.length+this.P.length};u.isEmpty=function(){return 0==this.J.length&&0==this.P.length};u.clear=function(){this.J=[];this.P=[]};u.contains=function(a){return E(this.J,a)||E(this.P,a)};
u.remove=function(a){var b;b=this.J;var c=sh(b,a);0<=c?(yh(b,c),b=!0):b=!1;return b||zh(this.P,a)};u.u=function(){for(var a=[],b=this.J.length-1;0<=b;--b)a.push(this.J[b]);for(var c=this.P.length,b=0;b<c;++b)a.push(this.P[b]);return a};var Kk=function(a,b){J.call(this);this.$d=a||0;this.Gb=b||10;if(this.$d>this.Gb)throw Error("[goog.structs.Pool] Min can not be greater than max");this.Y=new Jk;this.ea=new Ti;this.delay=0;this.rc=null;this.fb()};B(Kk,J);u=Kk.prototype;u.sb=function(){var a=Zg();if(!(null!=this.rc&&a-this.rc<this.delay)){var b=this.gh();b&&(this.rc=a,this.ea.add(b));return b}};u.Fc=function(a){return this.ea.remove(a)?(this.Zb(a),!0):!1};
u.gh=function(){for(var a;0<this.Ad()&&(a=this.Y.dequeue(),!this.yc(a));)this.fb();!a&&this.s()<this.Gb&&(a=this.ec());return a};u.Zb=function(a){this.ea.remove(a);this.yc(a)&&this.s()<this.Gb?this.Y.enqueue(a):this.gc(a)};u.fb=function(){for(var a=this.Y;this.s()<this.$d;)a.enqueue(this.ec());for(;this.s()>this.Gb&&0<this.Ad();)this.gc(a.dequeue())};u.ec=function(){return{}};u.gc=function(a){if(typeof a.la==q)a.la();else for(var b in a)a[b]=null};u.yc=function(a){return typeof a.Ef==q?a.Ef():!0};
u.contains=function(a){return this.Y.contains(a)||this.ea.contains(a)};u.s=function(){return this.Y.s()+this.ea.s()};u.Wf=function(){return this.ea.s()};u.Ad=function(){return this.Y.s()};u.isEmpty=function(){return this.Y.isEmpty()&&this.ea.isEmpty()};u.l=function(){Kk.h.l.call(this);if(0<this.Wf())throw Error("[goog.structs.Pool] Objects not released");delete this.ea;for(var a=this.Y;!a.isEmpty();)this.gc(a.dequeue());delete this.Y};var Lk=function(a,b){this.Wd=a;this.Pc=b};Lk.prototype.getKey=function(){return this.Wd};Lk.prototype.clone=function(){return new Lk(this.Wd,this.Pc)};var Mk=function(a){this.M=[];a&&this.rg(a)};u=Mk.prototype;u.Nd=function(a,b){var c=this.M;c.push(new Lk(a,b));this.Hg(c.length-1)};u.rg=function(a){var b,c;if(a instanceof Mk){if(b=a.K(),c=a.u(),0>=a.s()){a=this.M;for(var d=0;d<b.length;d++)a.push(new Lk(b[d],c[d]));return}}else b=Fh(a),c=Eh(a);for(d=0;d<b.length;d++)this.Nd(b[d],c[d])};u.remove=function(){var a=this.M,b=a.length,c=a[0];if(!(0>=b))return 1==b?xh(a):(a[0]=a.pop(),this.Eg(0)),c.Pc};
u.Eg=function(a){for(var b=this.M,c=b.length,d=b[a];a<c>>1;){var f=this.Zf(a),g=this.dg(a),f=g<c&&b[g].getKey()<b[f].getKey()?g:f;if(b[f].getKey()>d.getKey())break;b[a]=b[f];a=f}b[a]=d};u.Hg=function(a){for(var b=this.M,c=b[a];0<a;){var d=this.$f(a);if(b[d].getKey()>c.getKey())b[a]=b[d],a=d;else break}b[a]=c};u.Zf=function(a){return 2*a+1};u.dg=function(a){return 2*a+2};u.$f=function(a){return a-1>>1};u.u=function(){for(var a=this.M,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].Pc);return b};
u.K=function(){for(var a=this.M,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].getKey());return b};u.ka=function(a){return vh(this.M,function(b){return b.getKey()==a})};u.clone=function(){return new Mk(this)};u.s=function(){return this.M.length};u.isEmpty=function(){return 0==this.M.length};u.clear=function(){xh(this.M)};var Nk=function(){Mk.call(this)};B(Nk,Mk);Nk.prototype.enqueue=function(a,b){this.Nd(a,b)};Nk.prototype.dequeue=function(){return this.remove()};var V=function(a,b){this.sd=void 0;this.Kb=new Nk;Kk.call(this,a,b)};B(V,Kk);u=V.prototype;u.sb=function(a,b){if(!a){var c=V.h.sb.call(this);c&&this.delay&&(this.sd=v.setTimeout(A(this.ub,this),this.delay));return c}this.Kb.enqueue(w(b)?b:100,a);this.ub()};u.ub=function(){for(var a=this.Kb;0<a.s();){var b=this.sb();if(b)a.dequeue().apply(this,[b]);else break}};u.Zb=function(a){V.h.Zb.call(this,a);this.ub()};u.fb=function(){V.h.fb.call(this);this.ub()};
u.l=function(){V.h.l.call(this);v.clearTimeout(this.sd);this.Kb.clear();this.Kb=null};var Ok=function(a,b,c,d){this.mc=a;this.Fa=!!d;V.call(this,b,c)};B(Ok,V);Ok.prototype.ec=function(){var a=new O,b=this.mc;b&&b.forEach(function(b,d){a.headers.set(d,b)});this.Fa&&a.Ic(!0);return a};Ok.prototype.yc=function(a){return!a.sa&&!a.Ab()};var Pk=function(a,b,c,d,f,g){N.call(this);this.xc=w(a)?a:1;this.qa=w(f)?Math.max(0,f):0;this.Ga=new Ok(b,c,d,g);this.N=new Pi;this.ob=new yk(this)};B(Pk,N);var Qk=[Nf,p,ng,ce,Uc,rg];u=Pk.prototype;u.Hc=function(a){this.qa=Math.max(0,a)};u.send=function(a,b,c,d,f,g,k,m,r,sa){if(this.N.get(a))throw Error("[goog.net.XhrManager] ID in use");b=new Rk(b,A(this.kg,this,a),c,d,f,k,w(m)?m:this.xc,r,sa);this.N.set(a,b);a=A(this.hg,this,a);this.Ga.sb(a,g);return b};
u.abort=function(a,b){var c=this.N.get(a);if(c){var d=c.Qb;c.jh(!0);b&&(d&&(this.ne(d,c.Qc),Ei(d,Nf,function(){this.Ga.Fc(d)},!1,this)),this.N.remove(a));d&&d.abort()}};u.hg=function(a,b){var c=this.N.get(a);c&&!c.Qb?(this.zf(b,c.Qc),b.Hc(this.qa),b.mh(c.Ca),b.Ic(c.Fa),c.Qb=b,this.dispatchEvent(new Sk(Nf,this,a,b)),this.pe(a,b),c.bd&&b.abort()):this.Ga.Fc(b)};
u.kg=function(a,b){var c=b.target;switch(b.type){case Nf:this.pe(a,c);break;case p:return this.ig(a,c,b);case ng:this.lg(a,c);break;case rg:case ce:this.jg(a,c);break;case Uc:this.gg(a,c)}return null};u.pe=function(a,b){var c=this.N.get(a);!c||c.od||c.lc()?(c&&(this.ne(b,c.Qc),this.N.remove(a)),this.Ga.Fc(b)):(c.qg(),b.send(c.getUrl(),c.Dg,c.getContent(),c.mc))};
u.ig=function(a,b,c){var d=this.N.get(a);if(7==b.za||b.Sa()||d.lc())if(this.dispatchEvent(new Sk(p,this,a,b)),d&&(d.kh(!0),d.nd))return d.nd.call(b,c);return null};u.gg=function(a,b){this.dispatchEvent(new Sk(Uc,this,a,b))};u.lg=function(a,b){this.dispatchEvent(new Sk(ng,this,a,b))};u.jg=function(a,b){this.N.get(a).lc()&&this.dispatchEvent(new Sk(ce,this,a,b))};u.ne=function(a,b,c){this.ob.Ob(a,c||Qk,b)};u.zf=function(a,b,c){this.ob.Aa(a,c||Qk,b)};
u.l=function(){Pk.h.l.call(this);this.Ga.la();this.Ga=null;this.ob.la();this.ob=null;this.N.clear();this.N=null};var Sk=function(a,b,c,d){K.call(this,a,b);this.id=c;this.Qb=d};B(Sk,K);var Rk=function(a,b,c,d,f,g,k,m,r){this.rh=a;this.Dg=c||Ob;this.If=d;this.mc=f||null;this.xc=w(k)?k:1;this.hd=0;this.bd=this.od=!1;this.Qc=b;this.nd=g;this.Ca=m||e;this.Fa=!!r;this.Qb=null};u=Rk.prototype;u.getUrl=function(){return this.rh};u.getContent=function(){return this.If};u.qg=function(){this.hd++};
u.lc=function(){return this.hd>this.xc};u.kh=function(a){this.od=a};u.jh=function(a){this.bd=a};function Tk(a,b,c,d,f,g){this.Qa=a;this.se=b;this.re=d||null;this.data=f||null;if(g){if(this.fc=g,g!=Ud&&g!=Rd&&g!=Sd&&g!=Td)throw"bad display mode: "+g;}else this.fc=Td;this.Bb=!1}Tk.prototype.Yf=function(){return this.Qa};function Uk(a){this.Nf=!0;this.C=a;this.Pb=null}u=Uk.prototype;u.qf=function(a){this.Pb=a};u.Ue=function(){return this.C.data};u.kf=function(a){return this.C.data=a};u.mf=function(a){return this.C.Bb=a};
u.Re=function(){var a={};a.type=this.Pb.He;a.instanceId=this.C.Qa;a.sectionId=this.C.se;a.actionUrl=W.bc;a.quickEditUrl=W.wd+Ea+this.Pb.He+Da+this.C.Qa+Ca+this.C.se+va+W.Tc;return a};u.Xb=function(a,b,c,d){b=b||{};window.__wavt&&(b.xssi_token=window.__wavt);W.Xb(a,b,this.C.Qa,this.Pb.He,c,d)};function W(){}W.Ye=function(a,b,c){W.ha={};W.wd=a;W.bc=b;W.nj=c;W.kc={};W.Rb=new Pk;W.ce=0;W.Dc=0;M(W.Rb,Nf,function(){W.Dc++});M(W.Rb,p,function(){W.Dc--})};W.sf=function(a){a=W.Oe(a.document);document.body.appendChild(a)};
W.rf=function(a){W.sf(window);if(window.parent==window){var b=mc;a&&(b=a);a=W.Ne(window.document,b);document.body.appendChild(a[0]);document.body.appendChild(a[1])}};W.$e=zd;W.Me=zd;W.Tc="editWidget";W.Te=function(){return W.bc};W.nf=function(a,b){W.Ac=a;W.bh=b};W.We=function(){return W.Ac};W.pf=function(a){W.uh=a};W.Uc=function(){return W.uh};W.lf=function(a){W.kc=a};W.Se=function(){var a={},b;for(b in W.kc){var c=W.kc[b];a[c.name]=c.data}c={};for(b in W.ha)c[b]=W.ha[b].B.C.data;a.widgets=c;return a};
W.Wc=function(a,b){var c=new Uk(b),d=new window[a](c);c.qf(d);W.ha[b.Qa]=d;W.Sc(d);return d};W.ff=function(a,b){var c=W.Wc(a,b);c.B.mf(!0);return c};W.Sc=function(a){a.B.C.fc!=Td&&(a.B.Nf=!1)};W.ra=function(a){return W.ha?W.ha[a]:null};W.Wb=function(a,b,c,d,f){var g=e;d&&(g=Da+d);a=W.wd+va+a+Ca+b+Ea+c+g;if(window.name==f)return window.location.replace(a),window.focus(),window;f=window.open(a,f,Ig);f.focus();return f};
W.df=function(a){var b=a.getAttribute(Ge),c=W.ra(b);if(c){var d=c.B.Ja;if(null!=d&&!d.closed)return d.focus(),!1}d=Id+b;a=W.Wb(W.Tc,a.parentNode.getAttribute(Ge),a.getAttribute(Gg),b,d);c&&(c.B.Ja=a);return!1};W.ef=function(a){W.Wb(W.Me,a.parentNode.getAttribute(Ge),a.getAttribute(Gg),a.getAttribute(Ge),W.$e);return!1};W.Pe=function(a,b,c){W.ia(c,c.LayoutsMessages.DELETING);W.Yc(Nd,{},a,b)};Uk.prototype.gf=function(a,b){W.ia(b,b.LayoutsMessages.SAVING);this.Xb(Jd,a)};
W.hf=function(a,b,c){a.sectionid=document.getElementById(Vf).value;W.ia(c,c.LayoutsMessages.SAVING);W.Yc(Zc,a,e,b)};W.Xi=function(a,b,c){C(null!=c,hf);var d=W.ra(b);C(null!=d,jf+b);d.B.C.Bb?W.hf(a,c,window):d.B.gf(a,window)};W.Xb=function(a,b,c,d,f,g){W.Xc(W.bc,a,b,c,d,f,g)};W.Yc=function(a,b,c,d,f){W.Ac&&(b.security_token=W.bh,W.Xc(W.Ac,a,b,c,d,f))};
W.Xc=function(a,b,c,d,f,g,k){b=[Xc+encodeURIComponent(b),Fg+encodeURIComponent(d),Hg+encodeURIComponent(f),Rf];for(var m in c)if(typeof c[m]==nf)for(d=c[m],f=0;f<d.length;++f)b.push(encodeURIComponent(m)+n+encodeURIComponent(d[f]));else b.push(encodeURIComponent(m)+n+encodeURIComponent(c[m]));var r=g||Ek();c=function(){r(this.a)&&window.eval(this.cg())};k==Ob?(a=0<=a.indexOf(sb)?a+l:a+sb,W.Rb.send(e+W.ce++,a+b.join(l),Ob,void 0,null,null,c)):W.Rb.send(e+W.ce++,a,kc,b.join(l),null,null,c)};
W.jf=function(a,b){if(a){var c=W.ra(a);c&&(c.B.Ja=b)}};W.cb=function(a,b){0==W.Dc?a.setTimeout(function(){a.close()},b):a.setTimeout(function(){W.cb(a,b)},200)};W.Ze=function(a,b){a&&(W.cb(a,100),W.tf(a,b))};W.tf=function(a,b){if(a){var c=a.document.getElementById(hg);c&&(c=c.innerHTML);c&&a&&a.opener.parent&&a.opener.parent.editor&&a.opener.parent.editor.SetSaveMessage(c,b)}};
W.Vc=function(a,b,c){var d=W.ha[a];null!=c.errors?((a=d?d.B.Ja:null)||(a=window),W.ia(a,c.errors),d&&d.eb?d.eb(b,c,a):W.eb(c,a)):(C(null!=d,jf+a),d.Vc(b,c))};W.eb=function(a,b){var c=a[de],d;for(d in c)Vk(d,c[d],b.document)};W.af=function(a,b){window.parent&&window.parent.editor&&b?W.bf(a,b):window.location.replace(window.location.href)};W.bf=function(a,b){var c=W.ra(a);c.B.kf(b.data);var d=document.getElementById(a);ki(d);Gk(d,c,W);c.B.Ja=null};
W.Xe=function(a,b,c){var d=c[gg];if(null!=c.errors)W.ia(window,c.errors),W.eb(c,window);else if(b==Zc){var f;W.Ub(window)&&(window.opener&&window.opener.parent&&(f=window.opener.parent),f&&f.editor&&f.editor.HandleAddNewWidget(c));W.ia(window,d);null==window.opener?window.location=Za+c.blogID:f&&f._WidgetManager?f._WidgetManager._KillPopupDelay(window):W.cb(window,100)}else c=W.ha[a],C(null!=c),b==Nd&&(W.ia(c.B.Ja,d),W.Qe(a,Gc))};
W.cf=function(a){var b=W.ra(a);b&&(b.B.C.fc==Sd?top.editor.HandleDeleteWidget(b.B.C.re):(b=b.B.C.re,b.parentNode.removeChild(b)),delete W.ha[a])};W.Qe=function(a,b,c){if(W.Ub(window)){var d=window.opener;c||(c=d._WidgetManager[b]);c(a);d._WidgetManager?d._WidgetManager._KillPopupDelay(window,a):W.cb(window,100)}else a=W.Uc()+tb+a,a+=xa+encodeURIComponent(b),window.location.replace(a)};W.Ub=function(a){var b=!1;try{if(a.opener){var c=Ac+a.opener.document.domain;c&&c!=Ac&&(b=!0)}}catch(d){}return b};
W.Zc="status-msg-yellow-on-white";W.ia=function(a,b){a||(a=self);var c=a.document.getElementById(hg);c&&(c.innerHTML=b);(c=a.document.getElementById(gg))&&Mj(c,W.Zc)};W.Kh=function(a){a||(a=self);(a=a.document.getElementById(gg))&&Oj(a,W.Zc)};W.vi=function(a){a&&0<a.length&&a.substring(0,4)!=Ae&&(a=Be+a);return a};W.Ve=function(a,b){if(E(Lj(a),b))return a;if(a)for(var c=a.childNodes.length,d=0;d<c;d++){var f=W.Ve(a.childNodes.item(d),b);if(f)return f}return null};
W.Oe=function(a){a=a.createElement(Vd);a.className=pd;a.style.position=Vc;a.style.top=$a;a.style.left=$a;a.style.width=bb;a.style.height=bb;G&&!H(7)&&(a.style.height=je);a.style.zIndex=cb;a.style.cursor=Md;a.onclick=W.Vb;a.onmousedown=W.Vb;a.onmouseup=W.Vb;a.style.background=Ag;a.style.filter=bd;a.style.opacity=Oa;a.innerHTML=Aa;return a};
W.Ne=function(a,b){var c=W.Rc(a,b),d=W.Rc(a,b);c.style.backgroundColor=ma;c.style.border=eb;G&&(c.style.filter=ga);c.style.opacity=Pa;d.style.border=fb;c.style.zIndex=1200;d.style.zIndex=1200;return[c,d]};
W.Rc=function(a,b){var c=a.createElement(Vd);c.style.position=Vc;c.style.top=lb;c.style.left=Ma;c.style.width=kb;c.style.height=ib;c.style.margin=$a;c.style.padding=db;c.style.fontSize=hb;c.style.textAlign=vd;c.style.color=na;c.style.fontFamily=ka;G&&(c.style.top=La,c.style.left=La,c.style.filter=ea);c.style.MozTransform=Uf;c.style.MozTransformOrigin=jb;c.style.WebkitTransform=Uf;c.style.WebkitTransformOrigin=jb;c.innerHTML=b;c.className=dg;return c};
W.Vb=function(a){a||(a=window.event);a&&(a.cancelBubble=!0,a.stopPropagation&&a.stopPropagation());return!1};var Wk=function(a,b){b||(b=document);return b.getElementById(ge+a)},Xk=function(a){if(a=Wk(a))ki(a),a.className=fe},Vk=function(a,b,c){if(a=Wk(a,c))a.innerHTML=b,a.className=ee};x("_WidgetManager",W,void 0);W._Init=W.Ye;W._SetPageActionUrl=W.nf;W._GetPageActionUrl=W.We;W._SetWidgetRefreshUrl=W.pf;W._GetWidgetRefreshUrl=W.Uc;W._GetCallbackUrl=W.Te;W._DeleteWidgetFromPage=W.Pe;
W._DisplayWidget=W.Sc;W._GetWidget=W.ra;W._HandleControllerResult=W.Vc;W._HandlePageActionResult=W.Xe;W._IsOpenerReachable=W.Ub;W._SetConfigWin=W.jf;W._SetDataContext=W.lf;W._SetupPreview=W.rf;W._RegisterWidget=W.Wc;W._RegisterNewWidget=W.ff;W._PopupPaneFromParams=W.Wb;W._PopupConfig=W.df;W._PopupToolbox=W.ef;W._KillPopupDelay=W.Ze;W._OnWidgetConfigured=W.af;W._OnWidgetDeleted=W.cf;x("_WidgetInfo",Tk,void 0);Tk.prototype._getInstanceId=Tk.prototype.Yf;Uk.prototype._GetData=Uk.prototype.Ue;
Uk.prototype._GenerateWidgetMetadata=Uk.prototype.Re;W._GetAllData=W.Se;x("widget_module_provide",function(a,b,c){Hk.Xf().fh(a,b,c)},void 0);function Y(a,b,c,d,f,g,k,m){this.F=a;this.kd=b!=kf?b:null;this.Ud=c;this.Sd=d;this.Td=f;this.te=g;this.Vd=k;this.ih=m;this.xb=this.xa=-1;this.oc=null;this.Wa=300;this.wc=gb;this.I=document.getElementById(this.F+Rc);this.jb=document.getElementById(this.F+Jc);this.wb=document.getElementById(this.F+Kc);this.pc=document.getElementById(this.F+Nc);this.Ld=document.getElementById(this.F+Oc);this.f=document.getElementById(this.F+Mc);this.Oa=document.getElementById(this.F+Qc);this.gd=window.frames[this.F+
Ic];this.nc=0;this.v=new Image;this.v.onload=A(this.ah,this);this.v.onerror=A(this.Rg,this);this.yd=!1;this.ua=this.w=this.Db=null;this.Ec=!1}u=Y.prototype;
u.ah=function(){this.nc=0;Xk(this.F+Pc);Xk(this.F+Lc);this.pc.checked&&0!=this.xa||(this.xa=this.v.width,this.xb=this.v.height,this.oc=this.v.src);var a=1,b=1;this.v.width>this.Wa&&(a=this.Wa/this.v.width);this.v.height>this.Wa&&(b=this.Wa/this.v.height);a=Math.min(a,b);this.I.style.width=Math.round(this.v.width*a)+Lf;this.I.style.height=Math.round(this.v.height*a)+Lf;this.I.src=this.v.src;this.I.style.display=e;this.wb.style.display=t;this.jb.style.display=e;this.f.disabled=!0;this.Ud&&this.Ud.call({},
this.I.src,this.oc,this.xa,this.xb)};u.Za=function(a,b,c,d){a?(Vk(this.F+Lc,b),Xk(this.F+Pc)):(Vk(this.F+Pc,b),Xk(this.F+Lc));this.I.style.display=t;this.wb.style.display=e;this.jb.style.display=t;this.f.disabled=!1;this.Sd&&this.Sd.call({},c,d)};u.Rg=function(){if(2>this.nc){this.nc++;var a=this.v.src;this.v.src=e;this.Ta(a)}else this.Za(this.pc.checked,WidgetMessages.SIV_INVALID_URL,this.I.src,[])};u.Ta=function(a){this.Fe();this.v.src=a};
u.Ff=function(a){a=a||window.event;window.event?(a.returnValue=!1,a.cancelBubble=!0):(a.preventDefault(),a.stopPropagation());this.I.style.display=t;this.jb.style.display=t;this.wb.style.display=e;this.f.disabled=!1;this.Oa.value=e;this.oe();this.Ec=!0;this.Td&&this.Td.call({})};u.og=function(){this.pc.checked=tg;this.Oa.value=e;this.Fe();this.Gg();this.yd=!0;try{this.w.submit()}catch(a){this.Za(!0,WidgetMessages.SIV_INVALID_URL,this.w.value,[])}this.Fg()};
u.cc=function(){var a=this.gd.document.result;if(a)if(a.hasErrors)0<a.errors.length?this.Za(!0,a.errors[0].message,this.f.value,a.errors):this.Za(!0,WidgetMessages.SIV_INVALID_URL,this.f.value,a.errors);else{var b=Math.max(a.origWidth,a.origHeight),c=this.Jd();0!=this.xa&&-1!=c&&b>c?(b=c/b,this.xa=Math.round(a.origWidth*b),this.xb=Math.round(a.origHeight*b)):(this.xa=a.origWidth,this.xb=a.origHeight);this.oc=a.mainSrc;this.Ta(a.thumbSrc)}else this.Za(!0,WidgetMessages.SIV_INVALID_URL,this.f.value,
[])};u.pg=function(a){9!=(a||window.event).keyCode&&(this.Ld.checked=tg,null!=this.Db&&(window.clearTimeout(this.Db),this.Db=null),a=A(this.yg,this),this.Db=window.setTimeout(a,1E3))};u.yg=function(){if(this.Ec||this.v.src!=this.Oa.value)this.oe(),this.Ta(this.Oa.value);this.Ec=!1};u.Ag=function(a){this.Ld.checked=!0;this.Oa.value=a;this.Ta(a)};
u.Fe=function(){this.I.src=Xa;this.I.style.width=this.wc;this.I.style.height=this.wc;this.I.style.display=e;this.wb.style.display=t;this.jb.style.display=t};
u.Gg=function(){if(!this.w){this.w=document.createElement(pe);this.w.action=Oe;this.w.method=kc;this.w.target=this.gd.name;this.w.encoding=df;this.w.style.display=t;if(this.kd){var a=document.createElement(Se);a.type=ye;a.name=od;a.value=this.kd;this.w.appendChild(a)}a=document.createElement(Se);a.type=ye;a.name=Wf;a.id=Wf;this.w.appendChild(a);a=document.createElement(Se);a.type=ye;a.name=Xf;a.value=this.ih;this.w.appendChild(a);document.body.appendChild(this.w)}a=this.Jd();-1==a&&(a=1600);document.getElementById(Wf).value=
a;this.ua={parent:this.f.parentNode,nextSibling:this.f.nextSibling};this.f.parentNode.removeChild(this.f);this.w.appendChild(this.f)};u.lh=function(a){this.Wa=a;this.wc=a+Lf};u.Fg=function(){this.w.removeChild(this.f);this.ua&&this.ua.nextSibling?this.ua.parent.insertBefore(this.f,this.ua.nextSibling):this.ua.parent.appendChild(this.f)};
u.oe=function(){var a=document.createElement(Se);a.type=le;a.name=this.f.name;a.id=this.f.id;a.onchange=this.f.onchange;var b=this.f.nextSibling;null==b?this.f.parentNode.appendChild(a):this.f.parentNode.insertBefore(a,b);this.f.parentNode.removeChild(this.f);this.f=a};u.Jd=function(){return-1==this.te&&this.Vd?this.Vd():this.te};function Z(){this.Oc={}}var Yk=new Z;Z.prototype.Jf=function(a,b,c,d,f,g,k,m){this.Oc[a]=new Y(a,b,eval(c),eval(d),eval(f),g,eval(k),m);return this.Oc[a]};
Z.prototype.Id=function(a){return this.Oc[a]};Z.prototype.cc=function(a){(a=this.Id(a))&&a.yd&&a.cc()};x("_UploadSimpleImage",Yk,void 0);Z.prototype._createUsiContainer=Z.prototype.Jf;Z.prototype._getUsiContainer=Z.prototype.Id;Z.prototype._channelResultArrived=Z.prototype.cc;Y.prototype._changeImage=Y.prototype.Ff;Y.prototype._imgUrlFileOnChange=Y.prototype.og;Y.prototype._imgUrlTextOnKeyUp=Y.prototype.pg;Y.prototype._loadInitialUrl=Y.prototype.Ag;Y.prototype._loadImageFromUrl=Y.prototype.Ta;
Y.prototype._setPreviewSize=Y.prototype.lh; })()
